import moment from "moment";
const initialValues = {
  page28: [
    {
      formCreatedDate: moment().format("DD-MM-YYYY"),
      section2: [
        {
          name: "How often do you have feelings of hopelessness?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you have self-destructive thoughts?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you have an inability to handle stress?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you have anger and aggression while under stress? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },

        {
          name: "How often do you feel you are not rested, even after long hours of sleep?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you prefer to isolate yourself from others?      ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you have unexplained lack of concern for family and friends?  ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How easily are you distracted from your tasks? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you have an inability to finish tasks? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you feel the need to consume caffeine to stay alert?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you feel your libido has been decreased? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you lose your temper for minor reasons?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you have feelings of worthlessness? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
      ],

      section3: [
        {
          name: "How often do you feel anxious or panicked for no reason?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you have feelings of dread or impending doom? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you feel knots in your stomach? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you have feelings of being overwhelmed for no reason?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you have feelings of guilt about everyday decisions?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: " How often does your mind feel restless? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How difficult is it to turn your mind off when you want to relax?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },

        {
          name: "How often do you have disorganized attention?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },

        {
          name: " How often do you worry about things you were not worried about before?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "	 How often do you have feelings of inner tension and inner excitability? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
      ],

      section4: [
        {
          name: " Do you feel your visual memory (shapes & images) has decreased?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Do you feel your verbal memory has decreased?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Do you have memory lapses?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Has your creativity decreased?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Has your comprehension diminished?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Do you have difficulty calculating numbers?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: " Do you have difficulty recognizing objects & faces? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },

        {
          name: "Do you feel like your opinion about yourself has changed?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Are you experiencing excessive urination?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Are you experiencing a slower mental response?         ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
      ],

      section5: [
        {
          name: "A decrease in mental alertness",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "A decrease in mental speed ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "A decrease in concentration quality",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Slow cognitive processing ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Impaired mental performance",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "An increase in the ability to be distracted ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Need coffee or caffeine sources to improve mental function",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
      ],
    },
  ],
};

export default initialValues;
