import moment from "moment";
const initialValues = {
  page18: [
    {
      CategoryXII: [
        {
          name: "Cannot stay asleep",
          CategoryXII0check: false,
          CategoryXII1check: false,
          CategoryXII2check: false,
          CategoryXII3check: false,
        },
        {
          name: "Crave salt",
          CategoryXII0check: false,
          CategoryXII1check: false,
          CategoryXII2check: false,
          CategoryXII3check: false,
        },
        {
          name: "Slow starter in the morning",
          CategoryXII0check: false,
          CategoryXII1check: false,
          CategoryXII2check: false,
          CategoryXII3check: false,
        },
        {
          name: "Afternoon fatigue",
          CategoryXII0check: false,
          CategoryXII1check: false,
          CategoryXII2check: false,
          CategoryXII3check: false,
        },
        {
          name: "Dizziness when standing up quickly",
          CategoryXII0check: false,
          CategoryXII1check: false,
          CategoryXII2check: false,
          CategoryXII3check: false,
        },
        {
          name: "Afternoon headaches",
          CategoryXII0check: false,
          CategoryXII1check: false,
          CategoryXII2check: false,
          CategoryXII3check: false,
        },
        {
          name: "Headaches with exertion or stress",
          CategoryXII0check: false,
          CategoryXII1check: false,
          CategoryXII2check: false,
          CategoryXII3check: false,
        },
        {
          name: "Weak nails",
          CategoryXII0check: false,
          CategoryXII1check: false,
          CategoryXII2check: false,
          CategoryXII3check: false,
        },
      ],
      CategoryXIII: [
        {
          name: "Cannot fall asleep",
          CategoryXIII0check: false,
          CategoryXIII1check: false,
          CategoryXIII2check: false,
          CategoryXIII3check: false,
        },
        {
          name: "Perspire easily",
          CategoryXIII0check: false,
          CategoryXIII1check: false,
          CategoryXIII2check: false,
          CategoryXIII3check: false,
        },
        {
          name: "Under a high amount of stress",
          CategoryXIII0check: false,
          CategoryXIII1check: false,
          CategoryXIII2check: false,
          CategoryXIII3check: false,
        },
        {
          name: "Weight gain when under stress",
          CategoryXIII0check: false,
          CategoryXIII1check: false,
          CategoryXIII2check: false,
          CategoryXIII3check: false,
        },
        {
          name: "Wake up tired even after 6 or more hours of sleep",
          CategoryXIII0check: false,
          CategoryXIII1check: false,
          CategoryXIII2check: false,
          CategoryXIII3check: false,
        },
        {
          name: "Excessive perspiration or perspiration with little or no activity",
          CategoryXIII0check: false,
          CategoryXIII1check: false,
          CategoryXIII2check: false,
          CategoryXIII3check: false,
        },
      ],
      CategoryXIV: [
        {
          name: "Edema and swelling in ankles and wrists",
          CategoryXIV0check: false,
          CategoryXIV1check: false,
          CategoryXIV2check: false,
          CategoryXIV3check: false,
        },
        {
          name: "Muscle cramping",
          CategoryXIV0check: false,
          CategoryXIV1check: false,
          CategoryXIV2check: false,
          CategoryXIV3check: false,
        },
        {
          name: "Poor muscle endurance",
          CategoryXIV0check: false,
          CategoryXIV1check: false,
          CategoryXIV2check: false,
          CategoryXIV3check: false,
        },
        {
          name: "Frequent urination",
          CategoryXIV0check: false,
          CategoryXIV1check: false,
          CategoryXIV2check: false,
          CategoryXIV3check: false,
        },
        {
          name: "Frequent thirst",
          CategoryXIV0check: false,
          CategoryXIV1check: false,
          CategoryXIV2check: false,
          CategoryXIV3check: false,
        },
        {
          name: "Crave salt",
          CategoryXIV0check: false,
          CategoryXIV1check: false,
          CategoryXIV2check: false,
          CategoryXIV3check: false,
        },
        {
          name: "Abnormal sweating from minimal activity",
          CategoryXIV0check: false,
          CategoryXIV1check: false,
          CategoryXIV2check: false,
          CategoryXIV3check: false,
        },
        {
          name: "Alteration in bowel regularity",
          CategoryXIV0check: false,
          CategoryXIV1check: false,
          CategoryXIV2check: false,
          CategoryXIV3check: false,
        },
        {
          name: "Inability to hold breath for long periods",
          CategoryXIV0check: false,
          CategoryXIV1check: false,
          CategoryXIV2check: false,
          CategoryXIV3check: false,
        },
        {
          name: "Shallow, rapid breathing",
          CategoryXIV0check: false,
          CategoryXIV1check: false,
          CategoryXIV2check: false,
          CategoryXIV3check: false,
        },
      ],
      CategoryXV: [
        {
          name: "Tired/sluggish",
          CategoryXV0check: false,
          CategoryXV1check: false,
          CategoryXV2check: false,
          CategoryXV3check: false,
        },
        {
          name: "Feel cold―hands, feet, all over",
          CategoryXV0check: false,
          CategoryXV1check: false,
          CategoryXV2check: false,
          CategoryXV3check: false,
        },
        {
          name: "Require excessive amounts of sleep to function properly",
          CategoryXV0check: false,
          CategoryXV1check: false,
          CategoryXV2check: false,
          CategoryXV3check: false,
        },
        {
          name: "Increase in weight even with low-calorie diet",
          CategoryXV0check: false,
          CategoryXV1check: false,
          CategoryXV2check: false,
          CategoryXV3check: false,
        },
        {
          name: "Gain weight easily",
          CategoryXV0check: false,
          CategoryXV1check: false,
          CategoryXV2check: false,
          CategoryXV3check: false,
        },
        {
          name: "Difficult, infrequent bowel movements",
          CategoryXV0check: false,
          CategoryXV1check: false,
          CategoryXV2check: false,
          CategoryXV3check: false,
        },
        {
          name: "Depression/lack of motivation",
          CategoryXV0check: false,
          CategoryXV1check: false,
          CategoryXV2check: false,
          CategoryXV3check: false,
        },
        {
          name: "Morning headaches that wear off as the day progresses",
          CategoryXV0check: false,
          CategoryXV1check: false,
          CategoryXV2check: false,
          CategoryXV3check: false,
        },
        {
          name: "Outer third of eyebrow thins",
          CategoryXV0check: false,
          CategoryXV1check: false,
          CategoryXV2check: false,
          CategoryXV3check: false,
        },
        {
          name: "Thinning of hair on scalp, face, or genitals, or excessive hair loss",
          CategoryXV0check: false,
          CategoryXV1check: false,
          CategoryXV2check: false,
          CategoryXV3check: false,
        },
        {
          name: "Dryness of skin and/or scalp",
          CategoryXV0check: false,
          CategoryXV1check: false,
          CategoryXV2check: false,
          CategoryXV3check: false,
        },
        {
          name: "Mental sluggishness",
          CategoryXV0check: false,
          CategoryXV1check: false,
          CategoryXV2check: false,
          CategoryXV3check: false,
        },
      ],
      CategoryXVI: [
        {
          name: "Heart palpitations",
          CategoryXVI0check: false,
          CategoryXVI1check: false,
          CategoryXVI2check: false,
          CategoryXVI3check: false,
        },
        {
          name: "Inward trembling",
          CategoryXVI0check: false,
          CategoryXVI1check: false,
          CategoryXVI2check: false,
          CategoryXVI3check: false,
        },
        {
          name: "Increased pulse even at rest",
          CategoryXVI0check: false,
          CategoryXVI1check: false,
          CategoryXVI2check: false,
          CategoryXVI3check: false,
        },
        // {
        //   name: "Pain prevents me from walking more than 100 yards.",
        //   CategoryXVI0check: false,
        //   CategoryXVI1check: false,
        //   CategoryXVI2check: false,
        //   CategoryXVI3check: false,
        // },
        {
          name: "Nervous and emotional",
          CategoryXVI0check: false,
          CategoryXVI1check: false,
          CategoryXVI2check: false,
          CategoryXVI3check: false,
        },
        {
          name: "Insomnia",
          CategoryXVI0check: false,
          CategoryXVI1check: false,
          CategoryXVI2check: false,
          CategoryXVI3check: false,
        },
        // {
        //   name: "Night sweats",
        //   CategoryXVI0check: false,
        //   CategoryXVI1check: false,
        //   CategoryXVI2check: false,
        //   CategoryXVI3check: false,
        // },
        // ,
        // {
        //   name: "Difficulty gaining weight",
        //   CategoryXVI0check: false,
        //   CategoryXVI1check: false,
        //   CategoryXVI2check: false,
        //   CategoryXVI3check: false,
        // },
      ],
      CategoryXVICont: [
        {
          name: "Night sweats",
          CategoryXVICont0check: false,
          CategoryXVICont1check: false,
          CategoryXVICont2check: false,
          CategoryXVICont3check: false,
        },
        {
          name: "Difficulty gaining weight",
          CategoryXVICont0check: false,
          CategoryXVICont1check: false,
          CategoryXVICont2check: false,
          CategoryXVICont3check: false,
        },
      ],
      CategoryXVII: [
        {
          name: "Urination difficulty or dribbling",
          CategoryXVII0check: false,
          CategoryXVII1check: false,
          CategoryXVII2check: false,
          CategoryXVII3check: false,
        },
        {
          name: "Frequent urination",
          CategoryXVII0check: false,
          CategoryXVII1check: false,
          CategoryXVII2check: false,
          CategoryXVII3check: false,
        },
        {
          name: "Pain inside of legs or heels",
          CategoryXVII0check: false,
          CategoryXVII1check: false,
          CategoryXVII2check: false,
          CategoryXVII3check: false,
        },
        {
          name: "Feeling of incomplete bowel emptying",
          CategoryXVII0check: false,
          CategoryXVII1check: false,
          CategoryXVII2check: false,
          CategoryXVII3check: false,
        },
        {
          name: "Leg twitching at night",
          CategoryXVII0check: false,
          CategoryXVII1check: false,
          CategoryXVII2check: false,
          CategoryXVII3check: false,
        },
      ],
      CategoryXVIII: [
        {
          name: "Decreased libido",
          CategoryXVIII0check: false,
          CategoryXVIII1check: false,
          CategoryXVIII2check: false,
          CategoryXVIII3check: false,
        },
        {
          name: "Decreased number of spontaneous morning erections",
          CategoryXVIII0check: false,
          CategoryXVIII1check: false,
          CategoryXVIII2check: false,
          CategoryXVIII3check: false,
        },
        {
          name: "Decreased fullness of erections",
          CategoryXVIII0check: false,
          CategoryXVIII1check: false,
          CategoryXVIII2check: false,
          CategoryXVIII3check: false,
        },
        {
          name: "Difficulty maintaining morning erections",
          CategoryXVIII0check: false,
          CategoryXVIII1check: false,
          CategoryXVIII2check: false,
          CategoryXVIII3check: false,
        },
        {
          name: "Spells of mental fatigue",
          CategoryXVIII0check: false,
          CategoryXVIII1check: false,
          CategoryXVIII2check: false,
          CategoryXVIII3check: false,
        },
        {
          name: "Inability to concentrate",
          CategoryXVIII0check: false,
          CategoryXVIII1check: false,
          CategoryXVIII2check: false,
          CategoryXVIII3check: false,
        },
        {
          name: "Episodes of depression",
          CategoryXVIII0check: false,
          CategoryXVIII1check: false,
          CategoryXVIII2check: false,
          CategoryXVIII3check: false,
        },
        {
          name: "Muscle soreness",
          CategoryXVIII0check: false,
          CategoryXVIII1check: false,
          CategoryXVIII2check: false,
          CategoryXVIII3check: false,
        },
        {
          name: "Decreased physical stamina",
          CategoryXVIII0check: false,
          CategoryXVIII1check: false,
          CategoryXVIII2check: false,
          CategoryXVIII3check: false,
        },
        {
          name: "Unexplained weight gain",
          CategoryXVIII0check: false,
          CategoryXVIII1check: false,
          CategoryXVIII2check: false,
          CategoryXVIII3check: false,
        },
        {
          name: "Increase in fat distribution around chest and hips",
          CategoryXVIII0check: false,
          CategoryXVIII1check: false,
          CategoryXVIII2check: false,
          CategoryXVIII3check: false,
        },
        {
          name: "Sweating attacks",
          CategoryXVIII0check: false,
          CategoryXVIII1check: false,
          CategoryXVIII2check: false,
          CategoryXVIII3check: false,
        },

        {
          name: "More emotional than in the past",
          CategoryXVIII0check: false,
          CategoryXVIII1check: false,
          CategoryXVIII2check: false,
          CategoryXVIII3check: false,
        },
      ],
      CategoryXIX: [
        {
          name: "Perimenopausal",
          CategoryXIXradio: "test",
        },
        {
          name: "Alternating menstrual cycle lengths",
          CategoryXIXradio: "test",
        },
        {
          name: "Extended menstrual cycle (greater than 32 days)",
          CategoryXIXradio: "test",
        },
        {
          name: "Shortened menstrual cycle (less than 24 days)",
          CategoryXIXradio: "test",
        },
        {
          name: "Pain and cramping during periods",
          CategoryXIX0check: false,
          CategoryXIX1check: false,
          CategoryXIX2check: false,
          CategoryXIX3check: false,
        },
        {
          name: "Scanty blood flow",
          CategoryXIX0check: false,
          CategoryXIX1check: false,
          CategoryXIX2check: false,
          CategoryXIX3check: false,
        },
        {
          name: "Heavy blood flow",
          CategoryXIX0check: false,
          CategoryXIX1check: false,
          CategoryXIX2check: false,
          CategoryXIX3check: false,
        },
        {
          name: "Breast pain and swelling during menses",
          CategoryXIX0check: false,
          CategoryXIX1check: false,
          CategoryXIX2check: false,
          CategoryXIX3check: false,
        },
        {
          name: "Pelvic pain during menses",
          CategoryXIX0check: false,
          CategoryXIX1check: false,
          CategoryXIX2check: false,
          CategoryXIX3check: false,
        },
        {
          name: "Irritable and depressed during menses",
          CategoryXIX0check: false,
          CategoryXIX1check: false,
          CategoryXIX2check: false,
          CategoryXIX3check: false,
        },
        {
          name: "Acne",
          CategoryXIX0check: false,
          CategoryXIX1check: false,
          CategoryXIX2check: false,
          CategoryXIX3check: false,
        },
        {
          name: "Facial hair growth",
          CategoryXIX0check: false,
          CategoryXIX1check: false,
          CategoryXIX2check: false,
          CategoryXIX3check: false,
        },
        {
          name: "Hair loss/thinning",
          CategoryXIX0check: false,
          CategoryXIX1check: false,
          CategoryXIX2check: false,
          CategoryXIX3check: false,
        },
      ],
      CategoryXX: [
        {
          name: "How many years have you been menopausal?",
          CategoryXXinput: "",
        },
        {
          name: "Since menopause, do you ever have uterine bleeding?",
          CategoryXXradio: "",
          // CategoryXXno: "",
        },
        {
          name: "Hot flashes",
          CategoryXX0check: false,
          CategoryXX1check: false,
          CategoryXX2check: false,
          CategoryXX3check: false,
        },
        {
          name: "Mental fogginess",
          CategoryXX0check: false,
          CategoryXX1check: false,
          CategoryXX2check: false,
          CategoryXX3check: false,
        },
        {
          name: "Disinterest in sex",
          CategoryXX0check: false,
          CategoryXX1check: false,
          CategoryXX2check: false,
          CategoryXX3check: false,
        },
        {
          name: "Mood swings",
          CategoryXX0check: false,
          CategoryXX1check: false,
          CategoryXX2check: false,
          CategoryXX3check: false,
        },
        {
          name: "Depression",
          CategoryXX0check: false,
          CategoryXX1check: false,
          CategoryXX2check: false,
          CategoryXX3check: false,
        },
        {
          name: "Painful intercourse",
          CategoryXX0check: false,
          CategoryXX1check: false,
          CategoryXX2check: false,
          CategoryXX3check: false,
        },
        {
          name: "Shrinking breasts",
          CategoryXX0check: false,
          CategoryXX1check: false,
          CategoryXX2check: false,
          CategoryXX3check: false,
        },
        {
          name: "Facial hair growth",
          CategoryXX0check: false,
          CategoryXX1check: false,
          CategoryXX2check: false,
          CategoryXX3check: false,
        },
        {
          name: "Acne",
          CategoryXX0check: false,
          CategoryXX1check: false,
          CategoryXX2check: false,
          CategoryXX3check: false,
        },
        {
          name: "Increased vaginal pain, dryness, or itching",
          CategoryXX0check: false,
          CategoryXX1check: false,
          CategoryXX2check: false,
          CategoryXX3check: false,
        },
      ],
      alcoholicBeverages: "",
      caffeinatedBeverages: "",
      eatCount: "",
      stressLevel: "",
      eatFishCount: "",
      workoutCount: "",
      nutCount: "",
      worstFoodA: "",
      worstFoodB: "",
      worstFoodC: "",
      healthyFoodA: "",
      healthyFoodB: "",
      healthyFoodC: "",
      CategoryXXinput: "",
      supplements: "",
      medication: "",
      formCreatedDate: moment().format("DD-MM-YYYY"),
    },
  ],
};

export default initialValues;
