const form = {
    formField:{
        OrbitofrontalCheck:{
            type:'checkbox',
            name:"OrbitofrontalCheck"
          },
          PrecentralCheck:{
            type:'checkbox',
            name:"PrecentralCheck"
          },
          BrocaCheck:{
            type:'checkbox',
            name:"BrocaCheck"
          },
          SomatosensoryCheck:{
            type:'checkbox',
            name:"SomatosensoryCheck"
          },
          InferiorCheck:{
            type:'checkbox',
            name:"InferiorCheck"
          },
          AuditoryCheck:{
            type:'checkbox',
            name:"AuditoryCheck"
          },
          AssociationCheck:{
            type:'checkbox',
            name:"AssociationCheck"
          },
          HippocampusCheck:{
            type:'checkbox',
            name:"HippocampusCheck"
          },
          OccipitalCheck:{
            type:'checkbox',
            name:"OccipitalCheck"
          },
          SpinocerebellumCheck:{
            type:'checkbox',
            name:"SpinocerebellumCheck"
          },
          CerebrocerebellumCheck:{
            type:'checkbox',
            name:"CerebrocerebellumCheck"
          },
          VestibulocerebellumCheck:{
            type:'checkbox',
            name:"VestibulocerebellumCheck"
          },
          DirectCheck:{
            type:'checkbox',
            name:"DirectCheck"
          },
          IndirectCheck:{
            type:'checkbox',
            name:"IndirectCheck"
          },
          ParasympatheticCheck:{
            type:'checkbox',
            name:"ParasympatheticCheck"
          },
          SympatheticCheck:{
            type:'checkbox',
            name:"SympatheticCheck"
          },
          EpileptiformCheck:{
            type:'checkbox',
            name:"EpileptiformCheck"
          },

          category1Check:{
            type:'checkbox',
            name:"category1Check"
          },
          category2Check:{
            type:'checkbox',
            name:"category2Check"
          },
          category3Check:{
            type:'checkbox',
            name:"category3Check"
          },
          category1Check:{
            type:'checkbox',
            name:"category1Check"
          },
          category1Check:{
            type:'checkbox',
            name:"category1Check"
          },
          category4Check:{
            type:'checkbox',
            name:"category4Check"
          },
          category5Check:{
            type:'checkbox',
            name:"category5Check"
          },
          category6Check:{
            type:'checkbox',
            name:"category6Check"
          },
          category7Check:{
            type:'checkbox',
            name:"category7Check"
          },
          category8Check:{
            type:'checkbox',
            name:"category8Check"
          },
          category9Check:{
            type:'checkbox',
            name:"category9Check"
          },
          category10Check:{
            type:'checkbox',
            name:"category10Check"
          }, 
          category11Check:{
            type:'checkbox',
            name:"category11Check"
          },
          category1Check:{
            type:'checkbox',
            name:"category1Check"
          },
          category12Check:{
            type:'checkbox',
            name:"category12Check"
          },
          category13Check:{
            type:'checkbox',
            name:"category13Check"
          },
          category14Check:{
            type:'checkbox',
            name:"category14Check"
          },
          category15Check:{
            type:'checkbox',
            name:"category15Check"
          },
          category16Check:{
            type:'checkbox',
            name:"category16Check"
          },
          category17Check:{
            type:'checkbox',
            name:"category17Check"
          },
          category18Check:{
            type:'checkbox',
            name:"category18Check"
          },
          category19Check:{
            type:'checkbox',
            name:"category19Check"
          },
          category20Check:{
            type:'checkbox',
            name:"category20Check"
          },
    }

}

export default form;