import moment from "moment";
import checkout from "./form";

const {
  formField: {
    OrbitofrontalCheck,

    PrecentralCheck,
    BrocaCheck,

    SomatosensoryCheck,
    InferiorCheck,
    AuditoryCheck,
    AssociationCheck,
    HippocampusCheck,
    OccipitalCheck,
    SpinocerebellumCheck,
    CerebrocerebellumCheck,
    VestibulocerebellumCheck,
    DirectCheck,
    IndirectCheck,
    ParasympatheticCheck,
    SympatheticCheck,
    EpileptiformCheck,
    category1Check,
    category2Check,
    category3Check,
    category4Check,
    category5Check,
    category6Check,
    category7Check,
    category8Check,
    category9Check,
    category10Check,
    category11Check,
    category12Check,
    category13Check,
    category14Check,
    category15Check,
    category16Check,
    category17Check,
    category18Check,
    category19Check,
    category20Check,
  },
} = checkout;

const initialValues = {
  eleventhPage: [
    {
      [OrbitofrontalCheck.name]: false,
      [PrecentralCheck.name]: false,
      [BrocaCheck.name]: false,
      [SomatosensoryCheck.name]: false,
      [InferiorCheck.name]: false,
      [AuditoryCheck.name]: false,
      [AssociationCheck.name]: false,
      [HippocampusCheck.name]: false,
      [OccipitalCheck.name]: false,
      [SpinocerebellumCheck.name]: false,
      [CerebrocerebellumCheck.name]: false,
      [VestibulocerebellumCheck.name]: false,
      [DirectCheck.name]: false,
      [IndirectCheck.name]: false,
      [ParasympatheticCheck.name]: false,
      [SympatheticCheck.name]: false,
      [EpileptiformCheck.name]: false,

      [category1Check.name]: false,
      [category2Check.name]: false,
      [category3Check.name]: false,
      [category4Check.name]: false,
      [category5Check.name]: false,
      [category6Check.name]: false,
      [category7Check.name]: false,
      [category8Check.name]: false,
      [category9Check.name]: false,
      [category10Check.name]: false,
      [category11Check.name]: false,
      [category12Check.name]: false,
      [category13Check.name]: false,
      [category14Check.name]: false,
      [category15Check.name]: false,
      [category16Check.name]: false,
      [category17Check.name]: false,
      [category18Check.name]: false,
      [category19Check.name]: false,
      [category20Check.name]: false,
      formCreatedDate: moment().format("DD-MM-YYYY"),
      patientDetailsForm: {
        PractitionerName: "",
        NPI: "",
        TIN: "",
        hourlyRate: "",
        patientName: "",
        name: "",
        isNewPatient: false,
        isFollowUpPatient: false,
        isNewComplaintPatient: false,
        patientVisitNumber: "",
        patientTodaysDate: "",
        patientNextReExam: "",
        patientDob: "",
        patientAge: "",
        patientHeight: "",
        patientHeightNI: false,
        patientWeight: "",
        patientWeightNI: false,
        patientHtnYes: false,
        patientHtnNo: false,
        patientCautions: "",
      },
    },
  ],
};
export default initialValues;
