import moment from "moment";
const initialValues = {
  page23: [
    {
      name: "",
      age: "",
      gender: "",
      date: "",
      formCreatedDate: moment().format("DD-MM-YYYY"),
      sections1: [
        {
          name: "A decrease in attention span",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Mental fatigue",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty learning new things",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty staying focused and concentrating for extended periods of time",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Experiencing fatigue when reading sooner than in the past",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Experiencing fatigue when driving sooner than in the past",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Need for caffeine to stay mentally alert",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Overall brain function impairs your daily life",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
      ],
      sections2: [
        {
          name: "Twitching or tremor in your hands and legs when resting",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Handwriting has gotten smaller and more crowded together",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "A loss of smell to foods",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty sleeping or fitful sleep",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Stiffness in shoulders and hips that goes away when you start to move",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Constipation",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Voice has become softer",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Facial expression that is serious or angry",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Episodes of dizziness or light-headedness upon standing",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "A hunched over posture when getting up and walking",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
      ],
      sections3: [
        {
          name: "Memory loss that impacts daily activities",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty planning, problem solving,or working with numbers",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty completing daily tasks",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Confusion about dates, the passage of time, or place",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty understanding visual images and spatial relationships (addresses and locations)",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty finding words when speaking",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Misplacement of things and inability to retrace steps",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Poor judgment and bad decisions",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Disinterest in hobbies, social activities, or work	",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Personality or mood changes",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
      ],
      sections4: [
        {
          name: "Reduced function in overall hearing",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty understanding language with background or scatter noise",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Ringing or buzzing in the ear",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty comprehending language without perfect pronunciation",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty recognizing familiar faces",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Changes in comprehending the meaning of sentences, written or spoken",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty with verbal memory and finding words ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty remembering events",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty recalling previously learned facts and names",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Inability to comprehend familiar words when read",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty spelling familiar words",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Monotone, unemotional speech",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty understanding the emotions of others when they speak (nonverbal cues)",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Disinterest in music and a lack of appreciation for melodies",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty with long-term memory",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Memory impairment when doing the basic activities of daily living",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty with directions and visual memory",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Noticeable differences in energy levels throughout the day",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
      ],
      sections5: [
        {
          name: "Difficulty coordinating visual inputs and hand movements, resulting in an inability to efficiently reach for objects",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty comprehending written text",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Floaters or halos in your visual field",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Dullness of colors in your visual field during different times of the day",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty discriminating similar shades of color",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
      ],
    },
  ],
};

export default initialValues;
