export const steps = [
  {
    title: "Profile",
    content: "User Profile Details",
    target: "#profile",
    placement: "left",
    placementBeacon: "center",
    disableBeacon: true,
    continuous: true,
  },
  {
    title: "Messages",
    content: "In Buser Institute Available Message Facility",
    target: "#messages",
    placement: "bottom",
    disableBeacon: true,
    continuous: true,
  },
  {
    title: "Doctor Soap Form",
    content: "Buser Institute Doctor-Soap Form",
    target: "#doctor-soap-form",
    placement: "bottom",
    disableBeacon: true,
    continuous: true,
  },
  {
    title: "Client Intake Form",
    content: "Buser Institute Client Intake Form",
    target: "#client-intake-form",
    placement: "bottom",
    disableBeacon: true,
    continuous: true,
  },
  {
    title: "Informed Consent",
    content: "Buser Institute Informed Consent",
    target: "#informedConsent",
    placement: "right",
    disableBeacon: true,
    continuous: true,
  },
  {
    title: "Practitioner Agreement",
    content: "Buser Institute Practitioner Agreement",
    target: "#associate-practitioner-agreement",
    placement: "right",
    disableBeacon: true,
    continuous: true,
  },
  {
    title: "Welcome Page",
    content: "Buser Institute Welcome Page",
    target: "#welcome",
    placement: "right",
    disableBeacon: true,
    continuous: true,
  },
  {
    title: "Home Page",
    content: "Buser Institute Home Page",
    target: "#home",
    placement: "right",
    disableBeacon: true,
    continuous: true,
  },
  {
    title: "Services",
    content: "Buser Institute Services",
    target: "#services",
    placement: "right",
    // continuous: true,
  },
  {
    title: "Calender",
    content: "Buser Institute Calender",
    target: "#calendar",
    placement: "right",
  },
  {
    title: "Schedule",
    content: "Buser Institute Schedule",
    target: "#schedule",
    placement: "right",
  },
  {
    title: "Upcoming Events",
    content: "Buser Institute Upcoming Events",
    target: "#upcomingEvents",
    placement: "right",
  },
  {
    title: "Upcoming Clients",
    content: "Buser Institute Upcoming Clients",
    target: "#upcomingClients",
    placement: "right",
  },
  {
    title: "Book Appointments",
    content: "Buser Institute Book Appointments",
    target: "#book-appointments",
    placement: "right",
  },
  {
    title: "Upcoming Appointments",
    content: "Buser Institute Upcoming Appointments",
    target: "#upcoming-appointments",
    placement: "right",
  },
  {
    title: "Photo Therapy",
    content: "Buser Institute Photo Therapy",
    target: "#photo-therapy",
    placement: "right",
  },
  {
    title: "Video Messaging Therapy",
    content: "Buser Institute Video Messaging Therapy",
    target: "#video-messaging-therapy",
    placement: "right",
  },
  {
    title: "Live Video Therapy Portal",
    content: "Buser Institute Live Video Therapy Portal",
    target: "#live-video-portal",
    placement: "right",
  },
  {
    title: "Photos and Videos",
    content: "Buser Institute Photos and Videos",
    target: "#photo-video",
    placement: "right",
  },
  {
    title: "Labs",
    content: "Buser Institute Labs",
    target: "#labs",
    placement: "right",
  },
  {
    title: "Sequences",
    content: "Buser Institute Sequences",
    target: "#sequences",
    placement: "right",
  },
  {
    title: "Nutrition",
    content: "Buser Institute Nutrition",
    target: "#nutrition",
    placement: "right",
  },
  {
    title: "Daily Updates",
    content: "Buser Institute Daily Updates",
    target: "#daily-updates",
    placement: "right",
  },
  {
    title: "Progress Chart",
    content: "Buser Institute Progress Chart",
    target: "#progress-chart",
    placement: "right",
  },
  {
    title: "Patient Records",
    content: "Buser Institute Patient Records",
    target: "#patient-Records",
    placement: "right",
  },
  {
    title: "SOAP Notes",
    content: "Buser Institute SOAP Notes",
    target: "#SOAP-Note",
    placement: "right",
  },
  {
    title: "Clinical Guideline Program",
    content: "Buser Institute Clinical Guideline Program",
    target: "#Clinical-Guideline-Program",
    placement: "right",
  },
  {
    title: "Sequence Generator",
    content: "Buser Institute Sequence Generator",
    target: "#Sequence-Generator",
    placement: "right",
  },
  {
    title: "Work History",
    content: "Buser Institute Work History",
    target: "#Work-History",
    placement: "right",
  },
  {
    title: "Education",
    content: "Buser Institute Education",
    target: "#Education",
    placement: "right",
  },
  {
    title: "Education Material",
    content: "Buser Institute Education Material",
    target: "#Education-Material",
    placement: "right",
  },
  {
    title: "Equipment",
    content: "Buser Institute Equipment",
    target: "#equipment",
    placement: "right",
  },
  {
    title: "Contact Us",
    content: "Buser Institute Contact Us",
    target: "#contact-us",
    placement: "top",
    placementBeacon: "right",
  },
];
