import checkout from "./form";

const {
  formField: {
    PractitionerName,
    NPI,
    TIN,
    hourlyRate,

    PatientName,
    newPatient,
    patientFollowUp,
    patientNewComplaint,
    visitNumber,
    patienttodaysDate,
    patientNextReExam,
    patientDob,
    patientAge,
    patientHeight,
    patientHeightNi,
    patientWeight,
    patientWeightNi,
    patientHtnYes,
    patientHtnNo,
    patientCautions,

    isImproved,
    isNoChanges,
    isRegressed,
    isFlareUp,
    additionalAssessment,

    doe,
    isVitals,
    bp,
    mmHG,
    pulse,
    temp,
    rr,
    spo2,
    isNeurologicalExam,
    isCranialNerves,
    cranialNerves,
    isRombergs,
    rombergs,
    isDiadichodyskinesia,
    diadichodyskinesia,
    isDermatomes,
    dermatomes,
    isMyotomes,
    myotomes,
    isDtrs,
    dtrs,
    isPathological,
    pathological,
    isHomans,
    homans,

    // flexion60_exam,
    // flexion60_pain,
    // flexion60_noPain,
    // flexion60_location,
    // flexion60_left,
    // flexion60_right,

    // extension50_exam,
    // extension50_pain,
    // extension50_noPain,
    // extension50_location,
    // extension50_left,
    // extension50_right,

    // leftLateralFlexion40_pain,
    // leftLateralFlexion40_noPain,

    // rightLateralFlexion40_pain,
    // rightLateralFlexion40_noPain,

    // leftRotation80_pain,
    // leftRotation80_noPain,

    // rightRotation80_pain,
    // rightRotation80_noPain,

    // cervicalRegionalNotes1,
    // cervicalRegionalNotes2,

    // flexion90_pain,
    // flexion90_noPain,
    // extension30_pain,
    // extension30_noPain,
    // leftLateralFlexion20_pain,
    // leftLateralFlexion20_noPain,
    // rightLateralFlexion20_pain,
    // rightLateralFlexion20_noPain,
    // leftRotation30_pain,
    // leftRotation30_noPain,
    // rightRotation30_pain,
    // rightRotation30_noPain,

    lumbarRegionalNotes1,
    MaximalForaminalCompression_left,
    MaximalForaminalCompression_right,
    ODonoghuesManeuver,

    // flexion90_left,
    // flexion90_right,
    // extension30_left,
    // extension30_right,
    // leftLateralFlexion20_left,
    // leftLateralFlexion20_right,
    // rightLateralFlexion20_left,
    // rightLateralFlexion20_right,
    // leftRotation30_left,
    // leftRotation30_right,
    // rightRotation30_left,
    // rightRotation30_right,
    Yeomans_left,
    Yeomans_right,

    isLtC0,
    isLtC1,
    isLtC2,
    isLtC3,
    isLtC4,
    isLtC5,
    isLtC6,
    isLtC7,

    isRtC0,
    isRtC1,
    isRtC2,
    isRtC3,
    isRtC4,
    isRtC5,
    isRtC6,
    isRtC7,

    isLtT1,
    isLtT2,
    isLtT3,
    isLtT4,
    isLtT5,
    isLtT6,
    isLtT7,
    isLtT8,
    isLtT9,
    isLtT10,
    isLtT11,
    isLtT12,

    isRtT1,
    isRtT2,
    isRtT3,
    isRtT4,
    isRtT5,
    isRtT6,
    isRtT7,
    isRtT8,
    isRtT9,
    isRtT10,
    isRtT11,
    isRtT12,

    isLtL1,
    isLtL2,
    isLtL3,
    isLtL4,
    isLtL5,

    isRtL1,
    isRtL2,
    isRtL3,
    isRtL4,
    isRtL5,

    isLtSij,
    isRtSij,

    isOther,
  },
} = checkout;
console.log("PractitionerName..", PractitionerName);
const initialValues = {
  // [PractitionerName.name]: "",
  // [NPI.name]: "",
  // [TIN.name]: "",
  // [hourlyRate.name]: "",

  // [PatientName.name]: "",
  // [newPatient.name]: false,
  // [patientFollowUp.name]: false,
  // [patientNewComplaint.name]: false,
  // [visitNumber.name]: "",
  // [patienttodaysDate.name]: "",
  // [patientNextReExam.name]: "",
  // [patientDob.name]: "",
  // [patientAge.name]: "",
  // [patientHeight.name]: "",
  // [patientHeightNi.name]: false,
  // [patientWeight.name]: "",
  // [patientWeightNi.name]: false,
  // [patientHtnYes.name]: false,
  // [patientHtnNo.name]: false,
  // [patientCautions.name]: "",
  fifteenthPage: [
    {
      [isImproved.name]: false,
      [isNoChanges.name]: false,
      [isRegressed.name]: false,
      [isFlareUp.name]: false,
      [additionalAssessment.name]: "",

      [doe.name]: "",
      [isVitals.name]: false,
      [bp.name]: "",
      [mmHG.name]: "",
      [pulse.name]: "",
      [temp.name]: "",
      [rr.name]: "",
      [spo2.name]: "",
      [isNeurologicalExam.name]: false,
      [isCranialNerves.name]: false,
      [cranialNerves.name]: "",
      [isRombergs.name]: false,
      [rombergs.name]: "",
      [isDiadichodyskinesia.name]: false,
      [diadichodyskinesia.name]: "",
      [isDermatomes.name]: false,
      [dermatomes.name]: "",
      [isMyotomes.name]: false,
      [myotomes.name]: "",
      [isDtrs.name]: false,
      [dtrs.name]: "",
      [isPathological.name]: false,
      [pathological.name]: "",
      [isHomans.name]: false,
      [homans.name]: "",

      // [flexion60_exam.name] : "",
      // [flexion60_pain.name] : false,
      // [flexion60_noPain.name] : false,
      // [flexion60_location.name] : "",
      // [flexion60_left.name] : "",
      // [flexion60_right.name] : "",

      // [extension50_exam.name] : "",
      // [extension50_pain.name] : false,
      // [extension50_noPain.name] : false,
      // [extension50_location.name] : "",
      // [extension50_left.name] : "",
      // [extension50_right.name] : "",

      // [leftLateralFlexion40_pain.name] : false,
      // [leftLateralFlexion40_noPain.name] : false,

      // [rightLateralFlexion40_pain.name] : false,
      // [rightLateralFlexion40_noPain.name] : false,

      // [leftRotation80_pain.name] : false,
      // [leftRotation80_noPain.name] : false,

      // [rightRotation80_pain.name] : false,
      // [rightRotation80_noPain.name] : false,

      // [cervicalRegionalNotes1.name] : "",
      // [cervicalRegionalNotes2.name] : "",

      // [flexion90_pain.name] : false,
      // [flexion90_noPain.name] : false,
      // [extension30_pain.name] : false,
      // [extension30_noPain.name] : false,
      // [leftLateralFlexion20_pain.name] : false,
      // [leftLateralFlexion20_noPain.name] : false,
      // [rightLateralFlexion20_pain.name] : false,
      // [rightLateralFlexion20_noPain.name] : false,
      // [leftRotation30_pain.name] : false,
      // [leftRotation30_noPain.name] : false,
      // [rightRotation30_pain.name] : false,
      // [rightRotation30_noPain.name] : false,

      [lumbarRegionalNotes1.name]: "",
      [MaximalForaminalCompression_left.name]: "",
      [MaximalForaminalCompression_right.name]: "",
      [ODonoghuesManeuver.name]: "",

      // [flexion90_left.name] : "",
      // [flexion90_right.name] : "",
      // [extension30_left.name] : "",
      // [extension30_right.name] : "",
      // [leftLateralFlexion20_left.name] : "",
      // [leftLateralFlexion20_right.name] : "",
      // [rightLateralFlexion20_left.name] : "",
      // [rightLateralFlexion20_right.name] : "",
      // [leftRotation30_left.name] : "",
      // [leftRotation30_right.name] : "",
      // [rightRotation30_left.name] : "",
      // [rightRotation30_right.name] : "",

      [Yeomans_left.name]: "",
      [Yeomans_right.name]: "",

      // [isLtC0.name]: false,
      // [isLtC1.name]: false,
      // [isLtC2.name]: false,
      // [isLtC3.name]: false,
      // [isLtC4.name]: false,
      // [isLtC5.name]: false,
      // [isLtC6.name]: false,
      // [isLtC7.name]: false,

      // [isRtC0.name]: false,
      // [isRtC1.name]: false,
      // [isRtC2.name]: false,
      // [isRtC3.name]: false,
      // [isRtC4.name]: false,
      // [isRtC5.name]: false,
      // [isRtC6.name]: false,
      // [isRtC7.name]: false,

      // [isLtT1.name]: false,
      // [isLtT2.name]: false,
      // [isLtT3.name]: false,
      // [isLtT4.name]: false,
      // [isLtT5.name]: false,
      // [isLtT6.name]: false,
      // [isLtT7.name]: false,
      // [isLtT8.name]: false,
      // [isLtT9.name]: false,
      // [isLtT10.name]: false,
      // [isLtT11.name]: false,
      // [isLtT12.name]: false,

      // [isRtT1.name]: false,
      // [isRtT2.name]: false,
      // [isRtT3.name]: false,
      // [isRtT4.name]: false,
      // [isRtT5.name]: false,
      // [isRtT6.name]: false,
      // [isRtT7.name]: false,
      // [isRtT8.name]: false,
      // [isRtT9.name]: false,
      // [isRtT10.name]: false,
      // [isRtT11.name]: false,
      // [isRtT12.name]: false,

      // [isLtL1.name]: false,
      // [isLtL2.name]: false,
      // [isLtL3.name]: false,
      // [isLtL4.name]: false,
      // [isLtL5.name]: false,

      // [isRtL1.name]: false,
      // [isRtL2.name]: false,
      // [isRtL3.name]: false,
      // [isRtL4.name]: false,
      // [isRtL5.name]: false,

      // [isLtSij.name]: false,
      // [isRtSij.name]: false,

      [isOther.name]: false,

      CervicalRegional_Array: [
        { RangeofMotion: "Flexion (60°)", OrthopedicTests: "Flexion compression" },
        { RangeofMotion: "Extension (50°)", OrthopedicTests: "Extension compression" },
        {
          RangeofMotion: "Left Lateral Flexion (40°)",
          OrthopedicTests: "Right rotation compression",
        },
        {
          RangeofMotion: "Right Lateral Flexion (40°)",
          OrthopedicTests: "Left rotation compression",
        },
        { RangeofMotion: "Left Rotation (80°)", OrthopedicTests: "Cervical Distraction" },
        { RangeofMotion: "Right Rotation (80°)", OrthopedicTests: "Jackson’s Compression" },
      ],

      lumbarRegional_Array: [
        { RangeofMotion: "Flexion (90°)", OrthopedicTests: "SLR" },
        { RangeofMotion: "Extension (30°)", OrthopedicTests: "Kemp's" },
        { RangeofMotion: "Left Lateral Flexion (20°)", OrthopedicTests: "FABERE" },
        { RangeofMotion: "Right Lateral Flexion (20°)", OrthopedicTests: "Ely's" },
        { RangeofMotion: "Left Rotation (30°)", OrthopedicTests: "Nachla's" },
        { RangeofMotion: "Right Rotation (30°)", OrthopedicTests: "Hibb's" },
      ],
      // cArray: [
      //   { isLtC0: false, isRtC0: false },
      //   { isLtC1: false, isRtC1: false },
      //   { isLtC2: false, isRtC2: false },
      //   { isLtC3: false, isRtC3: false },
      //   { isLtC4: false, isRtC4: false },
      //   { isLtC5: false, isRtC5: false },
      //   { isLtC6: false, isRtC6: false },
      // ],
      // tArray: [],
      // lArray: [],

      isdArray: [
        { lt: false, name: "C0", rt: false },
        { lt: false, name: "C1", rt: false },
        { lt: false, name: "C2", rt: false },
        { lt: false, name: "C3", rt: false },
        { lt: false, name: "C4", rt: false },
        { lt: false, name: "C5", rt: false },
        { lt: false, name: "C6", rt: false },
        { lt: false, name: "C7", rt: false },

        { lt: false, name: "T1", rt: false },
        { lt: false, name: "T2", rt: false },
        { lt: false, name: "T3", rt: false },
        { lt: false, name: "T4", rt: false },
        { lt: false, name: "T5", rt: false },
        { lt: false, name: "T6", rt: false },
        { lt: false, name: "T7", rt: false },
        { lt: false, name: "T8", rt: false },
        { lt: false, name: "T9", rt: false },
        { lt: false, name: "T10", rt: false },
        { lt: false, name: "T11", rt: false },
        { lt: false, name: "T12", rt: false },

        { lt: false, name: "L1", rt: false },
        { lt: false, name: "L2", rt: false },
        { lt: false, name: "L3", rt: false },
        { lt: false, name: "L4", rt: false },
        { lt: false, name: "L5", rt: false },

        { lt: false, name: "SIJ", rt: false },
      ],
      textAreaPage15: "",
    },
  ],
};

export default initialValues;
