import moment from "moment";
const initialValues = {
  page6: [
    {
      physicalexam: "",
      obgynexam: "",
      wellnessexam: "",
      eyeexam: "",
      dentalexam: "",
      agemenstruation: "",
      cycleduration: "",
      cyclefrequency: "",
      abnormaltexture: "",
      paindiscomfort: "",
      datemenopause: "",
      lastpap: "",
      birthcontrol: "",
      hormonetherapy: "",
      acupuncturepast: false,
      acupuncturecurrent: false,
      chiropracticpast: false,
      chiropracticcurrent: false,
      massagepast: false,
      massagecurrent: false,
      medicalpast: false,
      medicalcurrent: false,
      naturopathicpast: false,
      naturopathiccurrent: false,
      nutritionistpast: false,
      nutritionistcurrent: false,
      otherspecialistpast: false,
      otherspecialistcurrent: false,
      Describe: "",
      bloodtest: "",
      breast: "",
      colonoscopy: "",
      ctscan: "",
      dexa: "",
      endoscope: "",
      mri: "",
      prostate: "",
      ultrasound: "",
      xray: "",
      other: "",
      bloodtestText: "",
      breastText: "",
      colonoscopyText: "",
      ctscanText: "",
      dexaText: "",
      endoscopeText: "",
      mriText: "",
      prostateText: "",
      ultrasoundText: "",
      xrayText: "",
      otherText: "",
      clientName: "",
      formCreatedDate: moment().format("DD-MM-YYYY"),
    },
  ],
};

export default initialValues;
