const initialValues = {

    // Namepatient : "",
    // page3date : "",
    // pg3dateofInjury : "",

    patient2 : "",
    date2 : "",
    dateofInjury2 : "",

    signatureDoctor : "",
    
    //neck values
    neckcheck1: false,
    neckcheck2: false,
    neckcheck3: false,
    neckcheck4: false,
    neckcheck5: false,
    neckcheck6: false,
    neckcheck7: false,
    neckcheck8: false,
    neckcheck9: false,
    neckcheck10: false,
    neckcheck11: false,
    neckcheck12: false,
    neckcheck13: false,
    neckcheck14: false,
    neckcheck15: false,
    neckcheck16: false,
    neckcheck17: false,
    neckcheck18: false,
    neckcheck19: false,
    neckcheck20: false,
    neckcheck21: false,
    neckcheck22: false,
    neckcheck23: false,
    neckcheck24: false,
    neckcheck25: false,
    neckcheck26: false,
    neckcheck27: false,
    neckcheck28: false,


    //Upper Back & Torso 
    torsocheck1 : false,
    torsoecheck2 : false,
    torsoecheck3 : false,
    torsoecheck4 : false,
    torsoecheck5 : false,
    torsoecheck6 : false,
    torsoecheck7 : false,
    torsoecheck8 : false,
    torsoecheck9 : false,
    torsoecheck10 : false,
    torsoecheck11 : false,
    torsoecheck12 : false,
    torsoecheck13 : false,
    torsoecheck14 : false,
    torsoecheck15 : false,
    torsoecheck16 : false,
    torsoecheck17 : false,
    torsoecheck18 : false,
    torsoecheck19 : false,
    torsoecheck20 : false,
    torsoecheck21 : false,
    torsoecheck22 : false,
    torsoecheck23 : false,
    torsoecheck24 : false,

    //Lumbar, Lumbosacral, SI & Pelvis 
    lumbercheck1 :  false,
    lumbercheck2 :  false,
    lumbercheck3 :  false,
    lumbercheck4 :  false,
    lumbercheck5 :  false,
    lumbercheck6 :  false,
    lumbercheck7 :  false,
    lumbercheck8 :  false,
    lumbercheck9 :  false,
    lumbercheck10 :  false,
    lumbercheck11 :  false,
    lumbercheck12 :  false,
    lumbercheck13 :  false,
    lumbercheck14 :  false,
    lumbercheck15 :  false,
    lumbercheck16 :  false,
    lumbercheck17 :  false,
    lumbercheck18 :  false,
    lumbercheck19 :  false,
    lumbercheck20 :  false,
    lumbercheck21 :  false,
    lumbercheck22 :  false,
    lumbercheck23 :  false,
    lumbercheck24 :  false,


    //Brain & Miscellaneous
    braincheck1 : false,
    braincheck2 : false,
    braincheck3 : false,
    braincheck4 : false,
    braincheck5 : false,
    braincheck6 : false,
    braincheck7 : false,
    braincheck8 : false,
    braincheck9 : false,
    braincheck10 : false,
    braincheck11 : false,
    braincheck12 : false,
    braincheck13 : false,
    braincheck14 : false,
    braincheck15 : false,
    braincheck16 : false,
    braincheck17 : false,
    braincheck18 : false,
    braincheck19 : false,

    //upper lower extermity
    //Chiropractic Segm. Dysfunctions
    Upper_Extremity : false,
    Ac_joint : false,
    lower_extermity: false,
    Hip_M99 : false,

    //Sprains
    Right_Shoulder : false,
    Left_Shoulder : false,
    Right_Elbow : false,
    Left_Elbow : false,
    Right_Wrist : false,
    Left_Wrist : false,
    Right_Hip : false,
    Left_Hip : false,
    Right_Knee :false,
    Left_Knee : false,
    Right_Ankle : false,
    Left_Ankle : false,
    Right_Foot : false,
    Left_Foot : false,
    Right_Great_Toe : false,
    Left_Great_Toe : false,

    //Finger Joint Sprains

    Right_Thumb : false,
    Left_Thumb : false,
    Right_Index : false,
    Left_Index : false,
    Right_Middle : false,
    Left_Middle : false,
    Right_Ring : false,
    Left_Ring : false,
    Right_Little: false,
    Left_Little : false,


    //strain of muscle fascia and tendency
    straincheck1: false,
    straincheck2: false,
    straincheck3: false,
    straincheck4: false,
    straincheck5: false,
    straincheck6: false,


    btmemptycheck1 : false,
    btmemptyinpt1 : "",

    btmemptycheck2 : false,
    btmemptyinpt2 : "",

    btmemptycheck3 : false,
    btmemptyinpt3 : "",

    btmemptycheck4 : false,
    btmemptyinpt4 : "",

    btmemptycheck5 : false,
    btmemptyinpt5 : "",

    btmemptycheck6 : false,
    btmemptyinpt6 : "",

    btmemptycheck7 : false,
    btmemptyinpt7 : "",

    btmemptycheck8 : false,
    btmemptyinpt8 : "",

    btmemptycheck9 : false,
    btmemptyinpt9 : "",

    btmemptycheck10 : false,
    btmemptyinpt10 : "",
}