const initialValues = {
    //orthopedic muscular symptoms cehckboxes values
    // sounds_with_neck_movements : false,
    // Neck_pain : false,
    // Upper_back_pain : false,
    // Low_back_pain : false,
    // Shoulder_pain : false,
    // Shoulder_pain_Left : false,
    // Shoulder_pain_Right : false,
    // Low_back_pain : false,
    // Shoulder_pain : false,

    patient2 : "",
    date2 : "",
    dateofInjury2 : "",

    doctorSignature :"",
    patientSignature : "",

    orthocheck1: false,
    orthocheck2: false,
    orthocheck3: false,
    orthocheck4: false,
    orthocheck5: false,  orthoLeftcheck5: false, orthoRightcheck5: false,
    orthocheck6: false,  orthoLeftcheck6: false, orthoRightcheck6: false,
    orthocheck7: false,  orthoLeftcheck7: false, orthoRightcheck7: false,
    orthocheck8: false,  orthoLeftcheck8: false, orthoRightcheck8: false,
    orthocheck9: false,  orthoLeftcheck9: false, orthoRightcheck9: false,
    orthocheck10: false, orthoLeftcheck10: false, orthoRightcheck10: false,
    orthocheck11: false, orthoLeftcheck11: false, orthoRightcheck11: false,
    orthocheck12: false, orthoLeftcheck12: false, orthoRightcheck12: false,
    orthocheck13: false, orthoLeftcheck13: false, orthoRightcheck13: false,
    orthocheck14: false, orthoLeftcheck14: false, orthoRightcheck14: false,
    orthocheck15: false, orthoLeftcheck15: false, orthoRightcheck15: false,
    orthocheck16: false, orthoLeftcheck16: false, orthoRightcheck16: false,
    orthocheck17: false,
    orthocheck18: false,
    orthocheck19: false,
    orthocheck20: false,
    orthocheck21: false,
    orthocheck22: false,
    orthocheck23: false,
    orthoInput23: "",
    orthocheck24: false,
    orthoInput24: "",
    orthocheck25: false,
    orthoInput25:"",
    orthocheck26: false,
    orthoInput26: "",



    //second checkboxes values
    brain_neuro_check1 : false,
    brain_neuro_check2: false,
    brain_neuro_check3 : false,
    brain_neuro_check4: false,
    brain_neuro_check5: false,
    brain_neuro_check6: false,
    brain_neuro_check7 : false,
    brain_neuro_check8 : false,
    brain_neuro_check9 : false,
    brain_neuro_check10 : false,
    brain_neuro_check11 : false,
    brain_neuro_check12: false,
    brain_neuro_check13 : false,
    brain_neuro_check14 : false,
    brain_neuro_check15 : false,
    brain_neuro_check16 : false,
    brain_neuro_check17 : false,
    brain_neuro_check18 : false,
    brain_neuro_check19 : false,
    brain_neuro_check20 : false,
    brain_neuro_check21 : false,
    brain_neuro_check22 : false,
    brain_neuro_check23 : false,
    brain_neuro_check24 : false,
    brain_neuro_check25 : false,
    brain_neuro_check26 : false,
    brain_neuro_check27 : false,
    brain_neuro_check28 : false,
    brain_neuro_check29 : false,
    brain_neuro_check30 : false,
    brain_neuro_check31 : false,
    brain_neuro_check32 : false,
    brain_neuro_check33 : false,
    brain_neuro_check34 : false,
    brain_neuro_check35 : false,
    brain_neuro_check36 : false,
    brain_neuro_check37 : false,
    brain_neuro_check38 : false,
    brain_neuro_check39 : false,
    brain_neuro_check40 : false,
    brain_neuro_check41 : false,
    brain_neuro_check42 : false,
    brain_neuro_check43 : false,
    brain_neuro_check44 : false,
    brain_neuro_check45 : false,
    brain_neuro_check46 : false,

    //neurological checkbox

    neurocheck1 : false,
    neuroleftcheck1 : false,
    neurorightcheck1 : false,

    neurocheck2 : false,
    neuroleftcheck2 : false,
    neurorightcheck2 : false,

    neurocheck3 : false,
    neuroleftcheck3 : false,
    neurorightcheck3 : false,

    neurocheck4 : false,
    neuroleftcheck4 : false,
    neurorightcheck4 : false,

    //symptoms associated with injuries
     injurycheck1 : false,
     injurycheck2 : false,
     injurycheck3 : false,
     injurycheck4 : false,
     injurycheck5 : false,
     injurycheck6 : false,
     injurycheck7 : false,
     injurycheck8 : false,
     injurycheck9 : false,
     injurycheck10 : false,
     injurycheck11 : false,
     injuryInput11 : "",

}
