const form = {
    formField:{
        followuptDate: {
            type:'date',
            name:'followuptDate',
        
          },
          doctorInitial: {
            type:'text',
            name:'doctorInitial',
        
          },
    
        description1Check:{
            type:'checkbox',
            name:"description1Check"
        },
        description1Input:{
            type:'text',
            name:"description1Input"
        },
        description1codeInput:{
            type:'text',
            name:"description1codeInput"
        },
        description1ServerityDrop:{
            type:'text',
            name:"description1ServerityDrop"
        },

      description2Check:{
            type:'checkbox',
            name:"description2Check"
        },
        description2Input:{
            type:'text',
            name:"description2Input"
        },
        description2codeInput:{
            type:'text',
            name:"description2codeInput"
        },
        description2ServerityDrop:{
            type:'text',
            name:"description2ServerityDrop"
        },

        description3Check:{
            type:'checkbox',
            name:"description3Check"
        },
        description3Input:{
            type:'text',
            name:"description3Input"
        },
        description3codeInput:{
            type:'text',
            name:"description3codeInput"
        },
        description3ServerityDrop:{
            type:'text',
            name:"description3ServerityDrop"
        },

        description4Check:{
            type:'checkbox',
            name:"description4Check"
        },
        description4Input:{
            type:'text',
            name:"description4Input"
        },
        description4codeInput:{
            type:'text',
            name:"description4codeInput"
        },
        description4ServerityDrop:{
            type:'text',
            name:"description4ServerityDrop"
        },

        description5Check:{
            type:'checkbox',
            name:"description5Check"
        },
        description5Input:{
            type:'text',
            name:"description5Input"
        },
        description5codeInput:{
            type:'text',
            name:"description5codeInput"
        },
        description5ServerityDrop:{
            type:'text',
            name:"description5ServerityDrop"
        },

        description6Check:{
            type:'checkbox',
            name:"description6Check"
        },
        description6Input:{
            type:'text',
            name:"description6Input"
        },
        description6codeInput:{
            type:'text',
            name:"description6codeInput"
        },
        description6ServerityDrop:{
            type:'text',
            name:"description6ServerityDrop"
        },

        description7Check:{
            type:'checkbox',
            name:"description7Check"
        },
        description7Input:{
            type:'text',
            name:"description7Input"
        },
        description7codeInput:{
            type:'text',
            name:"description7codeInput"
        },
        description7ServerityDrop:{
            type:'text',
            name:"description7ServerityDrop"
        },

        description8Check:{
            type:'checkbox',
            name:"description8Check"
        },
        description8Input:{
            type:'text',
            name:"description8Input"
        },
        description8codeInput:{
            type:'text',
            name:"description8codeInput"
        },
        description8ServerityDrop:{
            type:'text',
            name:"description8ServerityDrop"
        },

        description9Check:{
            type:'checkbox',
            name:"description9Check"
        },
        description9Input:{
            type:'text',
            name:"description9Input"
        },
        description9codeInput:{
            type:'text',
            name:"description9codeInput"
        },
        description9ServerityDrop:{
            type:'text',
            name:"description9ServerityDrop"
        },

        description10Check:{
            type:'checkbox',
            name:"description10Check"
        },
        description10Input:{
            type:'text',
            name:"description10Input"
        },
        description10codeInput:{
            type:'text',
            name:"description10codeInput"
        },
        description10ServerityDrop:{
            type:'text',
            name:"description10ServerityDrop"
        },

        table1Check:{
            type:'checkbox',
            name:"table1Check"
          },
          table2Check:{
            type:'checkbox',
            name:"table2Check"
          },
          table3Check:{
            type:'checkbox',
            name:"table3Check"
          },
          table1Check:{
            type:'checkbox',
            name:"table1Check"
          },
          table1Check:{
            type:'checkbox',
            name:"table1Check"
          },
          table4Check:{
            type:'checkbox',
            name:"table4Check"
          },
          table5Check:{
            type:'checkbox',
            name:"table5Check"
          },
          table6Check:{
            type:'checkbox',
            name:"table6Check"
          },
          table7Check:{
            type:'checkbox',
            name:"table7Check"
          },
          table8Check:{
            type:'checkbox',
            name:"table8Check"
          },

          table8Check:{
            type:'checkbox',
            name:"table8Check"
          },

          TherapeuticCheck:{
            type:'checkbox',
            name:"TherapeuticCheck"
          },
          FitnessCheck:{
            type:'checkbox',
            name:"FitnessCheck"
          },
          NutritionCheck:{
            type:'checkbox',
            name:"NutritionCheck"
          },
          MindfulnessCheck:{
            type:'checkbox',
            name:"MindfulnessCheck"
          },
          row1OtherInput:{
            type:'text',
            name:"row1OtherInput"
          },
          MyofascialCheck:{
            type:'checkbox',
            name:"MyofascialCheck"
          },
          StretchingCheck:{
            type:'checkbox',
            name:"StretchingCheck"
          },
          row2CSCheck:{
            type:'checkbox',
            name:"row2CSCheck"
          },
          row2TSCheck:{
            type:'checkbox',
            name:"row2TSCheck"
          },
          row2LSCheck:{
            type:'checkbox',
            name:"row2LSCheck"
          },
          row2OtherCheck:{
            type:'checkbox',
            name:"row2OtherCheck"
          },
          row2OtherInput1:{
            type:'text',
            name:"row2OtherInput1"
          },
          row2OtherInput2:{
            type:'text',
            name:"row2OtherInput2"
          },
          DiversifiedCheck:{
            type:'checkbox',
            name:"DiversifiedCheck"
          },
          ActivatorCheck:{
            type:'checkbox',
            name:"ActivatorCheck"
          },
          NetworkCheck:{
            type:'checkbox',
            name:"NetworkCheck"
          },
          row3OtherCheck:{
            type:'checkbox',
            name:"row3OtherCheck"
          },
          row3OtherInput:{
            type:'text',
            name:"row3OtherInput"
          },
          row3Other1Check:{
            type:'checkbox',
            name:"row3Other1Check"
          },
          row3CSCheck:{
            type:'checkbox',
            name:"row3CSCheck"
          },
          row3TSCheck:{
            type:'checkbox',
            name:"row3TSCheck"
          },
          row3LSCheck:{
            type:'checkbox',
            name:"row3LSCheck"
          },
          row3OtherInput1:{
            type:'text',
            name:"row3OtherInput1"
          },
          row3OtherInput2:{
            type:'text',
            name:"row3OtherInput2"
          },
          BlockingCheck:{
            type:'checkbox',
            name:"BlockingCheck"
          },
          IceCheck:{
            type:'checkbox',
            name:"IceCheck"
          },
          HeatCheck:{
            type:'checkbox',
            name:"HeatCheck"
          },
          row4OtherCheck:{
            type:'checkbox',
            name:"row4OtherCheck"
          },
          row4OtherInput:{
            type:'text',
            name:"row4OtherInput"
          },
          row4CSCheck:{
            type:'checkbox',
            name:"row4CSCheck"
          },
          row4LSCheck:{
            type:'checkbox',
            name:"row4LSCheck"
          },
          row4TSCheck:{
            type:'checkbox',
            name:"row4TSCheck"
          },
          row4Other1Check:{
            type:'checkbox',
            name:"row4Other1Check"
          },
          row4OtherInput1:{
            type:'text',
            name:"row4OtherInput1"
          },
          row4OtherInput2:{
            type:'text',
            name:"row4OtherInput2"
          },
          newPatient99201Input1:{
            type:"text",
            name: "newPatient99201Input1"
          },
          newPatient99202Input:{
            type:"text",
            name: "newPatient99202Input"
          },
          newPatient99203Input:{
            type:"text",
            name: "newPatient99203Input"
          },
          newPatient99204Input:{
            type:"text",
            name: "newPatient99204Input"
          },
          newPatient99205Input:{
            type:"text",
            name: "newPatient99205Input"
          },
          ExtPatientInput:{
            type:"text",
            name: "ExtPatientInput"
          },
          EstablishedPati99211Inp:{
            type:"text",
            name: "EstablishedPati99211Inp"
          },
          EstablishedPati99212Inp:{
            type:"text",
            name: "EstablishedPati99212Inp"
          },
          
          

    }
}

export default form;