import moment from "moment";
import checkout from "./form";

const {
  formField: {
    followuptDate,
    doctorInitial,

    description1Check,
    description1Input,
    description1codeInput,
    description1ServerityDrop,
    description2Input,
    description2Check,
    description2codeInput,
    description2ServerityDrop,

    description3Input,
    description3Check,
    description3codeInput,
    description3ServerityDrop,

    description4Input,
    description4Check,
    description4codeInput,
    description4ServerityDrop,

    description5Input,
    description5Check,
    description5codeInput,
    description5ServerityDrop,

    description6Input,
    description6Check,
    description6codeInput,
    description6ServerityDrop,

    description7Input,
    description7Check,
    description7codeInput,
    description7ServerityDrop,

    description8Input,
    description8Check,
    description8codeInput,
    description8ServerityDrop,

    description9Input,
    description9Check,
    description9codeInput,
    description9ServerityDrop,

    description10Input,
    description10Check,
    description10codeInput,
    description10ServerityDrop,

    table1Check,
    table2Check,
    table3Check,
    table4Check,
    table5Check,
    table6Check,
    table7Check,
    table8Check,

    TherapeuticCheck,
    FitnessCheck,
    NutritionCheck,
    MindfulnessCheck,
    row1OtherInput,
    MyofascialCheck,
    StretchingCheck,
    row2CSCheck,
    row2TSCheck,
    row2LSCheck,
    row2OtherCheck,
    row2OtherInput1,
    row2OtherInput2,
    DiversifiedCheck,
    ActivatorCheck,
    NetworkCheck,
    row3OtherCheck,
    row3OtherInput,
    row3Other1Check,
    row3CSCheck,
    row3TSCheck,
    row3LSCheck,
    row3OtherInput1,
    row3OtherInput2,
    BlockingCheck,
    IceCheck,
    HeatCheck,
    row4OtherCheck,
    row4OtherInput,
    row4CSCheck,
    row4LSCheck,
    row4TSCheck,
    row4Other1Check,
    row4OtherInput1,
    row4OtherInput2,
    newPatient99201Input1,
    newPatient99202Input,
    newPatient99203Input,
    newPatient99204Input,
    newPatient99205Input,
    ExtPatientInput,
    EstablishedPati99211Inp,
    EstablishedPati99212Inp,
  },
} = checkout;

const initialValues = {
  eightPage: [
    {
      [followuptDate.name]: "",
      [doctorInitial.name]: "",
      formCreatedDate: moment().format("DD-MM-YYYY"),
      // [description1Check.name]: false,
      // [description1Input.name]: "",
      // [description1codeInput.name]: "",
      // [description1ServerityDrop.name]: "",

      // [description2Check.name]: false,
      // [description2Input.name]: "",
      // [description2codeInput.name]: "",
      // [description2ServerityDrop.name]: "",

      // [description3Check.name]: false,
      // [description3Input.name]: "",
      // [description3codeInput.name]: "",
      // [description3ServerityDrop.name]: "",

      // [description4Check.name]: false,
      // [description4Input.name]: "",
      // [description4codeInput.name]: "",
      // [description4ServerityDrop.name]: "",

      // [description5Check.name]: false,
      // [description5Input.name]: "",
      // [description5codeInput.name]: "",
      // [description5ServerityDrop.name]: "",

      // [description6Check.name]: false,
      // [description6Input.name]: "",
      // [description6codeInput.name]: "",
      // [description6ServerityDrop.name]: "",

      // [description7Check.name]: false,
      // [description7Input.name]: "",
      // [description7codeInput.name]: "",
      // [description7ServerityDrop.name]: "",

      // [description8Check.name]: false,
      // [description8Input.name]: "",
      // [description8codeInput.name]: "",
      // [description8ServerityDrop.name]: "",

      // [description9Check.name]: false,
      // [description9Input.name]: "",
      // [description9codeInput.name]: "",
      // [description9ServerityDrop.name]: "",

      // [description10Check.name]: false,
      // [description10Input.name]: "",
      // [description10codeInput.name]: "",
      // [description10ServerityDrop.name]: "",

      [TherapeuticCheck.name]: false,
      [FitnessCheck.name]: false,
      [NutritionCheck.name]: false,
      [MindfulnessCheck.name]: false,
      [row1OtherInput.name]: "",
      [MyofascialCheck.name]: false,
      [StretchingCheck.name]: false,
      [row2CSCheck.name]: false,
      [row2TSCheck.name]: false,
      [row2LSCheck.name]: false,
      [row2OtherCheck.name]: false,
      [row2OtherInput1.name]: "",
      [row2OtherInput2.name]: "",
      [DiversifiedCheck.name]: false,
      [ActivatorCheck.name]: false,
      [NetworkCheck.name]: false,
      [row3OtherCheck.name]: false,
      [row3OtherInput.name]: "",
      [row3Other1Check.name]: false,
      [row3CSCheck.name]: false,
      [row3TSCheck.name]: false,
      [row3LSCheck.name]: false,
      [row3OtherInput1.name]: "",
      [row3OtherInput2.name]: "",
      [BlockingCheck.name]: false,
      [IceCheck.name]: false,
      [HeatCheck.name]: false,
      [row4OtherCheck.name]: false,
      [row4OtherInput.name]: "",
      [row4CSCheck.name]: false,
      [row4LSCheck.name]: false,
      [row4TSCheck.name]: false,
      [row4Other1Check.name]: false,
      [row4OtherInput1.name]: "",
      [row4OtherInput2.name]: "",

      [table1Check.name]: false,
      [table2Check.name]: false,
      [table3Check.name]: false,
      [table4Check.name]: false,
      [table5Check.name]: false,
      [table6Check.name]: false,
      [table7Check.name]: false,
      [table8Check.name]: false,
      [newPatient99201Input1.name]: "",
      [newPatient99202Input.name]: "",
      [newPatient99203Input.name]: "",
      [newPatient99204Input.name]: "",
      [newPatient99205Input.name]: "",
      [ExtPatientInput.name]: "",
      [EstablishedPati99211Inp.name]: "",
      [EstablishedPati99212Inp.name]: "",
      patientDetailsForm: {
        PractitionerName: "",
        NPI: "",
        TIN: "",
        hourlyRate: "",
        patientName:"",
        name: "",
        isNewPatient: false,
        isFollowUpPatient: false,
        isNewComplaintPatient: false,
        patientVisitNumber: "",
        patientTodaysDate: "",
        patientNextReExam: "",
        patientDob: "",
        patientAge: "",
        patientHeight: "",
        patientHeightNI: false,
        patientWeight: "",
        patientWeightNI: false,
        patientHtnYes: false,
        patientHtnNo: false,
        patientCautions: "",
      },
    },
  ],
};

export default initialValues;
