import form from "./form";
const initialValues = {
  humanSidebodyPointsEars: "",
  humanSidebodyPointsShoulder: "",
  humanSidebodyPointsArm: "",
  humanSidebodyPointsForearm: "",
  humanSidebodyPointsWrist: "",
  humanSidebodyPointsKnee: "",
  humanSidebodyPointsAnkle: "",

  humanexcerciseone: "",
  humanCheckone: "",

  humanexcerciseone1: "",
  humanexcerciseone2: "",
  humanexcerciseone3: "",
  humanexcerciseonesub3: "",
  humanexcerciseone4: "",
  humanexcerciseone5: "",
  humanexcerciseone6: "",
  humanexcerciseone7: "",
  humanexcerciseone8: "",
  humanexcerciseone9: "",
  humanexcerciseone10: "",
  humanexcerciseone11: "",
  humanexcerciseone12: "",
  humanexcerciseone13: "",
  humanexcerciseone14: "",
  humanexcerciseonesub14: "",
  humanexcerciseone15: "",

  leftshoulderdesc: "",
  rightshoulderdesc: "",
  leftthoricdesc: "",
  rightthoricdesc: "",
  leftpelvisdesc: "",
  rightpelvisdesc: "",
  lefthipdesc: "",
  righthipdesc: "",
  leftkneedesc: "",
  rightkneedesc: "",
  leftankledesc: "",
  rightankledesc: "",
  leftheaddesc: "",
  rightheaddesc: "",

  humanFullbodyPointsrightshoulder: "",
  check: "",
  humanFullbodyPointsadamsapple: "",
  humanFullbodyPointsleftshoulder: "",
  humanFullbodyPointschest: "",
  humanFullbodyPointsleftabdominal: "",
  humanFullbodyPointsabdominal: "",
  humanFullbodyPointsrightabdominal: "",
  humanFullbodyPointslefthip: "",
  humanFullbodyPointsrighthip: "",
  humanFullbodyPointsleftknee: "",
  humanFullbodyPointsrighttknee: "",
  humanFullbodyPointsleftankle: "",
  humanFullbodyPointsrighankle: "",

  humanexcerciseTwo: "",

  humanexcercisetwo1: "",
  humanexcercisetwosub1: "",
  humanexcercisetwo2: "",
  humanexcercisetwo3: "",
  humanexcercisetwo4: "",
  humanexcercisetwosub4: "",
  humanexcercisetwo5: "",
  humanexcercisetwo6: "",
  humanexcercisetwosub6: "",
  humanexcercisetwo7: "",
  humanexcercisetwo8: "",
  humanexcercisetwosub8: "",
  humanexcercisetwo9: "",
  humanexcercisetwo10: "",
  humanexcercisetwo11: "",
  humanexcercisetwosub11: "",
  humanexcercisetwo12: "",
  humanexcercisetwo13: "",
  humanexcercisetwosub13: "",
  humanexcercisetwo14: "",
  humanexcercisetwosub14: "",
  humanexcercisetwo15: "",
  humanexcercisetwo16: "",
  humanexcercisetwo17: "",

  ClientName: "",
  Chiefcomplaint: "",
  Painlevel: "",
  Practitioner: "",
  Date: "",
  physicianclearance: "",
  yes: "",
  no: "",

  excerciseDetails: [
    {
      humanSidebodyPointsEars: false,
      humanSidebodyPointsShoulder: false,
      humanSidebodyPointsArm: false,
      humanSidebodyPointsForearm: false,
      humanSidebodyPointsWrist: false,
      humanSidebodyPointsKnee: false,
      humanSidebodyPointsAnkle: false,

      humanexcerciseone: "",
      humanCheckone: "",

      humanexcerciseone1: false,
      humanexcerciseone2: false,
      humanexcerciseone3: false,
      humanexcerciseonesub3: false,
      humanexcerciseone4: false,
      humanexcerciseone5: false,
      humanexcerciseone6: false,
      humanexcerciseone7: false,
      humanexcerciseone8: false,
      humanexcerciseone9: false,
      humanexcerciseone10: false,
      humanexcerciseone11: false,
      humanexcerciseone12: false,
      humanexcerciseone13: false,
      humanexcerciseone14: false,
      humanexcerciseonesub14: false,
      humanexcerciseone15: false,

      leftshoulderdesc: "",
      rightshoulderdesc: "",
      leftthoricdesc: "",
      rightthoricdesc: "",
      leftpelvisdesc: "",
      rightpelvisdesc: "",
      lefthipdesc: "",
      righthipdesc: "",
      leftkneedesc: "",
      rightkneedesc: "",
      leftankledesc: "",
      rightankledesc: "",
      leftheaddesc: "",
      rightheaddesc: "",

      humanFullbodyPointsrightshoulder: false,
      check: false,
      humanFullbodyPointsadamsapple: false,
      humanFullbodyPointsleftshoulder: false,
      humanFullbodyPointschest: false,
      humanFullbodyPointsleftabdominal: false,
      humanFullbodyPointsabdominal: false,
      humanFullbodyPointsrightabdominal: false,
      humanFullbodyPointslefthip: false,
      humanFullbodyPointsrighthip: false,
      humanFullbodyPointsleftknee: false,
      humanFullbodyPointsrighttknee: false,
      humanFullbodyPointsleftankle: false,
      humanFullbodyPointsrighankle: false,

      humanexcerciseTwo: "",

      humanexcercisetwo1: "",
      humanexcercisetwosub1: "",
      humanexcercisetwo2: "",
      humanexcercisetwo3: "",
      humanexcercisetwo4: "",
      humanexcercisetwosub4: "",
      humanexcercisetwo5: "",
      humanexcercisetwo6: "",
      humanexcercisetwosub6: "",
      humanexcercisetwo7: "",
      humanexcercisetwo8: "",
      humanexcercisetwosub8: "",
      humanexcercisetwo9: "",
      humanexcercisetwo10: "",
      humanexcercisetwo11: "",
      humanexcercisetwosub11: "",
      humanexcercisetwo12: "",
      humanexcercisetwo13: "",
      humanexcercisetwosub13: "",
      humanexcercisetwo14: "",
      humanexcercisetwosub14: "",
      humanexcercisetwo15: "",
      humanexcercisetwo16: "",
      humanexcercisetwo17: "",

      ClientName: "",
      Chiefcomplaint: "",
      Painlevel: "",
      Practitioner: "",
      Date: "",
      physicianclearance: "",
      yes: "",
      no: "",
    },
  ],
};

export default initialValues;
