import moment from "moment";
const initialValues = {
  page7: [
    {
      AllergiesInput: "",
      AllergiesCheck: false,
      AllergiesMaternal: false,
      AllergiesPaternal: false,

      ArthritisInput: "",
      ArthritisCheck: false,
      ArthritisMaternal: false,
      ArthritisPaternal: false,

      AsthmaInput: "",
      AsthmaCheck: false,
      AsthmaMaternal: false,
      AsthmaPaternal: false,

      BloodDisordersInput: "",
      BloodDisordersCheck: false,
      BloodDisordersMaternal: false,
      BloodDisordersPaternal: false,

      CancerInput: "",
      CancerCheck: false,
      CancerMaternal: false,
      CancerPaternal: false,

      DepressionInput: "",
      DepressionCheck: false,
      DepressionMaternal: false,
      DepressionPaternal: false,

      DiabetesInput: "",
      DiabetesCheck: false,
      DiabetesMaternal: false,
      DiabetesPaternal: false,

      AttackInput: "",
      AttackCheck: false,
      AttackMaternal: false,
      AttackPaternal: false,

      LiverInput: "",
      LiverCheck: false,
      LiverMaternal: false,
      LiverPaternal: false,

      HBPInput: "",
      HBPCheck: false,
      HBPMaternal: false,
      HBPPaternal: false,

      KidneyDiseaseInput: "",
      KidneyDiseaseCheck: false,
      KidneyDiseaseMaternal: false,
      KidneyDiseasePaternal: false,

      LBPInput: "",
      LBPCheck: false,
      LBPMaternal: false,
      LBPPaternal: false,

      LungInput: "",
      LungCheck: false,
      LungMaternal: false,
      LungPaternal: false,

      NeuroInput: "",
      NeuroCheck: false,
      NeuroMaternal: false,
      NeuroPaternal: false,

      PsychologicalDisorderInput: "",
      PsychologicalDisorderCheck: false,
      PsychologicalDisorderMaternal: false,
      PsychologicalDisorderPaternal: false,

      RheumaticFeverInput: "",
      RheumaticFeverCheck: false,
      RheumaticFeverMaternal: false,
      RheumaticFeverPaternal: false,

      SeizuresInput: "",
      SeizuresCheck: false,
      SeizuresMaternal: false,
      SeizuresPaternal: false,

      SmallInput: "",
      SmallCheck: false,
      SmallMaternal: false,
      SmallPaternal: false,

      StomachInput: "",
      StomachCheck: false,
      StomachMaternal: false,
      StomachPaternal: false,

      StrokeInput: "",
      StrokeCheck: false,
      StrokeMaternal: false,
      StrokePaternal: false,

      ThyroidDiseaseInput: "",
      ThyroidDiseaseCheck: false,
      ThyroidDiseaseMaternal: false,
      ThyroidDiseasePaternal: false,

      VascularInput: "",
      VascularCheck: false,
      VascularMaternal: false,
      VascularPaternal: false,

      OtherInput: "",
      OtherCheck: false,
      OtherMaternal: false,
      OtherPaternal: false,

      meditations: "",
      dose: "",
      clientName: "",
      formCreatedDate: moment().format("DD-MM-YYYY"),
    },
  ],
};

export default initialValues;

// medicalhistory: [
//   {
//     diseaseName: "Allergies",
//     diseaseInput: "",
//     diseasecurrent: false,
//     diseasematernal: false,
//     diseasepaternal: false,
//   },
//   {
//     diseaseName: "Arthritis",
//     diseaseInput: "",
//     diseasecurrent: false,
//     diseasematernal: false,
//     diseasepaternal: false,
//   },
//   {
//     diseaseName: "Asthma",
//     diseaseInput: "",
//     diseasecurrent: false,
//     diseasematernal: false,
//     diseasepaternal: false,
//   },
//   {
//     diseaseName: "Blood Disorders",
//     diseaseInput: "",
//     diseasecurrent: false,
//     diseasematernal: false,
//     diseasepaternal: false,
//   },
//   {
//     diseaseName: "Cancer",
//     diseaseInput: "",
//     diseasecurrent: false,
//     diseasematernal: false,
//     diseasepaternal: false,
//   },
//   {
//     diseaseName: "Depression",
//     diseaseInput: "",
//     diseasecurrent: false,
//     diseasematernal: false,
//     diseasepaternal: false,
//   },
//   {
//     diseaseName: "Diabetes",
//     diseaseInput: "",
//     diseasecurrent: false,
//     diseasematernal: false,
//     diseasepaternal: false,
//   },
//   {
//     diseaseName: "Heart Disease / Attack",
//     diseaseInput: "",
//     diseasecurrent: false,
//     diseasematernal: false,
//     diseasepaternal: false,
//   },
//   {
//     diseaseName: "Liver / Gall bladder disease",
//     diseaseInput: "",
//     diseasecurrent: false,
//     diseasematernal: false,
//     diseasepaternal: false,
//   },
//   {
//     diseaseName: "High Blood Pressure",
//     diseaseInput: "",
//     diseasecurrent: false,
//     diseasematernal: false,
//     diseasepaternal: false,
//   },
//   {
//     diseaseName: "Kidney Disease/stones",
//     diseaseInput: "",
//     diseasecurrent: false,
//     diseasematernal: false,
//     diseasepaternal: false,
//   },
//   {
//     diseaseName: "Low Blood Pressure",
//     diseaseInput: "",
//     diseasecurrent: false,
//     diseasematernal: false,
//     diseasepaternal: false,
//   },
//   {
//     diseaseName: "Lung Disease",
//     diseaseInput: "",
//     diseasecurrent: false,
//     diseasematernal: false,
//     diseasepaternal: false,
//   },
//   {
//     diseaseName: "Neurological Disease",
//     diseaseInput: "",
//     diseasecurrent: false,
//     diseasematernal: false,
//     diseasepaternal: false,
//   },
//   {
//     diseaseName: "Psychological Disorder",
//     diseaseInput: "",
//     diseasecurrent: false,
//     diseasematernal: false,
//     diseasepaternal: false,
//   },
//   {
//     diseaseName: "Rheumatic Fever",
//     diseaseInput: "",
//     diseasecurrent: false,
//     diseasematernal: false,
//     diseasepaternal: false,
//   },
//   {
//     diseaseName: "Seizures",
//     diseaseInput: "",
//     diseasecurrent: false,
//     diseasematernal: false,
//     diseasepaternal: false,
//   },
//   {
//     diseaseName: "Small/Large Intestine",
//     diseaseInput: "",
//     diseasecurrent: false,
//     diseasematernal: false,
//     diseasepaternal: false,
//   },
//   {
//     diseaseName: "Stomach",
//     diseaseInput: "",
//     diseasecurrent: false,
//     diseasematernal: false,
//     diseasepaternal: false,
//   },
//   {
//     diseaseName: "Stroke",
//     diseaseInput: "",
//     diseasecurrent: false,
//     diseasematernal: false,
//     diseasepaternal: false,
//   },
//   {
//     diseaseName: "Thyroid Disease",
//     diseaseInput: "",
//     diseasecurrent: false,
//     diseasematernal: false,
//     diseasepaternal: false,
//   },
//   {
//     diseaseName: "Vascular Disease",
//     diseaseInput: "",
//     diseasecurrent: false,
//     diseasematernal: false,
//     diseasepaternal: false,
//   },
//   {
//     diseaseName: "Other",
//     diseaseInput: "",
//     diseasecurrent: false,
//     diseasematernal: false,
//     diseasepaternal: false,
//   },
// ],
