const form = {
    formField:{
        DATE:{
            type:'date',
            name:"DATE"
          },
          dateofinjury:{
            type:'date',
            name:"dateofinjury"
          },
          Patient:{
            type:'text',
            name:"Patient"
          },
          accidentWORK1Check:{
            type:'checkbox',
            name:"accidentWORK1Check"
          },
          accidentWORK2Check:{
            type:'checkbox',
            name:"accidentWORK2Check"
          },
          accidentWORK3Check:{
            type:'checkbox',
            name:"accidentWORK3Check"
          },
          accidentWORK1Check:{
            type:'checkbox',
            name:"accidentWORK1Check"
          },
          accidentWORK1Check:{
            type:'checkbox',
            name:"accidentWORK1Check"
          },
          accidentWORK4Check:{
            type:'checkbox',
            name:"accidentWORK4Check"
          },
          accidentWORK5Check:{
            type:'checkbox',
            name:"accidentWORK5Check"
          },
          accidentWORK6Check:{
            type:'checkbox',
            name:"accidentWORK6Check"
          },
          accidentWORK7Check:{
            type:'checkbox',
            name:"accidentWORK7Check"
          },
          accidentWORK8Check:{
            type:'checkbox',
            name:"accidentWORK8Check"
          },
          accidentWORK9Check:{
            type:'checkbox',
            name:"accidentWORK9Check"
          },
          accidentWORK10Check:{
            type:'checkbox',
            name:"accidentWORK10Check"
          }, 
          accidentWORK11Check:{
            type:'checkbox',
            name:"accidentWORK11Check"
          },
          accidentWORK1Check:{
            type:'checkbox',
            name:"accidentWORK1Check"
          },
          accidentWORK12Check:{
            type:'checkbox',
            name:"accidentWORK12Check"
          },
          accidentWORK13Check:{
            type:'checkbox',
            name:"accidentWORK13Check"
          },
          accidentWORK14Check:{
            type:'checkbox',
            name:"accidentWORK14Check"
          },
          accidentWORK15Check:{
            type:'checkbox',
            name:"accidentWORK15Check"
          },
          accidentWORK16Check:{
            type:'checkbox',
            name:"accidentWORK16Check"
          },
          accidentWORK17Check:{
            type:'checkbox',
            name:"accidentWORK17Check"
          },
          accidentWORK18Check:{
            type:'checkbox',
            name:"accidentWORK18Check"
          },
          accidentWORK19Check:{
            type:'checkbox',
            name:"accidentWORK19Check"
          },
          accidentWORK20Check:{
            type:'checkbox',
            name:"accidentWORK20Check"
          },

          accidentWORK21Check:{
            type:'checkbox',
            name:"accidentWORK11Check"
          },
          accidentWORK22Check:{
            type:'checkbox',
            name:"accidentWORK22Check"
          },
          accidentWORK23Check:{
            type:'checkbox',
            name:"accidentWORK23Check"
          },
          accidentWORK24Check:{
            type:'checkbox',
            name:"accidentWORK24Check"
          },
          accidentWORK25Check:{
            type:'checkbox',
            name:"accidentWORK25Check"
          },
          accidentWORK26Check:{
            type:'checkbox',
            name:"accidentWORK26Check"
          },
          accidentWORK27Check:{
            type:'checkbox',
            name:"accidentWORK27Check"
          },
          accidentWORK28Check:{
            type:'checkbox',
            name:"accidentWORK28Check"
          },
          accidentWORK29Check:{
            type:'checkbox',
            name:"accidentWORK29Check"
          },
          accidentWORK30Check:{
            type:'checkbox',
            name:"accidentWORK20Check"
          },

          accidentWORK31Check:{
            type:'checkbox',
            name:"accidentWORK31Check"
          },
          accidentWORK32Check:{
            type:'checkbox',
            name:"accidentWORK32Check"
          },
          accidentWORK33Check:{
            type:'checkbox',
            name:"accidentWORK33Check"
          },
          accidentWORK34Check:{
            type:'checkbox',
            name:"accidentWORK34Check"
          },
          accidentWORK35Check:{
            type:'checkbox',
            name:"accidentWORK35Check"
          },
          accidentWORK35Input1:{
            type:'text',
            name:"accidentWORK35Input1"
          },
          accidentWORK35Input2:{
            type:'text',
            name:"accidentWORK35Input2"
          },
          accidentWORK35Input4:{
            type:'text',
            name:"accidentWORK35Input4"
          },
          accidentWORK35Input3:{
            type:'text',
            name:"accidentWORK35Input3"
          },
          accidentWORK35Input5:{
            type:'text',
            name:"accidentWORK35Input5"
          },
          accidentWORK35Input6:{
            type:'text',
            name:"accidentWORK35Input6"
          },

          

          accidentHOMEduties1Check:{
            type:'checkbox',
            name:"accidentHOMEduties1Check"
          },
          accidentHOMEduties2Check:{
            type:'checkbox',
            name:"accidentHOMEduties2Check"
          },
          accidentHOMEduties3Check:{
            type:'checkbox',
            name:"accidentHOMEduties3Check"
          },
          accidentHOMEduties1Check:{
            type:'checkbox',
            name:"accidentHOMEduties1Check"
          },
          accidentHOMEduties1Check:{
            type:'checkbox',
            name:"accidentHOMEduties1Check"
          },
          accidentHOMEduties4Check:{
            type:'checkbox',
            name:"accidentHOMEduties4Check"
          },
          accidentHOMEduties5Check:{
            type:'checkbox',
            name:"accidentHOMEduties5Check"
          },
          accidentHOMEduties6Check:{
            type:'checkbox',
            name:"accidentHOMEduties6Check"
          },
          accidentHOMEduties7Check:{
            type:'checkbox',
            name:"accidentHOMEduties7Check"
          },
          accidentHOMEduties8Check:{
            type:'checkbox',
            name:"accidentHOMEduties8Check"
          },
          accidentHOMEduties9Check:{
            type:'checkbox',
            name:"accidentHOMEduties9Check"
          },
          accidentHOMEduties10Check:{
            type:'checkbox',
            name:"accidentHOMEduties10Check"
          }, 
          accidentHOMEduties11Check:{
            type:'checkbox',
            name:"accidentHOMEduties11Check"
          },
          accidentHOMEduties1Check:{
            type:'checkbox',
            name:"accidentHOMEduties1Check"
          },
          accidentHOMEduties12Check:{
            type:'checkbox',
            name:"accidentHOMEduties12Check"
          },
          accidentHOMEduties13Check:{
            type:'checkbox',
            name:"accidentHOMEduties13Check"
          },
          accidentHOMEduties14Check:{
            type:'checkbox',
            name:"accidentHOMEduties14Check"
          },
          accidentHOMEduties15Check:{
            type:'checkbox',
            name:"accidentHOMEduties15Check"
          },
          accidentHOMEduties16Check:{
            type:'checkbox',
            name:"accidentHOMEduties16Check"
          },
          accidentHOMEduties17Check:{
            type:'checkbox',
            name:"accidentHOMEduties17Check"
          },
          accidentHOMEduties18Check:{
            type:'checkbox',
            name:"accidentHOMEduties18Check"
          },
          accidentHOMEduties19Check:{
            type:'checkbox',
            name:"accidentHOMEduties19Check"
          },
          accidentHOMEduties20Check:{
            type:'checkbox',
            name:"accidentHOMEduties20Check"
          },

          accidentHOMEduties21Check:{
            type:'checkbox',
            name:"accidentHOMEduties11Check"
          },
          accidentHOMEduties22Check:{
            type:'checkbox',
            name:"accidentHOMEduties22Check"
          },
          accidentHOMEduties23Check:{
            type:'checkbox',
            name:"accidentHOMEduties23Check"
          },
          accidentHOMEduties24Check:{
            type:'checkbox',
            name:"accidentHOMEduties24Check"
          },
          accidentHOMEduties25Check:{
            type:'checkbox',
            name:"accidentHOMEduties25Check"
          },
          accidentHOMEduties26Check:{
            type:'checkbox',
            name:"accidentHOMEduties26Check"
          },
          accidentHOMEduties27Check:{
            type:'checkbox',
            name:"accidentHOMEduties27Check"
          },
          accidentHOMEduties28Check:{
            type:'checkbox',
            name:"accidentHOMEduties28Check"
          },
          accidentHOMEduties29Check:{
            type:'checkbox',
            name:"accidentHOMEduties29Check"
          },
          accidentHOMEduties30Check:{
            type:'checkbox',
            name:"accidentHOMEduties20Check"
          },

          accidentHOMEduties31Check:{
            type:'checkbox',
            name:"accidentHOMEduties31Check"
          },
          accidentHOMEduties32Check:{
            type:'checkbox',
            name:"accidentHOMEduties32Check"
          },
          accidentHOMEduties33Check:{
            type:'checkbox',
            name:"accidentHOMEduties33Check"
          },
          accidentHOMEduties34Check:{
            type:'checkbox',
            name:"accidentHOMEduties34Check"
          },
          accidentHOMEduties35Check:{
            type:'checkbox',
            name:"accidentHOMEduties35Check"
          },
          accidentHOMEduties35Input1:{
            type:'text',
            name:"accidentHOMEduties35Input1"
          },
          accidentHOMEduties36Check:{
            type:'checkbox',
            name:"accidentHOMEduties36Check"
          },
          accidentHOMEduties36Input:{
            type:'text',
            name:"accidentHOMEduties36Input"
          },
          accidentHOMEduties37Check:{
            type:'checkbox',
            name:"accidentHOMEduties37Check"
          },
          accidentHOMEduties37Input:{
            type:'text',
            name:"accidentHOMEduties37Input"
          },
          accidentHOMEduties38Check:{
            type:'checkbox',
            name:"accidentHOMEduties38Check"
          },
          accidentHOMEduties38Input:{
            type:'text',
            name:"accidentHOMEduties38Input"
          },
          doctorSign:{
            type:'text',
            name:"doctorSign"
          },
          doctorDate:{
            type:'date',
            name:"doctorDate"
          },
          accidentHOMEduties19Input1:{
            type:'text',
            name:"accidentHOMEduties19Input1"
          },
          accidentHOMEduties19Input2:{
            type:'text',
            name:"accidentHOMEduties19Input2"
          },
          initialCheck:{
            type:'checkbox',
            name:"initialCheck"
          },
          updateCheck:{
            type:'checkbox',
            name:"updateCheck"
          },
    }
}

export default form;