import moment from "moment";
import checkout from "./form";

const {
  formField: {
    DATE,
    dateofinjury,
    Patient,
    accidentWORK1Check,
    accidentWORK2Check,
    accidentWORK3Check,
    accidentWORK4Check,
    accidentWORK5Check,
    accidentWORK6Check,
    accidentWORK7Check,
    accidentWORK8Check,
    accidentWORK9Check,
    accidentWORK10Check,
    accidentWORK11Check,
    accidentWORK12Check,
    accidentWORK13Check,
    accidentWORK14Check,
    accidentWORK15Check,
    accidentWORK16Check,
    accidentWORK17Check,
    accidentWORK18Check,
    accidentWORK19Check,
    accidentWORK20Check,
    accidentWORK21Check,
    accidentWORK22Check,
    accidentWORK23Check,
    accidentWORK24Check,
    accidentWORK25Check,
    accidentWORK26Check,
    accidentWORK27Check,
    accidentWORK28Check,
    accidentWORK29Check,
    accidentWORK30Check,
    accidentWORK31Check,
    accidentWORK32Check,
    accidentWORK33Check,
    accidentWORK34Check,
    accidentWORK35Check,
    accidentWORK35Input1,
    accidentWORK35Input2,
    accidentWORK35Input3,
    accidentWORK35Input4,
    accidentWORK35Input5,
    accidentWORK35Input6,

    accidentHOMEduties1Check,
    accidentHOMEduties2Check,
    accidentHOMEduties3Check,
    accidentHOMEduties4Check,
    accidentHOMEduties5Check,
    accidentHOMEduties6Check,
    accidentHOMEduties7Check,
    accidentHOMEduties8Check,
    accidentHOMEduties9Check,
    accidentHOMEduties10Check,
    accidentHOMEduties11Check,
    accidentHOMEduties12Check,
    accidentHOMEduties13Check,
    accidentHOMEduties14Check,
    accidentHOMEduties15Check,
    accidentHOMEduties16Check,
    accidentHOMEduties17Check,
    accidentHOMEduties18Check,
    accidentHOMEduties19Check,
    accidentHOMEduties20Check,
    accidentHOMEduties21Check,
    accidentHOMEduties22Check,
    accidentHOMEduties23Check,
    accidentHOMEduties24Check,
    accidentHOMEduties25Check,
    accidentHOMEduties26Check,
    accidentHOMEduties27Check,
    accidentHOMEduties28Check,
    accidentHOMEduties29Check,
    accidentHOMEduties30Check,
    accidentHOMEduties31Check,
    accidentHOMEduties32Check,
    accidentHOMEduties33Check,
    accidentHOMEduties34Check,
    accidentHOMEduties35Check,
    accidentHOMEduties35Input1,
    accidentHOMEduties36Check,
    accidentHOMEduties36Input,
    accidentHOMEduties37Check,
    accidentHOMEduties37Input,
    accidentHOMEduties38Check,
    accidentHOMEduties38Input,
    doctorSign,
    doctorDate,
    accidentHOMEduties19Input1,
    accidentHOMEduties19Input2,
    initialCheck,
    updateCheck,
  },
} = checkout;

const initialValues = {
  dutiesPage: [
    {
      patientp5: "",
      datep5: moment().format("YYYY-MM-DD"),
      dateofInjuryp5: "",
      formCreatedDate: moment().format("DD-MM-YYYY"),
      doctorSign: "",
      doctorDate: "",

      // [DATE.name] : "",
      // [dateofinjury.name] : "",
      // [Patient.name] : "",
      [accidentWORK1Check.name]: false,
      [accidentWORK2Check.name]: false,
      [accidentWORK3Check.name]: false,
      [accidentWORK4Check.name]: false,
      [accidentWORK5Check.name]: false,
      [accidentWORK6Check.name]: false,
      [accidentWORK7Check.name]: false,
      [accidentWORK8Check.name]: false,
      [accidentWORK9Check.name]: false,
      [accidentWORK10Check.name]: false,
      [accidentWORK11Check.name]: false,
      [accidentWORK12Check.name]: false,
      [accidentWORK13Check.name]: false,
      [accidentWORK14Check.name]: false,
      [accidentWORK15Check.name]: false,
      [accidentWORK16Check.name]: false,
      [accidentWORK17Check.name]: false,
      [accidentWORK18Check.name]: false,
      [accidentWORK19Check.name]: false,
      [accidentWORK20Check.name]: false,
      [accidentWORK21Check.name]: false,
      [accidentWORK22Check.name]: false,
      [accidentWORK23Check.name]: false,
      [accidentWORK24Check.name]: false,
      [accidentWORK25Check.name]: false,
      [accidentWORK26Check.name]: false,
      [accidentWORK27Check.name]: false,
      [accidentWORK28Check.name]: false,
      [accidentWORK29Check.name]: false,
      [accidentWORK30Check.name]: false,

      [accidentWORK31Check.name]: false,
      [accidentWORK32Check.name]: false,
      [accidentWORK33Check.name]: false,
      [accidentWORK34Check.name]: false,
      [accidentWORK35Check.name]: false,
      [accidentWORK35Input1.name]: "",
      [accidentWORK35Input2.name]: "",
      [accidentWORK35Input3.name]: "",
      [accidentWORK35Input4.name]: "",
      [accidentWORK35Input5.name]: "",
      [accidentWORK35Input6.name]: "",

      [accidentHOMEduties1Check.name]: false,
      [accidentHOMEduties1Check.name]: false,
      [accidentHOMEduties2Check.name]: false,
      [accidentHOMEduties3Check.name]: false,
      [accidentHOMEduties4Check.name]: false,
      [accidentHOMEduties5Check.name]: false,
      [accidentHOMEduties6Check.name]: false,
      [accidentHOMEduties7Check.name]: false,
      [accidentHOMEduties8Check.name]: false,
      [accidentHOMEduties9Check.name]: false,
      [accidentHOMEduties10Check.name]: false,
      [accidentHOMEduties11Check.name]: false,
      [accidentHOMEduties12Check.name]: false,
      [accidentHOMEduties13Check.name]: false,
      [accidentHOMEduties14Check.name]: false,
      [accidentHOMEduties15Check.name]: false,
      [accidentHOMEduties16Check.name]: false,
      [accidentHOMEduties17Check.name]: false,
      [accidentHOMEduties18Check.name]: false,
      [accidentHOMEduties19Check.name]: false,
      [accidentHOMEduties20Check.name]: false,
      [accidentHOMEduties21Check.name]: false,
      [accidentHOMEduties22Check.name]: false,
      [accidentHOMEduties23Check.name]: false,
      [accidentHOMEduties24Check.name]: false,
      [accidentHOMEduties25Check.name]: false,
      [accidentHOMEduties26Check.name]: false,
      [accidentHOMEduties27Check.name]: false,
      [accidentHOMEduties28Check.name]: false,
      [accidentHOMEduties29Check.name]: false,
      [accidentHOMEduties30Check.name]: false,

      [accidentHOMEduties31Check.name]: false,
      [accidentHOMEduties32Check.name]: false,
      [accidentHOMEduties33Check.name]: false,
      [accidentHOMEduties34Check.name]: false,
      [accidentHOMEduties35Check.name]: false,
      [accidentHOMEduties35Input1.name]: "",
      [accidentHOMEduties36Check.name]: false,
      [accidentHOMEduties36Input.name]: "",
      [accidentHOMEduties37Check.name]: false,
      [accidentHOMEduties37Input.name]: "",
      [accidentHOMEduties38Check.name]: false,
      [accidentHOMEduties38Input.name]: "",
      [accidentHOMEduties19Input1.name]: "",
      [accidentHOMEduties19Input2.name]: "",
      [initialCheck.name]: false,
      [updateCheck.name]: false,
    },
  ],
  name: "",
};

export default initialValues;
