import moment from "moment";
const initialValues = {
  page24: [
    {
      formCreatedDate: moment().format("DD-MM-YYYY"),
      sections6: [
        {
          name: "Difficulty with detailed hand coordination",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty with making decisions",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty with suppressing socially inappropriate thoughts",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Socially inappropriate behavior",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Decisions made based on desires,regardless of the consequences",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty planning and organizing daily events",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty motivating yourself to start and finish tasks",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "A loss of attention and concentration",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
      ],
      sections7: [
        {
          name: "Hypersensitivities to touch or pain",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty with spatial awareness when moving,laying back in a chair, or leaning against a wall",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Frequently bumping into the wall or objects",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty with right-left discrimination",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Handwriting has become sloppier ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty with basic math calculations",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty finding words for written or verbal communication",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty recognizing symbols, words, or letters",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
      ],
      sections8: [
        {
          name: "Difficulty swallowing supplements or large bites of food",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Bowel motility and movements slow",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Bloating after meals",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Dry eyes or dry mouth",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "A racing heart",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "A flutter in the chest or an abnormal heart rhythm	",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Bowel or bladder incontinence,resulting in staining your underwear",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
      ],
      sections9: [
        {
          name: "A decrease in movement speed",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty initiating movement",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Stiffness in your muscles (not joints)",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "A stooped posture when walking",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Cramping of your hand when writing",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
      ],
      sections10: [
        {
          name: "Abnormal body movements (such as twitching legs)",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Desires to flinch, clear your throat,or perform some type of movement",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Constant nervousness and a restless mind ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Compulsive behaviors",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Increased tightness and tone in specific muscles",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
      ],
      sections11: [
        {
          name: "Difficulty with balance, or balance that is noticeably worse on one side",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "A need to hold the handrail or watch each step carefully when going down stairs",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Episodes of dizziness",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Nausea, car sickness, or seasickness",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "A quick impact after consuming alcohol",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "A slight hand shake when reaching for something",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Back muscles that tire quickly when standing or walking",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Chronic neck or back muscle tightness",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
      ],
    },
  ],
};

export default initialValues;
