import moment from "moment";
const initialValues = {
  page11: [
    {
      formCreatedDate: moment().format("DD-MM-YYYY"),
      tobacconever: false,
      tobaccoquit: false,
      tobaccoquitinput: "",
      tobaccoweek: false,
      tobaccoweekinput: "",
      alcohol: "",
      alcoholinput: "",
      drugsnone: false,
      drugsdiscribe: false,
      drugsdiscribeinput: "",
      sleephour: "",
      sleephourdis: false,
      sexuallyactive: "",
      sexuallyactivestd: false,
      sexuallyactivestdinput: "",
      excercise: "",
      water: "",
      AlcoholCheck: false,
      SmokesCheck: false,

      food: [
        { name: "Bananas", foodcheck: false },
        { name: "Eggs", foodcheck: false },
        { name: "Shellfish", foodcheck: false },
        { name: "Chocolate", foodcheck: false },
        { name: "Gluten", foodcheck: false },
        { name: "Soy", foodcheck: false },
        { name: "Citrus Fruits", foodcheck: false },
        { name: "Peanuts", foodcheck: false },
        { name: "Strawberries", foodcheck: false },
        { name: "Corn", foodcheck: false },
        { name: "Peppers", foodcheck: false },
        { name: "Tomatoes", foodcheck: false },
        { name: "Dairy", foodcheck: false },
        { name: "Refined Sugars", foodcheck: false },
        { name: "Wheat", foodcheck: false },
      ],
      othercheck: false,
      other: "",
      grains: "",
      vegetables: "",
      fruits: "",
      protein: "",
      dairy: "",
      fatsSweets: "",
      clientName: "",
    },
  ],
};

export default initialValues;
