const form = {
    formField:{
        section1Check:{
            type:'checkbox',
            name:"section1Check"
          },
          section2Check:{
            type:'checkbox',
            name:"section2Check"
          },
          section3Check:{
            type:'checkbox',
            name:"section3Check"
          },
          section4Check:{
            type:'checkbox',
            name:"section4Check"
          },
          section5Check:{
            type:'checkbox',
            name:"section5Check"
          },
          section6Check:{
            type:'checkbox',
            name:"section6Check"
          },
          section7Check:{
            type:'checkbox',
            name:"section7Check"
          },
          section8Check:{
            type:'checkbox',
            name:"section8Check"
          },
          section9Check:{
            type:'checkbox',
            name:"section9Check"
          },
          section10Check:{
            type:'checkbox',
            name:"section10Check"
          },
          section11Check:{
            type:'checkbox',
            name:"section11Check"
          },

          sectionBHNAF1Check:{
            type:'checkbox',
            name:"sectionBHNAF1Check"
          },
          sectionBHNAF2Check:{
            type:'checkbox',
            name:"sectionBHNAF2Check"
          },
          sectionBHNAF3Check:{
            type:'checkbox',
            name:"sectionBHNAF3Check"
          },
          sectionBHNAF4Check:{
            type:'checkbox',
            name:"sectionBHNAF4Check"
          },
          sectionBHNAF5Check:{
            type:'checkbox',
            name:"sectionBHNAF5Check"
          },
          sectionBHNAF6Check:{
            type:'checkbox',
            name:"sectionBHNAF6Check"
          },
          sectionBHNAF7Check:{
            type:'checkbox',
            name:"sectionBHNAF7Check"
          },
          sectionBHNAF8Check:{
            type:'checkbox',
            name:"sectionBHNAF8Check"
          },
          sectionBHNAF9Check:{
            type:'checkbox',
            name:"sectionBHNAF9Check"
          },
          sectionBHNAF10Check:{
            type:'checkbox',
            name:"sectionBHNAF10Check"
          },
          sectionBHNAF11Check:{
            type:'checkbox',
            name:"sectionBHNAF11Check"
          },
          sectionBHNAF12Check:{
            type:'checkbox',
            name:"sectionBHNAF12Check"
          },
          sectionBHNAF13Check:{
            type:'checkbox',
            name:"sectionBHNAF13Check"
          },
          sectionBHNAF14Check:{
            type:'checkbox',
            name:"sectionBHNAF14Check"
          },

          sectionNTAFACheck:{
            type:'checkbox',
            name:"sectionNTAFACheck"
          },
          sectionNTAFBCheck:{
            type:'checkbox',
            name:"sectionNTAFBCheck"
          },
          sectionNTAFC1Check:{
            type:'checkbox',
            name:"sectionNTAFC1Check"
          },
          sectionNTAFC2Check:{
            type:'checkbox',
            name:"sectionNTAFC2Check"
          },
          sectionNTAF1Check:{
            type:'checkbox',
            name:"sectionNTAF1Check"
          },
          sectionNTAF2Check:{
            type:'checkbox',
            name:"sectionNTAF2Check"
          },
          sectionNTAF3Check:{
            type:'checkbox',
            name:"sectionNTAF3Check"
          },
          sectionNTAF4Check:{
            type:'checkbox',
            name:"sectionNTAF4Check"
          },
          sectionNTAF5Check:{
            type:'checkbox',
            name:"sectionNTAF5Check"
          },
        
        }
    
}

export default form;