const form = {
  formId: "new-user-form",
  formField: {
    firstName: {
      name: "firstName",
      label: "Name",
      type: "text",
      placeholder: "eg. Micheal",
      errorMsg: "First name is required.",
    },
    name: {
      name: "name",
      label: "Name",
      type: "text",
      placeholder: "eg. Micheal",
      errorMsg: "First name is required.",
    },
    TODAYDATE: {
      type: "date",
      name: "Today's Date",
      label: "Today's Date",
      errorMsg: "Today's Date is required.",
    },
    DOB: {
      type: "date",
      name: "DOB",
      label: "DOB",
      errorMsg: "DOB is required.",
    },
    dob: {
      type: "date",
      name: "dob",
      label: "DOB",
      errorMsg: "dob is required.",
    },
    height: {
      name: "height",
      label: "Height",
      type: "number",
      placeholder: "eg. 175cm",
      errorMsg: "Height is required.",
    },
    weight: {
      name: "weight",
      label: "Weight",
      type: "number",
      placeholder: "eg. 1000g",
      errorMsg: "Weight is required.",
    },
    dominantHand: {
      name: "dominantHand",
      label: "Dominant Hand?",
      type: "radio",
      placeholder: "eg. 1000g",
      errorMsg: "Dominant Hand is required.",
    },
    address: {
      name: "address",
      label: "Address",
      type: "text",
      placeholder: "eg. Texas,USA",
      errorMsg: "Address is required.",
    },
    city: {
      name: "city",
      label: "City",
      type: "text",
      errorMsg: "City is required.",
    },
    zip: {
      name: "zip",
      label: "Zip",
      type: "number",
      placeholder: "enter Zip code",
      errorMsg: "Zip is required.",
      invalidMsg: "Zipcode is not valied (e.g. 70000).",
    },
    pincode: {
      name: "pincode",
      label: "Pincode",
      type: "number",
      placeholder: "Pincode",
      errorMsg: "Pincode is required.",
    },
    gender: {
      name: "gender",
      label: "Gender",
      type: "text",
      errorMsg: "Gender is required.",
    },
    lastName: {
      name: "lastName",
      label: "last name",
      type: "text",
      placeholder: "eg. Prior",
      errorMsg: "Last name is required.",
    },
    company: {
      name: "company",
      label: "company",
      type: "text",
      placeholder: "eg. Creative Tim",
      errorMsg: "company is required.",
    },

    email: {
      name: "email",
      label: "Email address",
      type: "email",
      placeholder: "eg. soft@dashboard.come",
      errorMsg: "Email address is required.",
      invalidMsg: "Your email address is invalid",
    },
    DL: {
      name: "DL",
      label: "DL#",
      type: "text",
      placeholder: "eg. Micheal#",
      errorMsg: "DL is required.",
    },
    address1: {
      name: "address1",
      label: "Address ",
      type: "text",
      placeholder: "eg. Street 111",
      errorMsg: "Address is required.",
    },
    city1: {
      name: "city1",
      label: "City",
      type: "text",
      placeholder: "eg. Texas",
      errorMsg: "City is required.",
    },
    zip1: {
      name: "zip1",
      label: "Zip",
      type: "number",
      placeholder: "enter Zip code",
      errorMsg: "Zip is required.",
      invalidMsg: "Zipcode is not valied (e.g. 70000).",
    },
    address2: {
      name: "address2",
      label: "Address",
      type: "text",
      placeholder: "eg. Street 221",
    },
    city2: {
      name: "city2",
      label: "City",
      type: "text",
      placeholder: "Select your city",
      errorMsg: "City is required.",
    },
    zip2: {
      name: "zip2",
      label: "Zip",
      type: "number",
      placeholder: "enter Zip code",
      errorMsg: "Zip is required.",
      invalidMsg: "Zipcode is not valied (e.g. 70000).",
    },
    address3: {
      name: "address3",
      label: "Address",
      type: "text",
      placeholder: "eg. Street 221",
    },
    city3: {
      name: "city3",
      label: "City",
      type: "text",
      placeholder: "Select your city",
      errorMsg: "City is required.",
    },
    zip3: {
      name: "zip3",
      label: "Zip",
      type: "number",
      placeholder: "enter Zip code",
      errorMsg: "Zip is required.",
      invalidMsg: "Zipcode is not valied (e.g. 70000).",
    },
    address4: {
      name: "address4",
      label: "Address ",
      type: "text",
      placeholder: "eg. Street 111",
      errorMsg: "Address is required.",
    },
    city4: {
      name: "city4",
      label: "City",
      type: "text",
      placeholder: "eg. Texas",
      errorMsg: "City is required.",
    },
    zip4: {
      name: "zip4",
      label: "Zip",
      type: "number",
      placeholder: "enter Zip code",
      errorMsg: "Zip is required.",
      invalidMsg: "Zipcode is not valied (e.g. 70000).",
    },

    city: {
      name: "city",
      label: "City",
      type: "text",
      placeholder: "Select your city",
      errorMsg: "City is required.",
    },
    EmergencyPhoneNumber: {
      name: "EmergencyPhoneNumber",
      label: "Emergency Phone Number",
      type: "number",
      placeholder: "eg.451036",
      errorMsg: "Emergency Phone Number is required.",
    },
    MaritalStatus: {
      name: "MaritalStatus",
      label: "Marital Status",
      type: "text",
      placeholder: "Select...",
      errorMsg: "Status is need to fill",
    },
    Cellphonenumber: {
      name: "Cellphonenumber",
      label: "Cell Phone Number",
      type: "number",
      placeholder: "eg. 366975120",
      errorMsg: "Cellphone number is required.",
    },
    Cellphonenumber1 : {
      name: "Cellphonenumber1",
      label: "Cell Phone Number",
      type: "number",
      placeholder: "eg. 366975120",
      errorMsg: "Cellphone number is required.",
    },
    phonenumbrCell : {
      name: "phonenumbrCell",
      label: "Cell Phone Number",
      type: "number",
      placeholder: "eg. 366975120",
      errorMsg: "Cellphone number is required.",
    },
    Cellphonenumber4: {
      name: "Cellphonenumber4",
      label: "Cell Phone Number",
      type: "number",
      placeholder: "eg. 366975120",
      errorMsg: "Cellphone number is required.",
    },
    Cellphonenumber3: {
      name: "Cellphonenumber3",
      label: "Cell Phone Number",
      type: "number",
      placeholder: "eg. 366975120",
      errorMsg: "Cellphone number is required.",
    },
    Cellphonenumber2: {
      name: "Cellphonenumber2",
      label: "Cell Phone Number",
      type: "number",
      placeholder: "eg. 366975120",
      errorMsg: "Cellphone number is required.",
    },
    Cellphonenumber0: {
      name: "Cellphonenumber0",
      label: "Cell Phone Number",
      type: "number",
      placeholder: "eg. 366975120",
      errorMsg: "Cellphone number is required.",
    },
    CellphonenumberA: {
      name: "CellphonenumberA",
      label: "Cell Phone Number",
      type: "number",
      placeholder: "eg. 366975120",
      errorMsg: "Cellphone number is required.",
    },
    Workphonenumber: {
      name: "Workphonenumber",
      label: "Work Phone Number",
      type: "number",
      placeholder: "eg. 366975120",
      errorMsg: "Workphone number is required.",
    },
    HealthInsurancecompany: {
      name: "HealthInsurancecompany",
      label: "Health Insurance company",
      type: "text",
      placeholder: "eg. abc company",
      errorMsg: "Health Insurance company name is required.",
    },
    Policy: {
      name: "Policy",
      label: "Policy#",
      type: "text",
      placeholder: "eg. abc Policy",
      errorMsg: "Policy is required.",
    },
    Adjuster: {
      name: "Adjuster",
      label: "Adjuster",
      type: "text",
      placeholder: "eg. Adjuster",
      errorMsg: "Adjuster is required.",
    },
    Phone: {
      name: "Phone",
      label: "Phone",
      type: "number",
      placeholder: "Number",
      errorMsg: "Phone number is required.",
      invalid:"invalid phone number"
    },
    Adjuster1: {
      name: "Adjuster1",
      label: "Adjuster",
      type: "text",
      placeholder: "eg. Adjuster",
      errorMsg: "Adjuster is required.",
    },
    Phone1: {
      name: "Phone1",
      label: "Phone",
      type: "number",
      placeholder: "eg. Adjuster",
      errorMsg: "Phone number is required.",
      invalid:"invalid phone number"
    },
    Agent: {
      name: "Agent",
      label: "Agent",
      type: "text",
      placeholder: "eg. Agent",
      errorMsg: "Agent is required.",
    },
    Phone2: {
      name: "Phone2",
      label: "Phone",
      type: "number",
      placeholder: "Number",
      errorMsg: "Phone number is required.",
      invalid:"invalid phone number"
    },
    Policy2: {
      name: "Policy2",
      label: "Policy#",
      type: "text",
      placeholder: "eg. abc Policy",
      errorMsg: "Policy is required.",
    },
    Claim: {
      name: "Claim",
      label: "Claim#",
      type: "text",
      placeholder: "eg. abc Claim",
      errorMsg: "Claim is required.",
    },
    Medicalpaymentcoverage: {
      name: "Medicalpaymentcoverage",
      label: "What Medical Payments Coverage?",
      type: "text",
      placeholder: "eg. abc Medical Payments Coverage",
      errorMsg: "Medical Payments Coverage is required.",
    },
    Uninsuredmotoristcoverage: {
      name: "Uninsuredmotoristcoverage",
      label: "What Uninsured Motorist Coverage?",
      type: "text",
      placeholder: "eg. abc Uninsured Motorist Coverage",
      errorMsg: "Uninsured Motorist Coverage is required.",
    },
    Lawfirmrepresent: {
      name: "Lawfirmrepresent",
      label: "What Law Firm Represents You?",
      type: "text",
      placeholder: "eg. abc Law Firm Represents You",
      errorMsg: "Law Firm Represents is required.",
    },
    Phone3: {
      name: "Phone3",
      label: "Phone",
      type: "number",
      placeholder: "Number",
      errorMsg: "Phone number is required.",
      invalid:"invalid phone number"
    },
    Lawyersname: {
      name: "Lawyersname",
      label: "Your Lawyer's Name",
      type: "text",
      placeholder: "eg. Lawyers's name",
      errorMsg: "Lawyer's Name is required.",
    },
    Insuredoncarpolicy: {
      name: "Insuredoncarpolicy",
      label: "Name of Insured on your Car Policy",
      type: "text",
      placeholder: "eg. Name of Insured on Your Car Policy",
      errorMsg: "Name of Insured on Your Car Policy is required.",
    },
    Patient: {
      name: "Patient",
      label: "For office use only Patient#",
      type: "text",
      placeholder: "For office use only",
      errorMsg: "Patient is required.",
    },
    Dateoflossaccident: {
      name: "Dataoflossaccident",
      label: "Date of Loss/Accident?",
      type: "date",
      placeholder: "eg. 12/02/2022",
      errorMsg: "Date of Loss/Accident is required.",
    },
    Dateforfirstsawanydoctor: {
      name: "Dateforfirstsawanydoctor",
      label: "Date you first saw any Doctor after accident",
      type: "date",
      placeholder: "eg. 12/02/2022",
      errorMsg: "Date you first saw any Doctor after accident is required.",
    },
    Costofallmedicaltretmentsinceaccident: {
      name: "Costofallmedicaltretmentsinceaccident",
      label: "Cost of all medical treatment since the accident? $",
      type: "number",
      placeholder: "eg. 100$",
      errorMsg: "Cost of all medical treatment is required.",
    },
    Howmuchincomeyoulost: {
      name: "Howmuchincomeyoulost",
      label: "How much income have you lost since the accident? $",
      type: "number",
      placeholder: "eg. 100$",
      errorMsg: "How much income have you lost is required.",
    },
    Propertydamageofyourcar: {
      name: "Propertydamageofyourcar",
      label: "What is the property damage (repair amount) of your car? $",
      type: "number",
      placeholder: "eg. 100$",
      errorMsg: "What is the property damage is required.",
    },
    Phone4: {
      name: "Phone4",
      label: "Phone",
      type: "number",
      placeholder: "eg. Adjuster",
      errorMsg: "Phone number is required.",
      invalid:"invalid phone number"
    },
    NameofPersonalMD: {
      name: "NameofPersonalMD",
      label: "Name of your Personal M.D.",
      type: "text",
      placeholder: "eg. 12345",
      errorMsg: "Name of your Personal M.D is required.",
    },
    lastSectionName: {
      name: "lastSectionName",
      label: "Name",
      type: "text",
      placeholder: "eg. Micheal",
      errorMsg: "Name is required.",
    },
    lastSectionType: {
      name: "lastSectionType",
      label: "Type",
      type: "text",
      placeholder: "eg. Micheal",
      errorMsg: "Type is required.",
    },
    lastSectionPhone: {
      name: "lastSectionPhone",
      label: "Phone#",
      type: "number",
      placeholder: "eg. Micheal",
      errorMsg: "Phone is required.",
      invalid : "Invalid phone number"
    },
    lastSectionBill: {
      name: "lastSectionBill",
      label: "Amount of Bill",
      type: "number",
      placeholder: "eg. Micheal",
      errorMsg: "Amount of Bill is required.",
    },
    lastSectionRecords: {
      name: "lastSectionRecords",
      label: "Records Rec'd",
      type: "text",
      placeholder: "eg. Micheal",
      errorMsg: "Records is required.",
    },
    CarInsurancecompany: {
      name: "CarInsurancecompany",
      label: "Car Insurance Company",
      type: "text",
      placeholder: "eg. Company name",
      errorMsg: "Car Insurance Company name is required.",
    },
    UserProfilePIC: {
      name: "UserProfilePIC",
      label: "UserProfilePIC",
      // type: "number",
      // placeholder: "eg. 366975120",
      // errorMsg: "phone number needed",
    },
    EmergencyName: {
      name: "EmergencyName",
      label: "Emergency Person Name",
      type: "text",
      placeholder: "eg.john jow",
    },
    EmergencyRelation: {
      name: "EmergencyRelation",
      label: "Relation",
      type: "text",
      placeholder: "eg. Father",
    },
    publicEmail: {
      name: "publicEmail",
      label: "public email",
      type: "email",
      placeholder: "Use an address you don't use frequently",
    },
    bio: {
      name: "bio",
      label: "bio",
      placeholder: "Say a few words about who you are or what you're working on.",
    },
    language: {
      type: "text",
      name: "language",
      label: "language",
      placeholder: "eg. English",
      errorMsg: "language is required.",
    },

    SocialSecurityNumber: {
      type: "number",
      name: "SocialSecurityNumber",
      label: "Social Security Number / Identification Number",
      placeholder: "eg.6454621",
    },
    NumberofChildren: {
      type: "number",
      name: "NumberofChildren",
      label: "Number of Children",
      placeholder: "eg.2",
      errorMsg: "required number of children",
    },
    Occupation: {
      type: "text",
      name: "Occupation",
      label: "Occupation",
      placeholder: "eg.Manager",
    },
    UserWorkHours: {
      type: "number",
      name: "UserWorkHours",
      label: "number of work hours per week",
      placeholder: "eg.68",
    },
    state: {
      type: "text",
      name: "state",
      label: "State",
      placeholder: "Select your State",
    },

    PractitionerName: {
      type: "text",
      name: "PractitionerName",
      label: "Practitioner:",
      placeholder: "Please Enter PractitionerName",
    },
    NPI: {
      type: "text",
      name: "NPI",
      label: "NPI",
      placeholder: "Please Enter NPI",
    },
    TIN: {
      type: "text",
      name: "TIN",
      label: "TIN",
      placeholder: "Please Enter TIN",
    },
    hourlyRate: {
      type: "text",
      name: "hourlyRate",
      label: "hourlyRate",
      placeholder: "Please Enter hourlyRate",
    },

    PatientName: {
      type: "text",
      name: "PatientName",
      label: "PatientName:",
      placeholder: "Please Enter PatientName",
    },
    newPatient: {
      type: "checkbox",
      name: "newPatient",
      label: "New",
      placeholder: "Please Enter NPI",
    },
    patientFollowUp: {
      type: "checkbox",
      name: "patientFollowUp",
      label: "Follow-Up",
      placeholder: "Please Enter TIN",
    },
    patientNewComplaint: {
      type: "checkbox",
      name: "patientNewComplaint",
      label: "New Complaint",
      placeholder: "Please Enter hourlyRate",
    },
    visitNumber: {
      type: "number",
      name: "visitNumber",
      label: "Visit Number",
      // placeholder:"Please Enter NPI",
    },
    patienttodaysDate: {
      type: "date",
      name: "patienttodaysDate",
      label: "Today's Date:",
      // placeholder:"Please Enter TIN",
    },
    patientNextReExam: {
      type: "date",
      name: "patientNextReExam",
      label: "Next Re-Exam",
      // placeholder:"Please Enter hourlyRate",
    },
    patientDob: {
      type: "date",
      name: "patientDob",
      label: "DOB:",
    },
    patientAge: {
      type: "number",
      name: "patientAge",
      label: "Age:",
    },
    patientHeight: {
      type: "text",
      name: "patientHeight",
      label: "Height:",
    },
    patientHeightNi: {
      type: "checkbox",
      name: "patientHeightNi",
      label: "NI:",
    },
    patientWeight: {
      type: "text",
      name: "patientWeight",
      label: "Weight:",
    },
    patientWeightNi: {
      type: "checkbox",
      name: "patientWeightNi",
      label: "NI:",
    },
    patientHtnYes: {
      type: "checkbox",
      name: "patientHtnYes",
      label: "Yes:",
    },
    patientHtnNo: {
      type: "checkbox",
      name: "patientHtnNo",
      label: "No:",
    },
    patientCautions: {
      type: "text",
      name: "patientCautions",
      label: "Cautions:",
    },

    isImproved: {
      type: "checkbox",
      name: "isImproved",
    },
    isNoChanges: {
      type: "checkbox",
      name: "isNoChanges",
    },
    isRegressed: {
      type: "checkbox",
      name: "isRegressed",
    },
    isFlareUp: {
      type: "checkbox",
      name: "isFlareUp",
    },
    additionalAssessment: {
      type: "text",
      name: "additionalAssessment",
      label: "additionalAssessment",
      placeholder: "Please Enter Additional Assessment",
    },

    doe: {
      type: "text",
      name: "doe",
      label: "Objective Findings: DOE:",
      placeholder: "Please Enter",
    },
    isVitals: {
      type: "checkbox",
      name: "isVitals",
    },
    bp: {
      type: "text",
      name: "bp",
      label: "bp",
      // placeholder:"Please Enter",
    },
    mmHG: {
      type: "text",
      name: "mmHG",
      label: "mmHG",
      // placeholder:"Please Enter",
    },
    pulse: {
      type: "text",
      name: "pulse",
      label: "pulse",
      // placeholder:"Please Enter",
    },
    temp: {
      type: "text",
      name: "temp",
      label: "temp",
      // placeholder:"Please Enter",
    },
    rr: {
      type: "text",
      name: "rr",
      label: "rr",
      // placeholder:"Please Enter",
    },
    spo2: {
      type: "text",
      name: "spo2",
      label: "spo2",
      // placeholder:"Please Enter",
    },
    isNeurologicalExam: {
      type: "checkbox",
      name: "isNeurologicalExam",
      // label: "neurologicalExam",
      // placeholder:"Please Enter",
    },
    isCranialNerves: {
      type: "checkbox",
      name: "isCranialNerves",
    },
    cranialNerves: {
      type: "text",
      name: "cranialNerves",
    },

    isRombergs: {
      type: "checkbox",
      name: "isRombergs",
    },
    rombergs: {
      type: "text",
      name: "rombergs",
    },

    isDiadichodyskinesia: {
      type: "checkbox",
      name: "isDiadichodyskinesia",
    },
    diadichodyskinesia: {
      type: "text",
      name: "diadichodyskinesia",
    },

    isDermatomes: {
      type: "checkbox",
      name: "isDermatomes",
    },
    dermatomes: {
      type: "text",
      name: "dermatomes",
    },

    isMyotomes: {
      type: "checkbox",
      name: "isMyotomes",
    },
    myotomes: {
      type: "text",
      name: "myotomes",
    },

    isDtrs: {
      type: "checkbox",
      name: "isDtrs",
    },
    dtrs: {
      type: "text",
      name: "dtrs",
    },

    isPathological: {
      type: "checkbox",
      name: "isPathological",
    },
    pathological: {
      type: "text",
      name: "pathological",
    },

    isHomans: {
      type: "checkbox",
      name: "isHomans",
    },
    homans: {
      type: "text",
      name: "homans",
    },

    flexion60_exam: {
      type: "text",
      name: "flexion60_exam",
    },
    flexion60_pain: {
      type: "checkbox",
      name: "flexion60_pain",
    },
    flexion60_noPain: {
      type: "checkbox",
      name: "flexion60_noPain",
    },
    flexion60_location: {
      type: "text",
      name: "flexion60_location",
    },
    flexion60_left: {
      type: "text",
      name: "flexion60_left",
    },
    flexion60_right: {
      type: "text",
      name: "flexion60_right  ",
    },

    extension50_exam: {
      type: "text",
      name: "extension50_exam",
    },
    extension50_pain: {
      type: "checkbox",
      name: "extension50_pain",
    },
    extension50_noPain: {
      type: "checkbox",
      name: "extension50_noPain",
    },
    extension50_location: {
      type: "text",
      name: "extension50_location",
    },
    extension50_left: {
      type: "text",
      name: "extension50_left",
    },
    extension50_right: {
      type: "text",
      name: "extension50_right  ",
    },

    leftLateralFlexion40_exam: {
      type: "text",
      name: "leftLateralFlexion40_exam",
    },
    leftLateralFlexion40_pain: {
      type: "checkbox",
      name: "leftLateralFlexion40_pain",
    },
    leftLateralFlexion40_noPain: {
      type: "checkbox",
      name: "leftLateralFlexion40_noPain",
    },
    leftLateralFlexion40_location: {
      type: "text",
      name: "leftLateralFlexion40_location",
    },
    leftLateralFlexion40_left: {
      type: "text",
      name: "leftLateralFlexion40_left",
    },
    leftLateralFlexion40_right: {
      type: "text",
      name: "leftLateralFlexion40_right",
    },

    rightLateralFlexion40_exam: {
      type: "text",
      name: "rightLateralFlexion40_exam",
    },
    rightLateralFlexion40_pain: {
      type: "checkbox",
      name: "rightLateralFlexion40_pain",
    },
    rightLateralFlexion40_noPain: {
      type: "checkbox",
      name: "rightLateralFlexion40_noPain",
    },
    rightLateralFlexion40_location: {
      type: "text",
      name: "rightLateralFlexion40_location",
    },
    rightLateralFlexion40_left: {
      type: "text",
      name: "rightLateralFlexion40_left",
    },
    rightLateralFlexion40_right: {
      type: "text",
      name: "rightLateralFlexion40_right",
    },

    leftRotation80_exam: {
      type: "text",
      name: "leftRotation80_exam",
    },
    leftRotation80_pain: {
      type: "checkbox",
      name: "leftRotation80_pain",
    },
    leftRotation80_noPain: {
      type: "checkbox",
      name: "leftRotation80_noPain",
    },
    leftRotation80_location: {
      type: "text",
      name: "leftRotation80_location",
    },
    leftRotation80_left: {
      type: "text",
      name: "leftRotation80_left",
    },
    leftRotation80_right: {
      type: "text",
      name: "leftRotation80_right",
    },

    rightRotation80_exam: {
      type: "text",
      name: "rightRotation80_exam",
    },
    rightRotation80_pain: {
      type: "checkbox",
      name: "rightRotation80_pain",
    },
    rightRotation80_noPain: {
      type: "checkbox",
      name: "rightRotation80_noPain",
    },
    rightRotation80_location: {
      type: "text",
      name: "rightRotation80_location",
    },
    rightRotation80_left: {
      type: "text",
      name: "rightRotation80_left",
    },
    rightRotation80_right: {
      type: "text",
      name: "rightRotation80_right",
    },

    cervicalRegionalNotes1: {
      type: "text",
      name: "cervicalRegionalNotes1",
    },
    cervicalRegionalNotes2: {
      type: "text",
      name: "cervicalRegionalNotes2",
    },

    flexion90_exam: {
      type: "text",
      name: "flexion90_exam",
    },
    flexion90_pain: {
      type: "checkbox",
      name: "flexion90_pain",
    },
    flexion90_noPain: {
      type: "checkbox",
      name: "flexion90_noPain",
    },
    flexion90_location: {
      type: "text",
      name: "flexion90_location",
    },

    extension30_exam: {
      type: "text",
      name: "extension30_exam",
    },
    extension30_pain: {
      type: "checkbox",
      name: "extension30_pain",
    },
    extension30_noPain: {
      type: "checkbox",
      name: "extension30_noPain",
    },
    extension30_location: {
      type: "text",
      name: "extension30_location",
    },

    leftLateralFlexion20_exam: {
      type: "text",
      name: "leftLateralFlexion20_exam",
    },
    leftLateralFlexion20_pain: {
      type: "checkbox",
      name: "leftLateralFlexion20_pain",
    },
    leftLateralFlexion20_noPain: {
      type: "checkbox",
      name: "leftLateralFlexion20_noPain",
    },
    leftLateralFlexion20_location: {
      type: "text",
      name: "leftLateralFlexion20_location",
    },

    rightLateralFlexion20_exam: {
      type: "text",
      name: "rightLateralFlexion20_exam",
    },
    rightLateralFlexion20_pain: {
      type: "checkbox",
      name: "rightLateralFlexion20_pain",
    },
    rightLateralFlexion20_noPain: {
      type: "checkbox",
      name: "rightLateralFlexion20_noPain",
    },
    rightLateralFlexion20_location: {
      type: "text",
      name: "rightLateralFlexion20_location",
    },

    leftRotation30_exam: {
      type: "text",
      name: "leftRotation30_exam",
    },
    leftRotation30_pain: {
      type: "checkbox",
      name: "leftRotation30_pain",
    },
    leftRotation30_noPain: {
      type: "checkbox",
      name: "leftRotation30_noPain",
    },
    leftRotation30_location: {
      type: "text",
      name: "leftRotation30_location",
    },

    rightRotation30_exam: {
      type: "text",
      name: "rightRotation30_exam",
    },
    rightRotation30_pain: {
      type: "checkbox",
      name: "rightRotation30_pain",
    },
    rightRotation30_noPain: {
      type: "checkbox",
      name: "rightRotation30_noPain",
    },
    rightRotation30_location: {
      type: "text",
      name: "rightRotation30_location",
    },

    lumbarRegionalNotes1: {
      type: "text",
      name: "lumbarRegionalNotes1",
    },

    //12th pae formFields
    dizzinessCheck: {
      type: "checkbox",
      name: "dizzinessCheck",
    },
    dizzinessinput: {
      type: "text",
      name: "dizzinessinput",
    },
    DiplopiaCheck: {
      type: "checkbox",
      name: "DiplopiaCheck",
    },
    Diplopiainput: {
      type: "text",
      name: "Diplopiainput",
    },
    DysphagiaCheck: {
      type: "checkbox",
      name: "DysphagiaCheck",
    },
    DysphagiaInput: {
      type: "text",
      name: "DysphagiaInput",
    },
    DysphasiaCheck: {
      type: "checkbox",
      name: "DysphasiaCheck",
    },
    DysphasiaInput: {
      type: "text",
      name: "DysphasiaInput",
    },
    DropCheck: {
      type: "checkbox",
      name: "DropCheck",
    },
    DropInput: {
      type: "text",
      name: "DropInput",
    },
    NystagmusCheck: {
      type: "checkbox",
      name: "NystagmusCheck",
    },
    NystagmusInput: {
      type: "text",
      name: "NystagmusInput",
    },
    //13thpage from fields
    Example: {
      type: "text",
      name: "Example",
      label: "Example",
      errorMsg: "Example is a required field.",
      value: "Example",
    },
    Disease: {
      type: "text",
      name: "Disease",
      label: "Disease",
      errorMsg: "Disease is a required field.",
      value: "Disease",
    },
    Anemia: {
      type: "text",
      name: "Anemia",
      label: "Anemia",
      errorMsg: "Anemia is a required field.",
      value: "Anemia",
    },
    BloodSugar: {
      type: "text",
      name: "BloodSugar",
      label: "Blood Sugar",
      errorMsg: "Blood Sugar is a required field.",
      value: "Blood Sugar",
    },
    Circulation: {
      type: "text",
      name: "Circulation",
      label: "Circulation",
      errorMsg: "Circulation is a required field.",
      value: "Circulation",
    },
    LeakyGut: {
      type: "text",
      name: "LeakyGut",
      label: "Leaky Gut(may refer to Cyrex Array 2 to confirm Dx)",
      errorMsg: "Leaky Gut is a required field.",
      value: "Leaky Gut",
    },
    LeakyBrain: {
      type: "text",
      name: "LeakyBrain",
      label: "Leaky Brain",
      errorMsg: "Leaky Brain is a required field.",
      value: "Leaky Brain",
    },
    Inflammation: {
      type: "text",
      name: "Inflammation",
      label:
        " Inflammation: (Note, CRP and ESR do not show up until later in disease process. Increased Ferratin and HDLs > 80 indicate subtle inflammation)",
      errorMsg: "Inflammation is a required field.",
      value: "Inflammation",
    },
    TxPlan: {
      type: "text",
      name: "TxPlan",
      label: "Tx Plan",
      errorMsg: "Tx Plan is a required field.",
      value: "Tx Plan",
    },
    TBD: {
      type: "text",
      name: "TBD",
      label: "TBD",
      errorMsg: "TBD is a required field.",
      value: "TBD",
    },

    //form 14fields
    Complaint: {
      type: "text",
      name: "Complaint",
    },
    symptoms: {
      type: "text",
      name: "symptoms",
    },
    Limitations: {
      type: "text",
      name: "Limitations",
    },
    Sequence: {
      type: "text",
      name: "Sequence",
    },
    Functional: {
      type: "text",
      name: "Functional",
    },
    Timemanagement: {
      type: "text",
      name: "Timemanagement",
    },

    symptomsformField: {
      Patient: {
        name: "Patient",
        label: "Patient",
        type: "text",
        placeholder: "For office use only",
        errorMsg: "Patient is required.",
      },
      DATE: {
        type: "date",
        name: "Date",
        label: "Date",
        placeholder: "03/02/2022",
        errorMsg: "Date is required.",
      },
      dateofinjury: {
        type: "date",
        name: "Date",
        label: "Date of Injury",
        placeholder: "03/02/2022",
        errorMsg: "Date of Injury is required.",
      },
      clucksoundswithneck: {
        type: "text",
        name: "clucksoundswithneck",
        label: "'Clunk' sounds with neck movements",
        errorMsg: "Clunk' sounds with neck movements is required.",
        value: "'Clunk' sounds with neck movements",
      },
      neckpain: {
        type: "text",
        name: "neckpain",
        label: "Neck pain",
        errorMsg: "Neck pain is a required field.",
        value: "Neck pain",
      },
      upperbackpain: {
        type: "text",
        name: "upperbackpain",
        label: "Upper back pain",
        errorMsg: "Upper back pain is a required field.",
        value: "Upper back pain",
      },
      lowbackpain: {
        type: "text",
        name: "lowbackpain",
        label: "Low back pain",
        errorMsg: "Low back pain is a required field.",
        value: "Low back pain",
      },
      shoulderpain: {
        type: "text",
        name: "shoulderpain",
        label: "Shoulder pain",
        errorMsg: "Shoulder pain is a required field.",
        value: "Shoulder pain",
      },
      upperArmPain: {
        type: "text",
        name: "upperArmPain",
        label: "Upper arm pain",
        errorMsg: "Upper arm pain is a required field.",
        value: "Upper arm pain",
      },
      elbowPain: {
        type: "text",
        name: "elbowPain",
        label: "Elbow pain",
        errorMsg: "Elbow pain is a required field.",
        value: "Elbow pain",
      },
      forearmPain: {
        type: "text",
        name: "forearmPain",
        label: "Forearm pain",
        errorMsg: "Forearm pain is a required field.",
        value: "Forearm pain",
      },
      wristPain: {
        type: "text",
        name: "wristPain",
        label: "Wrist pain",
        errorMsg: "Wrist pain is a required field.",
        value: "Wrist pain",
      },
      handPain: {
        type: "text",
        name: "handPain",
        label: "Hand pain",
        errorMsg: "Hand pain is a required field.",
        value: "Hand pain",
      },
      hipPain: {
        type: "text",
        name: "hipPain",
        label: "Hip pain",
        errorMsg: "Hip pain is a required field.",
        value: "Hip pain",
      },
      upperLegPain: {
        type: "text",
        name: "upperLegPain",
        label: "Upper leg pain",
        errorMsg: "Upper leg pain is a required field.",
        value: "Upper leg pain",
      },
      kneePain: {
        type: "text",
        name: "kneePain",
        label: "Knee pain",
        errorMsg: "Knee pain is a required field.",
        value: "Knee pain",
      },
      loweLegPain: {
        type: "text",
        name: "loweLegPain",
        label: "Lower leg pain",
        errorMsg: "Lower leg pain is a required field.",
        value: "Lower leg pain",
      },
      anklePAin: {
        type: "text",
        name: "anklePAin",
        label: "Ankle pain",
        errorMsg: "Ankle pain is a required field.",
        value: "Ankle pain",
      },
      footPain: {
        type: "text",
        name: "footPain",
        label: "Foot pain",
        errorMsg: "Foot pain is a required field.",
        value: "Foot pain",
      },
      jawPain: {
        type: "text",
        name: "jawPain",
        label: "Jaw pain",
        errorMsg: "Jaw pain is a required field.",
        value: "Jaw pain",
      },
      clickingInJaw: {
        type: "text",
        name: "clickingInJaw",
        label: "Clicking in Jaw",
        errorMsg: "Clicking in Jaw is a required field.",
        value: "Clicking in Jaw",
      },
      painWhenChewing: {
        type: "text",
        name: "painWhenChewing",
        label: "Pain when chewing",
        errorMsg: "Pain when chewing is a required field.",
        value: "Pain when chewing",
      },
      facePain: {
        type: "text",
        name: "facePain",
        label: "Face pain",
        errorMsg: "Face pain is a required field.",
        value: "Face pain",
      },
      chestPain: {
        type: "text",
        name: "chestPain",
        label: "Chest pain",
        errorMsg: "Chest pain is a required field.",
        value: "Chest pain",
      },
      stomachPain: {
        type: "text",
        name: "stomachPain",
        label: "Stomach pain",
        errorMsg: "Stomach pain is a required field.",
        value: "Stomach pain",
      },
    },
    // 19 page Filed
    humanSidebodyPoints: {
      type: "text",
      name: "humansidepoint",
      label: "Human Side Point",
      errorMsg: "Human Side Point is a required field.",
      value: "Human Side Point",
    },
    humanexcerciseone: {
      type: "text",
      name: "humanexcerciseone",
      label: "Human Excercise One",
      errorMsg: "Human Excercise One is a required field.",
      value: "Human Excercise one",
    },
    leftshoulderdesc: {
      type: "text",
      name: "leftshoulderdesc",
      label: "leftShoulder",
      errorMsg: "LeftShoulder Description is a required field.",
      value: "Left Shoulder Description",
    },
    rightshoulderdesc: {
      type: "text",
      name: "rightshoulderdesc",
      label: "rightShoulder",
      errorMsg: "Right Shoulder Description is a required field.",
      value: "Right Shoulder Description",
    },
    leftthoricdesc: {
      type: "text",
      name: "leftthoricdesc",
      label: "Left Thoric description",
      errorMsg: "Left Thoric Description is a required field.",
      value: "Left Thoric Description",
    },
    rightthoricdesc: {
      type: "text",
      name: "rightleftthoricdesc",
      label: "Right Thoric description",
      errorMsg: "Right Thoric Description is a required field.",
      value: "Right Thoric Description",
    },
    leftpelvisdesc: {
      type: "text",
      name: "leftpelvisdesc",
      label: "Left Pelvis description",
      errorMsg: "Left Pelvis description is a required field.",
      value: "Left Pelvin Description",
    },
    rightpelvisdesc: {
      type: "text",
      name: "rightpelvisdesc",
      label: "Right Pelvis description",
      errorMsg: "Right Pelvis description is a required field.",
      value: "Right Pelvin Description",
    },
    lefthipdesc: {
      type: "text",
      name: "lefthipdesc",
      label: "Left HIP Description",
      errorMsg: "Left Hip description is a required field.",
      value: "Left HIP Description",
    },
    righthipdesc: {
      type: "text",
      name: "righthipdesc",
      label: "Right HIP Description",
      errorMsg: "Right Hip description is a required field.",
      value: "Right HIP Description",
    },
    leftkneedesc: {
      type: "text",
      name: "leftkneedesc",
      label: "Left Knee Descirption",
      errorMsg: "Left Knee Description is a required field.",
      value: "Left Knee Description",
    },
    rightkneedesc: {
      type: "text",
      name: "rightkneedesc",
      label: "Right Knee Descirption",
      errorMsg: "Right Knee Description is a required field.",
      value: "Right Knee Description",
    },
    leftankledesc: {
      type: "text",
      name: "leftankledesc",
      label: "Left Ankle Description",
      errorMsg: "Left Ankle Description is a required field.",
      value: "Left Ankle Description",
    },
    rightankledesc: {
      type: "text",
      name: "rightankledesc",
      label: "Right Ankle Description",
      errorMsg: "Right Ankle Description is a required field.",
      value: "Right Ankle Description",
    },
    leftheaddesc: {
      type: "text",
      name: "leftheaddesc",
      label: "Left Head description",
      errorMsg: "Left Head description is a required field.",
      value: "Left Head description",
    },
    rightheaddesc: {
      type: "text",
      name: "rightheaddesc",
      label: "Right Head description",
      errorMsg: "Right Head description is a required field.",
      value: "Right Head description",
    },
    HumanFullbodyPoints: {
      type: "text",
      name: "Humanfullbodypoint",
      label: "Human Full Body Point",
      errorMsg: "Human Full Body point is a required field.",
      value: "Stomach pain",
    },
    humanexcerciseTwo: {
      type: "text",
      name: "Humanexcercisetwo",
      label: "Human Excercise Two",
      errorMsg: "Human Excercise Two is a required field.",
      value: "Human Excercise Two",
    },
    ClientName: {
      type: "text",
      name: "ClientName",
      label: "Client Name",
      errorMsg: "Client Name pain is a required field.",
      value: "Client Name",
    },
    Chiefcomplaint: {
      type: "text",
      name: "Chiefcomplaint",
      label: "Chief complaint",
      errorMsg: "Chief complaint is a required field.",
      value: "Chief complaint",
    },
    Painlevel: {
      type: "text",
      name: "Painlevel",
      label: "Pain Level",
      errorMsg: "Pain Level is a required field.",
      value: "Pain Level",
    },
    Practitioner: {
      type: "text",
      name: "Practitioner",
      label: "Practitioner",
      errorMsg: "Practitioner is a required field.",
      value: "Practitioner",
    },
    Date: {
      type: "date",
      name: "Date",
      label: "Date",
      errorMsg: "Date is a required field.",
      value: "Date",
    },
    PhysicianClearance: {
      type: "text",
      name: "Physicianclearance",
      label: "Physician Clearance",
      errorMsg: "Physician Clearance is a required field.",
      value: "Physician Clearance",
    },

    // 20 page field
    CrossPatternCONTRAIPSIControl: {
      type: "text",
      name: "CrossPatternCONTRA/IPSIControl",
      label: "Cross Pattern CONTRA/IPSIControl",
      errorMsg: "Cross Pattern CONTRA/IPSI Control is a required field.",
      value: "Cross Pattern CONTRA/IPSI Control",
    },
    CrossPatternCONTRAIPSI: {
      type: "text",
      name: "CrossPatternCONTRA/IPSI",
      label: "Cross Pattern CONTRA/IPSI",
      errorMsg: "Cross Pattern CONTRA/IPSI is a required field.",
      value: "Cross Pattern CONTRA/IPSI",
    },
    COGLoadsRLControl: {
      type: "text",
      name: "COGLoadsR/LControl",
      label: "COG Loads R/L Control",
      errorMsg: "COG Loads R/L Control is a required field.",
      value: "COG Loads R/L Control",
    },
    COGLoadsRL: {
      type: "text",
      name: "COGLoadsR/L",
      label: "COG Loads R/L",
      errorMsg: "COG Loads R/L is a required field.",
      value: "COG Loads R/L",
    },
    RLKnIRERControl: {
      type: "text",
      name: "R/L Kn IR/ER @ Control",
      label: "R/L Kn IR/ER @ Control",
      errorMsg: "R/L Kn IR/ER @ Control is a required field.",
      value: "R/L Kn IR/ER @ Control",
    },
    RLKnIRER: {
      type: "text",
      name: "R/L Kn IR/ER @",
      label: "R/L Kn IR/ER @",
      errorMsg: "R/L Kn IR/ER @ is a required field.",
      value: "R/L Kn IR/ER @",
    },
    RLHipELEVControl: {
      type: "text",
      name: "R/L Hip ELEV @ Control",
      label: "R/L Hip ELEV @ Control",
      errorMsg: "R/L Hip ELEV @ Control is a required field.",
      value: "R/L Hip ELEV @ Control",
    },
    RLHipELEV: {
      type: "text",
      name: "R/L Hip ELEV @",
      label: "R/L Hip ELEV @",
      errorMsg: "R/L Hip ELEV @ is a required field.",
      value: "R/L Hip ELEV @",
    },
    RLHipLATShiftControl: {
      type: "text",
      name: "R/L Hip LAT Shift @ Control",
      label: "R/L Hip LAT Shift @ Control",
      errorMsg: "R/L Hip LAT Shift @ Control is a required field.",
      value: "R/L Hip LAT Shift @ Control",
    },
    RLHipLATShift: {
      type: "text",
      name: "R/L Hip LAT Shift @",
      label: "R/L Hip LAT Shift @",
      errorMsg: "R/L Hip LAT Shift @ is a required field.",
      value: "R/L Hip LAT Shift @",
    },
    RLHipFLEXEXTdecrControl: {
      type: "text",
      name: "R/L Hip FLEX/EXT decr @ Control",
      label: "R/L Hip FLEX/EXT decr @ Control",
      errorMsg: "R/L Hip FLEX/EXT decr @ Control is a required field.",
      value: "R/L Hip FLEX/EXT decr @ Control",
    },
    RLHipFLEXEXTdecr: {
      type: "text",
      name: "R/L Hip FLEX/EXT decr @",
      label: "R/L Hip FLEX/EXT decr @",
      errorMsg: "R/L Hip FLEX/EXT decr @ is a required field.",
      value: "R/L Hip FLEX/EXT decr @",
    },
    RLHipROTforFLEXEXTControl: {
      type: "text",
      name: "R/L Hip ROT for FLEX/EXT @ Control",
      label: "R/L Hip ROT for FLEX/EXT @ Control",
      errorMsg: "R/L Hip ROT for FLEX/EXT @ Control is a required field.",
      value: "R/L Hip ROT for FLEX/EXT @ Control",
    },
    RLHipROTforFLEXEXT: {
      type: "text",
      name: "R/L Hip ROT for FLEX/EXT @",
      label: "R/L Hip ROT for FLEX/EXT @",
      errorMsg: "R/L Hip ROT for FLEX/EXT @ is a required field.",
      value: "R/L Hip ROT for FLEX/EXT @",
    },
    RLPelvicFLEXEXTdecrControl: {
      type: "text",
      name: "R/L Pelvic FLEX/EXT decr @ Control",
      label: "R/L Pelvic FLEX/EXT decr @ Control",
      errorMsg: "R/L Pelvic FLEX/EXT decr @ Control is a required field.",
      value: "R/L Pelvic FLEX/EXT decr @ Control",
    },
    RLPelvicFLEXEXTdecr: {
      type: "text",
      name: "R/L Pelvic FLEX/EXT decr @",
      label: "R/L Pelvic FLEX/EXT decr @",
      errorMsg: "R/L Pelvic FLEX/EXT decr @ is a required field.",
      value: "R/L Pelvic FLEX/EXT decr @",
    },
    RLPelvicROTIncrDecrControl: {
      type: "text",
      name: "R/L Pelvic ROT Incr/Decr @ Control",
      label: "R/L Pelvic ROT Incr/Decr @ Control",
      errorMsg: "R/L Pelvic ROT Incr/Decr @ Control is a required field.",
      value: "R/L Pelvic ROT Incr/Decr @ Control",
    },
    RLPelvicROTIncrDecr: {
      type: "text",
      name: "R/L Pelvic ROT Incr/Decr @",
      label: "R/L Pelvic ROT Incr/Decr @",
      errorMsg: "R/L Pelvic ROT Incr/Decr @ is a required field.",
      value: "R/L Pelvic ROT Incr/Decr @",
    },
    TorsoCROTControl: {
      type: "text",
      name: "Torso C-ROT Control",
      label: "Torso C-ROT Control",
      errorMsg: "Torso C-ROT Control is a required field.",
      value: "Torso C-ROT Control",
    },
    TorsoCROT: {
      type: "text",
      name: "Torso C-ROT",
      label: "Torso C-ROT",
      errorMsg: "Torso C-ROT is a required field.",
      value: "Torso C-ROT",
    },
    TorsoOffsetRLControl: {
      type: "text",
      name: "Torso Offset R/L Control",
      label: "Torso Offset R/L Control",
      errorMsg: "Torso Offset R/L Control is a required field.",
      value: "Torso Offset R/L Control",
    },
    TorsoOffsetRL: {
      type: "text",
      name: "Torso Offset R/L",
      label: "Torso Offset R/L",
      errorMsg: "Torso Offset R/L is a required field.",
      value: "Torso Offset R/L",
    },
    TorsoLATFLEXControl: {
      type: "text",
      name: "Torso LAT FLEX @ Control",
      label: "Torso LAT FLEX @ Control",
      errorMsg: "Torso LAT FLEX @ Control is a required field.",
      value: "Torso LAT FLEX @ Control",
    },
    TorsoLATFLEX: {
      type: "text",
      name: "Torso LAT FLEX @",
      label: "Torso LAT FLEX @",
      errorMsg: "Torso LAT FLEX @ is a required field.",
      value: "Torso LAT FLEX @",
    },
    HATLoadLRControl: {
      type: "text",
      name: "HAT Load L/R @ Control",
      label: "HAT Load L/R @ Control",
      errorMsg: "HAT Load L/R @ Control is a required field.",
      value: "HAT Load L/R @ Control",
    },
    HATLoadLR: {
      type: "text",
      name: "HAT Load L/R @",
      label: "HAT Load L/R @",
      errorMsg: "HAT Load L/R @ is a required field.",
      value: "HAT Load L/R @",
    },
    RLFootIRERControl: {
      type: "text",
      name: "R/L Foot IR/ER @ Control",
      label: "R/L Foot IR/ER @ Control",
      errorMsg: "R/L Foot IR/ER @ Control is a required field.",
      value: "R/L Foot IR/ER @ Control",
    },
    RLFootIRER: {
      type: "text",
      name: "R/L Foot IR/ER @",
      label: "R/L Foot IR/ER @",
      errorMsg: "R/L Foot IR/ER @ is a required field.",
      value: "R/L Foot IR/ER @",
    },
    RLCductIRERControl: {
      type: "text",
      name: "R/L C-duct IR/ER with Hu/Pelvis/Fem/Tib/Ank Control",
      label: "R/L C-duct IR/ER with Hu/Pelvis/Fem/Tib/Ank Control",
      errorMsg: "R/L C-duct IR/ER with Hu/Pelvis/Fem/Tib/Ankis Control a required field.",
      value: "R/L C-duct IR/ER with Hu/Pelvis/Fem/Tib/Ank Control",
    },
    RLCductIRER: {
      type: "text",
      name: "R/L C-duct IR/ER with Hu/Pelvis/Fem/Tib/Ank",
      label: "R/L C-duct IR/ER with Hu/Pelvis/Fem/Tib/Ank",
      errorMsg: "R/L C-duct IR/ER with Hu/Pelvis/Fem/Tib/Ankis a required field.",
      value: "R/L C-duct IR/ER with Hu/Pelvis/Fem/Tib/Ank",
    },
    RLArmSwingControl: {
      type: "text",
      name: "R/L Arm Swing Control",
      label: "R/L Arm Swing Control",
      errorMsg: "R/L Arm SwingL Control is a required field.",
      value: "R/L Arm Swing Control",
    },
    RLArmSwing: {
      type: "text",
      name: "R/L Arm Swing",
      label: "R/L Arm Swing",
      errorMsg: "R/L Arm SwingL is a required field.",
      value: "R/L Arm Swing",
    },
    RLShFLEXEXTControl: {
      type: "text",
      name: "R/L Sh FLEX/EXT @ Control",
      label: "R/L Sh FLEX/EXT @ Control",
      errorMsg: "R/L Sh FLEX/EXT @ Control is a required field.",
      value: "R/L Sh FLEX/EXT @ Control",
    },
    RLShFLEXEXT: {
      type: "text",
      name: "R/L Sh FLEX/EXT @",
      label: "R/L Sh FLEX/EXT @",
      errorMsg: "R/L Sh FLEX/EXT @ is a required field.",
      value: "R/L Sh FLEX/EXT @",
    },
    RLArmCarryingAngleIncrDecrControl: {
      type: "text",
      name: "R/L Arm Carrying Angle Incr/Decr Control",
      label: "R/L Arm Carrying Angle Incr/Decr Control",
      errorMsg: "R/L Arm Carrying Angle Incr/Decr Control is a required field.",
      value: "R/L Arm Carrying Angle Incr/Decr Control",
    },
    RLArmCarryingAngleIncrDecr: {
      type: "text",
      name: "R/L Arm Carrying Angle Incr/Decr",
      label: "R/L Arm Carrying Angle Incr/Decr",
      errorMsg: "R/L Arm Carrying Angle Incr/Decr is a required field.",
      value: "R/L Arm Carrying Angle Incr/Decr",
    },
    HOHControl: {
      type: "text",
      name: "HOH-Control",
      label: "HOH Control",
      errorMsg: "HOH Control is a required field.",
      value: "HOH Control",
    },
    HOH: {
      type: "text",
      name: "HOH",
      label: "HOH",
      errorMsg: "HOH is a required field.",
      value: "HOH",
    },

    HBBControl: {
      type: "text",
      name: "HBB-Control",
      label: "HBB Control",
      errorMsg: "HBB Control is a required field.",
      value: "HBB Control",
    },
    HBB: {
      type: "text",
      name: "HBB",
      label: "HBB",
      errorMsg: "HBB is a required field.",
      value: "HBB",
    },
    DFControl: {
      type: "text",
      name: "DF-Control",
      label: "DF Control",
      errorMsg: "DF Control is a required field.",
      value: "DF Control",
    },
    DF: {
      type: "text",
      name: "DF",
      label: "DF",
      errorMsg: "DF is a required field.",
      value: "DF",
    },
    Gaitnotes: {
      type: "text",
      name: "Gaitnotes",
      label: "Gait Notes",
      errorMsg: "Gait Notes is a required field.",
      value: "Gait Notes",
    },

    // 21 page Filed
    COGTensionBreathingPRControl: {
      type: "text",
      name: "COG-Tension-Breathing-PR-Control",
      label: "COG-Tension-Breathing-PR Control",
      errorMsg: "COG-Tension-Breathing-PR Control is a required field.",
      value: "COG-Tension-Breathing-PR-Control",
    },
    COGTensionBreathingPR: {
      type: "text",
      name: "COG-Tension-Breathing-PR",
      label: "COG-Tension-Breathing-PR",
      errorMsg: "COG-Tension-Breathing-PR is a required field.",
      value: "COG-Tension-Breathing-PR",
    },
    RombergTestControl: {
      type: "text",
      name: "Romberg Test-Control",
      label: "Romberg Test Control",
      errorMsg: "Romberg Test Control is a required field.",
      value: "Romberg Test-Control",
    },
    RombergTest: {
      type: "text",
      name: "Romberg Test",
      label: "Romberg Test",
      errorMsg: "Romberg Test is a required field.",
      value: "Romberg Test",
    },
    StandingHOHPTBothControl: {
      type: "text",
      name: "Standing-HOH-PT-Both-Control",
      label: "Standing-HOH-PT-Both Control",
      errorMsg: "Standing-HOH-PT-Both Control is a required field.",
      value: "Standing-HOH-PT-Both-Control",
    },
    StandingHOHPTBoth: {
      type: "text",
      name: "Standing-HOH-PT-Both",
      label: "Standing-HOH-PT-Both",
      errorMsg: "Standing-HOH-PT-Both is a required field.",
      value: "Standing-HOH-PT-Both",
    },
    HoHminus: {
      type: "checkbox",
      name: "HoH(-)",
      label: "HoH(-)",
      errorMsg: "HoH(-) is a required field.",
      value: "HoH(-)",
    },
    HoHplusone: {
      type: "checkbox",
      name: "HoH(+1)",
      label: "HoH(+1)",
      errorMsg: "HoH(+1) is a required field.",
      value: "HoH(+1)",
    },
    HoHplustwo: {
      type: "checkbox",
      name: "HoH(+2)",
      label: "HoH(+2)",
      errorMsg: "HoH(+2) is a required field.",
      value: "HoH(+2)",
    },
    HoHplusthree: {
      type: "checkbox",
      name: "HoH(+3)",
      label: "HoH(+3)",
      errorMsg: "HoH(+3) is a required field.",
      value: "HoH(+3)",
    },
    HoHOcc: {
      type: "checkbox",
      name: "HoHOcc",
      label: "HoHOcc",
      errorMsg: "HoHOcc is a required field.",
      value: "HoHOcc",
    },
    HoHC: {
      type: "checkbox",
      name: "HoHC",
      label: "HoHC",
      errorMsg: "HoHC is a required field.",
      value: "HoHC",
    },
    HoHSh: {
      type: "checkbox",
      name: "HoHSh",
      label: "HoHSh",
      errorMsg: "HoHSh is a required field.",
      value: "HoHSh",
    },
    HoHSc: {
      type: "checkbox",
      name: "HoHSc",
      label: "HoHSc",
      errorMsg: "HoHSc is a required field.",
      value: "HoHSc",
    },
    HoHT1: {
      type: "checkbox",
      name: "HoHT1",
      label: "HoHT1",
      errorMsg: "HoHT1 is a required field.",
      value: "HoHT1",
    },
    HoHT: {
      type: "checkbox",
      name: "HoHT",
      label: "HoHT",
      errorMsg: "HoHT is a required field.",
      value: "HoHT",
    },
    HoHMT: {
      type: "checkbox",
      name: "HoHMT",
      label: "HoHMT",
      errorMsg: "HoHMT is a required field.",
      value: "HoHMT",
    },
    HoHL: {
      type: "checkbox",
      name: "HoHL",
      label: "HoHL",
      errorMsg: "HoHL is a required field.",
      value: "HoHL",
    },
    HoHP: {
      type: "checkbox",
      name: "HoHP",
      label: "HoHP",
      errorMsg: "HoHP is a required field.",
      value: "HoHP",
    },
    HoHSa: {
      type: "checkbox",
      name: "HoHSa",
      label: "HoHSa",
      errorMsg: "HoHSa is a required field.",
      value: "HoHSa",
    },
    HoHH: {
      type: "checkbox",
      name: "HoHH",
      label: "HoHH",
      errorMsg: "HoHH is a required field.",
      value: "HoHH",
    },
    HoHK: {
      type: "checkbox",
      name: "HoHK",
      label: "HoHK",
      errorMsg: "HoHK is a required field.",
      value: "HoHK",
    },
    HoHA: {
      type: "checkbox",
      name: "HoHA",
      label: "HoHA",
      errorMsg: "HoHA is a required field.",
      value: "HoHA",
    },
    PTminus: {
      type: "checkbox",
      name: "PT(-)",
      label: "PT(-)",
      errorMsg: "PT(-) is a required field.",
      value: "PT(-)",
    },
    PTplusone: {
      type: "checkbox",
      name: "PT(+1)",
      label: "PT(+1)",
      errorMsg: "PT(+1) is a required field.",
      value: "PT(+1)",
    },
    PTplustwo: {
      type: "checkbox",
      name: "PT(+2)",
      label: "PT(+2)",
      errorMsg: "PT(+2) is a required field.",
      value: "PT(+2)",
    },
    PTplusthree: {
      type: "checkbox",
      name: "PT(+3)",
      label: "PT(+3)",
      errorMsg: "PT(+3) is a required field.",
      value: "PT(+3)",
    },
    PTOcc: {
      type: "checkbox",
      name: "PTOcc",
      label: "PTOcc",
      errorMsg: "PTOcc is a required field.",
      value: "PTOcc",
    },
    PTC: {
      type: "checkbox",
      name: "PTC",
      label: "PTC",
      errorMsg: "PTC is a required field.",
      value: "PTC",
    },
    PTSh: {
      type: "checkbox",
      name: "PTSh",
      label: "PTSh",
      errorMsg: "PTSh is a required field.",
      value: "PTSh",
    },
    PTSc: {
      type: "checkbox",
      name: "PTSc",
      label: "PTSc",
      errorMsg: "PTSc is a required field.",
      value: "PTSc",
    },
    PTT1: {
      type: "checkbox",
      name: "PTT1",
      label: "PTT1",
      errorMsg: "PTT1 is a required field.",
      value: "PTT1",
    },
    PTT: {
      type: "checkbox",
      name: "PTT",
      label: "PTT",
      errorMsg: "PTT is a required field.",
      value: "PTT",
    },
    PTMT: {
      type: "checkbox",
      name: "PTMT",
      label: "PTMT",
      errorMsg: "PTMT is a required field.",
      value: "PTMT",
    },
    PTL: {
      type: "checkbox",
      name: "PTL",
      label: "PTL",
      errorMsg: "PTL is a required field.",
      value: "PTL",
    },
    PTP: {
      type: "checkbox",
      name: "PTP",
      label: "PTP",
      errorMsg: "PTP is a required field.",
      value: "PTP",
    },
    PTSa: {
      type: "checkbox",
      name: "PTSa",
      label: "PTSa",
      errorMsg: "PTSa is a required field.",
      value: "PTSa",
    },
    PTH: {
      type: "checkbox",
      name: "PTH",
      label: "PTH",
      errorMsg: "PTH is a required field.",
      value: "PTH",
    },
    PTK: {
      type: "checkbox",
      name: "PTK",
      label: "PTK",
      errorMsg: "PTK is a required field.",
      value: "PTK",
    },
    PTA: {
      type: "checkbox",
      name: "PTA",
      label: "PTA",
      errorMsg: "PTA is a required field.",
      value: "PTA",
    },
    Bothminus: {
      type: "checkbox",
      name: "Both(-)",
      label: "Both(-)",
      errorMsg: "Both(-) is a required field.",
      value: "Both(-)",
    },
    Bothplusone: {
      type: "checkbox",
      name: "Both(+1)",
      label: "Both(+1)",
      errorMsg: "Both(+1) is a required field.",
      value: "Both(+1)",
    },
    Bothplustwo: {
      type: "checkbox",
      name: "Both(+2)",
      label: "Both(+2)",
      errorMsg: "Both(+2) is a required field.",
      value: "Both(+2)",
    },
    Bothplusthree: {
      type: "checkbox",
      name: "Both(+3)",
      label: "Both(+3)",
      errorMsg: "Both(+3) is a required field.",
      value: "Both(+3)",
    },
    BothOcc: {
      type: "checkbox",
      name: "BothOcc",
      label: "BothOcc",
      errorMsg: "BothOcc is a required field.",
      value: "BothOcc",
    },
    BothC: {
      type: "checkbox",
      name: "BothC",
      label: "BothC",
      errorMsg: "BothC is a required field.",
      value: "BothC",
    },
    BothSh: {
      type: "checkbox",
      name: "BothSh",
      label: "BothSh",
      errorMsg: "BothSh is a required field.",
      value: "BothSh",
    },
    BothSc: {
      type: "checkbox",
      name: "BothSc",
      label: "BothSc",
      errorMsg: "BothSc is a required field.",
      value: "BothSc",
    },
    BothT1: {
      type: "checkbox",
      name: "BothT1",
      label: "BothT1",
      errorMsg: "BothT1 is a required field.",
      value: "BothT1",
    },
    BothT: {
      type: "checkbox",
      name: "BothT",
      label: "BothT",
      errorMsg: "BothT is a required field.",
      value: "BothT",
    },
    BothMT: {
      type: "checkbox",
      name: "BothMT",
      label: "BothMT",
      errorMsg: "BothMT is a required field.",
      value: "BothMT",
    },
    BothL: {
      type: "checkbox",
      name: "BothL",
      label: "BothL",
      errorMsg: "BothL is a required field.",
      value: "BothL",
    },
    BothP: {
      type: "checkbox",
      name: "BothP",
      label: "BothP",
      errorMsg: "BothP is a required field.",
      value: "BothP",
    },
    BothSa: {
      type: "checkbox",
      name: "BothSa",
      label: "BothSa",
      errorMsg: "BothSa is a required field.",
      value: "BothSa",
    },
    BothH: {
      type: "checkbox",
      name: "BothH",
      label: "BothH",
      errorMsg: "BothH is a required field.",
      value: "BothH",
    },
    BothK: {
      type: "checkbox",
      name: "BothK",
      label: "BothK",
      errorMsg: "BothK is a required field.",
      value: "BothK",
    },
    BothA: {
      type: "checkbox",
      name: "BothA",
      label: "BothA",
      errorMsg: "BothA is a required field.",
      value: "BothA",
    },
    CDHypo: {
      type: "checkbox",
      name: "CDHypo",
      label: "CDHypo",
      errorMsg: "CDHypo is a required field.",
      value: "CDHypo",
    },
    CDHyper: {
      type: "checkbox",
      name: "CDHyper",
      label: "CDHyper",
      errorMsg: "CDHyper is a required field.",
      value: "CDHyper",
    },
    CDOcc: {
      type: "checkbox",
      name: "CDOcc",
      label: "CDOcc",
      errorMsg: "CDOcc is a required field.",
      value: "CDOcc",
    },
    CDC: {
      type: "checkbox",
      name: "CDC",
      label: "CDC",
      errorMsg: "CDC is a required field.",
      value: "CDC",
    },
    CDSh: {
      type: "checkbox",
      name: "CDSh",
      label: "CDSh",
      errorMsg: "CDSh is a required field.",
      value: "CDSh",
    },
    CDSc: {
      type: "checkbox",
      name: "CDSc",
      label: "CDSc",
      errorMsg: "CDSc is a required field.",
      value: "CDSc",
    },
    CDT1: {
      type: "checkbox",
      name: "CDT1",
      label: "CDT1",
      errorMsg: "CDT1 is a required field.",
      value: "CDT1",
    },
    CDT: {
      type: "checkbox",
      name: "CDT",
      label: "CDT",
      errorMsg: "CDT is a required field.",
      value: "CDT",
    },
    CDMT: {
      type: "checkbox",
      name: "CDMT",
      label: "CDMT",
      errorMsg: "CDMT is a required field.",
      value: "CDMT",
    },
    CDL: {
      type: "checkbox",
      name: "CDL",
      label: "CDL",
      errorMsg: "CDL is a required field.",
      value: "CDL",
    },
    CDP: {
      type: "checkbox",
      name: "CDP",
      label: "CDP",
      errorMsg: "CDP is a required field.",
      value: "CDP",
    },
    CDSa: {
      type: "checkbox",
      name: "CDSa",
      label: "CDSa",
      errorMsg: "CDSa is a required field.",
      value: "CDSa",
    },
    CDH: {
      type: "checkbox",
      name: "CDH",
      label: "CDH",
      errorMsg: "CDH is a required field.",
      value: "CDH",
    },
    CDK: {
      type: "checkbox",
      name: "CDK",
      label: "CDK",
      errorMsg: "CDK is a required field.",
      value: "CDK",
    },
    CDA: {
      type: "checkbox",
      name: "CDA",
      label: "CDA",
      errorMsg: "CDA is a required field.",
      value: "CDA",
    },
    StandingGoalPostsControl: {
      type: "text",
      name: "Standing-goal-posts-control",
      label: "Standing-goal-posts control",
      errorMsg: "Standing-goal-posts control is a required field.",
      value: "Standing-goal-posts control",
    },
    StandingGoalPosts: {
      type: "text",
      name: "Standing-goal-posts",
      label: "Standing-goal-posts",
      errorMsg: "Standing-goal-posts is a required field.",
      value: "Standing-goal-posts",
    },
    StandingTorsoRotationControl: {
      type: "text",
      name: "Standing-torso-rotation-control",
      label: "Standing-torso-rotation-control",
      errorMsg: "Standing-torso-rotation-control is a required field.",
      value: "Standing-torso-rotation-control",
    },
    StandingTorsoRotation: {
      type: "text",
      name: "Standing-torso-rotation",
      label: "Standing-torso-rotation",
      errorMsg: "Standing-torso-rotation is a required field.",
      value: "Standing-torso-rotation",
    },
    StandingWallTestControl: {
      type: "text",
      name: "Standing-wall-test-control",
      label: "Standing-wall-test-control",
      errorMsg: "Standing-wall-test-control is a required field.",
      value: "Standing-wall-test-control",
    },
    StandingWallTest: {
      type: "text",
      name: "Standing-wall-test",
      label: "Standing-wall-test",
      errorMsg: "Standing-wall-test is a required field.",
      value: "Standing-wall-test",
    },
    StandingWallTestwHOHPTBothControl: {
      type: "text",
      name: "Standing-Wall-Test-w/-HOH-PT-Both-Control",
      label: "Standing Wall Test w/ HOH, PT, Both Control",
      errorMsg: "Standing Wall Test w/ HOH, PT, Both Control is a required field.",
      value: "Standing Wall Test w/ HOH, PT, Both Control",
    },
    StandingWallTestwHOHPTBoth: {
      type: "text",
      name: "Standing-Wall-Test-w/-HOH-PT-Both",
      label: "Standing Wall Test w/ HOH, PT, Both",
      errorMsg: "Standing Wall Test w/ HOH, PT, Both is a required field.",
      value: "Standing Wall Test w/ HOH, PT, Both",
    },
    StandingWallAngelsControl: {
      type: "text",
      name: "Standing-Wall-Angels-Control",
      label: "Standing-goal-posts-Control",
      errorMsg: "Standing-goal-posts-Control is a required field.",
      value: "Standing-goal-posts-Control",
    },
    StandingWallAngels: {
      type: "text",
      name: "Standing-Wall-Angels",
      label: "Standing-goal-posts",
      errorMsg: "Standing-goal-posts is a required field.",
      value: "Standing-goal-posts",
    },
    StandingWallLateralBendsReachControl: {
      type: "text",
      name: "Standing-Wall-Lateral-Bends/Reach-Control",
      label: "Standing-Wall-Lateral-Bends/Reach-Control",
      errorMsg: "Standing-Wall-Lateral-Bends/Reach-Control is a required field.",
      value: "Standing-Wall-Lateral-Bends/Reach-Control",
    },
    StandingWallLateralBendsReach: {
      type: "text",
      name: "Standing-Wall-Lateral-Bends/Reach",
      label: "Standing-Wall-Lateral-Bends/Reach",
      errorMsg: "Standing-Wall-Lateral-Bends/Reach is a required field.",
      value: "Standing-Wall-Lateral-Bends/Reach",
    },
    StandingNeckROMControl: {
      type: "text",
      name: "Standing-Neck-ROM-Control",
      label: "Standing-Neck-ROM-Control",
      errorMsg: "Standing-Neck-ROM-Control is a required field.",
      value: "Standing-Neck-ROM-Control",
    },
    StandingNeckROM: {
      type: "text",
      name: "Standing-Neck-ROM",
      label: "Standing-Neck-ROM",
      errorMsg: "Standing-Neck-ROM is a required field.",
      value: "Standing-Neck-ROM",
    },
    JawOpeningandLateralDeviationControl: {
      type: "text",
      name: "Jaw-Opening and Lateral-Deviation Control",
      label: "Jaw-Opening and Lateral-Deviation Control",
      errorMsg: "Jaw-Opening and Lateral-Deviation Control is a required field.",
      value: "Jaw-Opening and Lateral-Deviation Control",
    },
    JawOpeningandLateralDeviation: {
      type: "text",
      name: "Jaw-Opening and Lateral-Deviation",
      label: "Jaw-Opening and Lateral-Deviation",
      errorMsg: "Jaw-Opening and Lateral-Deviation is a required field.",
      value: "Jaw-Opening and Lateral-Deviation",
    },
    GilletSIJFunctionTestControl: {
      type: "text",
      name: "Gillet-SIJ-Function-Test-Control",
      label: "Gillet-SIJ-Function-Test-Control",
      errorMsg: "Gillet-SIJ-Function-Control is a required field.",
      value: "Gillet-SIJ-Function-Test-Control",
    },
    GilletSIJFunctionTest: {
      type: "text",
      name: "Gillet-SIJ-Function-Test",
      label: "Gillet-SIJ-Function-Test",
      errorMsg: "Gillet-SIJ-Function-Test is a required field.",
      value: "Gillet-SIJ-Function-Test",
    },
    StandingStorkWalksControl: {
      type: "text",
      name: "Standing-Stork-Walks-Control",
      label: "Standing-Stork-Walks-Control",
      errorMsg: "Standing-Stork-Walks-Control is a required field.",
      value: "Standing-Stork-Walks-Control",
    },
    StandingStorkWalks: {
      type: "text",
      name: "Standing-Stork-Walks",
      label: "Standing-Stork-Walks",
      errorMsg: "Standing-Stork-Walks is a required field.",
      value: "Standing-Stork-Walks",
    },
    TrendelenburgTestControl: {
      type: "text",
      name: "Trendelenburg-Test-Control",
      label: "Trendelenburg-Test-Control",
      errorMsg: "Trendelenburg-Test-Control is a required field.",
      value: "Trendelenburg-Test-Control",
    },
    TrendelenburgTest: {
      type: "text",
      name: "Trendelenburg-Test",
      label: "Trendelenburg-Test",
      errorMsg: "Trendelenburg-Test is a required field.",
      value: "Trendelenburg-Test",
    },

    StepUpsControl: {
      type: "text",
      name: "Step-Ups-Control",
      label: "Step Ups-Control",
      errorMsg: "Step Ups Control is a required field.",
      value: "Step Ups Control",
    },
    StepUps: {
      type: "text",
      name: "Step Ups",
      label: "Step Ups",
      errorMsg: "Step Ups is a required field.",
      value: "Step Ups",
    },
    StandingToeTouchControl: {
      type: "text",
      name: "Standing-Toe-Touch-Control",
      label: "Standing-Toe-Touch-Control",
      errorMsg: "Standing-Toe-Touch-Control is a required field.",
      value: "Standing-Toe-Touch-Control",
    },
    StandingToeTouch: {
      type: "text",
      name: "StandingToeTouch",
      label: "StandingToeTouch",
      errorMsg: "StandingToeTouch is a required field.",
      value: "StandingToeTouch",
    },
    SquatControl: {
      type: "text",
      name: "Squat Control",
      label: "Squat Control",
      errorMsg: "Squat Control is a required field.",
      value: "Squat Control",
    },
    Squat: {
      type: "text",
      name: "Squat",
      label: "Squat",
      errorMsg: "Squat is a required field.",
      value: "Squat",
    },
    Lunges: {
      type: "text",
      name: "Lunges",
      label: "Lunges",
      errorMsg: "Lunges is a required field.",
      value: "Lunges",
    },
    LungesControl: {
      type: "text",
      name: "Lunges-Control",
      label: "Lunges-Control",
      errorMsg: "Lunges-Control is a required field.",
      value: "Lunges-Control",
    },
    SittingAnkleKneeCrossoverControl: {
      type: "text",
      name: "Sitting-Ankle-Knee-Crossover-Control",
      label: "Sitting-Ankle-Knee-Crossover-Control",
      errorMsg: "Sitting-Ankle-Knee-Crossover-Control is a required field.",
      value: "Sitting-Ankle-Knee-Crossover-Control",
    },
    SittingAnkleKneeCrossover: {
      type: "text",
      name: "Sitting-Ankle-Knee-Crossover",
      label: "Sitting-Ankle-Knee-Crossover",
      errorMsg: "Sitting-Ankle-Knee-Crossover is a required field.",
      value: "Sitting-Ankle-Knee-Crossover",
    },
    SittingCatsandDogsControl: {
      type: "text",
      name: "Sitting-Cats and Dogs Control",
      label: "Sitting-Cats and Dogs Control",
      errorMsg: "Sitting-Cats and Dogs Control is a required field.",
      value: "Sitting-Cats and Dogs Control",
    },
    SittingCatsandDogs: {
      type: "text",
      name: "Sitting-Cats and Dogs",
      label: "Sitting-Cats and Dogs",
      errorMsg: "Sitting-Cats and Dogs is a required field.",
      value: "Sitting-Cats and Dogs",
    },
    SittingSingleHipLiftsControl: {
      type: "text",
      name: "Sitting-Single-Hip-Lifts-Control",
      label: "Sitting-Single-Hip-Lifts-Control",
      errorMsg: "Sitting-Single-Hip-Lifts-Control is a required field.",
      value: "Sitting-Single-Hip-Lifts-Control",
    },
    SittingSingleHipLifts: {
      type: "text",
      name: "Sitting-Single-Hip-Lifts",
      label: "Sitting-Single-Hip-Lifts",
      errorMsg: "Sitting-Single-Hip-Lifts is a required field.",
      value: "Sitting-Single-Hip-Lifts",
    },
    HooklyingPositionControl: {
      type: "text",
      name: "Hooklying-Position-Control",
      label: "Hooklying-Position-Control",
      errorMsg: "Hooklying-Position-Control is a required field.",
      value: "Hooklying-Position-Control",
    },
    HooklyingPosition: {
      type: "text",
      name: "HooklyingPosition",
      label: "HooklyingPosition",
      errorMsg: "HooklyingPosition is a required field.",
      value: "HooklyingPosition",
    },
    HooklyingLegRotationsControl: {
      type: "text",
      name: "Hooklying-Leg-Rotations-Control",
      label: "Hooklying-Leg-Rotations-Control",
      errorMsg: "Hooklying-Leg-Rotations-Control is a required field.",
      value: "Hooklying-Leg-Rotations-Control",
    },
    HooklyingLegRotations: {
      type: "text",
      name: "Hooklying-Leg-Rotations",
      label: "Hooklying-Leg-Rotations",
      errorMsg: "Hooklying-Leg-Rotations is a required field.",
      value: "Hooklying-Leg-Rotations",
    },
    LyingSupineControl: {
      type: "text",
      name: "Lying Supine-control",
      label: "Lying Supine-control",
      errorMsg: "Lying Supine-control is a required field.",
      value: "Lying Supine-control",
    },
    LyingSupine: {
      type: "text",
      name: "Lying-Supine",
      label: "Lying-Supine",
      errorMsg: "Lying-Supine is a required field.",
      value: "Lying-Supine",
    },
    SBControl: {
      type: "text",
      name: "SB-Control",
      label: "SB-Control",
      errorMsg: "SB-Control is a required field.",
      value: "SB-Control",
    },
    SB: {
      type: "text",
      name: "SB",
      label: "SB",
      errorMsg: "SB is a required field.",
      value: "SB",
    },
    IMLSIJTestControl: {
      type: "text",
      name: "IML-SIJ-Test-Control",
      label: "IML-SIJ-Test-Control",
      errorMsg: "IML-SIJ-Test-Control is a required field.",
      value: "IML-SIJ-Test-Control",
    },
    IMLSIJTest: {
      type: "text",
      name: "IML-SIJ-Test",
      label: "IML-SIJ-Test",
      errorMsg: "IML-SIJ-Test is a required field.",
      value: "IML-SIJ-Test",
    },
    LyingProneControl: {
      type: "text",
      name: "Lying-Prone-Control",
      label: "Lying-Prone-Control",
      errorMsg: "Lying-Prone-Control is a required field.",
      value: "Lying-Prone-Control",
    },
    LyingProne: {
      type: "text",
      name: "Lying-Prone",
      label: "Lying-Prone",
      errorMsg: "Lying-Prone is a required field.",
      value: "Lying-Prone",
    },
    ProneSingleLegLiftsControl: {
      type: "text",
      name: "Prone-Single-Leg-Lifts-Control",
      label: "Prone-Single-Leg-Lifts-Control",
      errorMsg: "Prone-Single-Leg-Lifts-Control is a required field.",
      value: "Prone-Single-Leg-Lifts-Control",
    },
    ProneSingleLegLifts: {
      type: "text",
      name: "Prone-Single-Leg-Lifts",
      label: "Prone-Single-Leg-Lifts",
      errorMsg: "Prone-Single-Leg-Lifts is a required field.",
      value: "Prone-Single-Leg-Lifts",
    },
    SupineSingleLegActiveBridgesControl: {
      type: "text",
      name: "Supine-single-leg-active-bridges-Control",
      label: "Supine-single-leg-active-bridges-Control",
      errorMsg: "Supine-single-leg-active-bridges-Control is a required field.",
      value: "Supine-single-leg-active-bridges-Control",
    },
    SupineSingleLegActiveBridges: {
      type: "text",
      name: "Supine-single-leg-active-bridges",
      label: "Supine-single-leg-active-bridges",
      errorMsg: "Supine-single-leg-active-bridges is a required field.",
      value: "Supine-single-leg-active-bridges",
    },

    // 22 page
    HookCervicalSitupsControl: {
      type: "text",
      name: "Hook-Cervical-Situps-Control",
      label: "Hook-Cervical-Situps-Control",
      errorMsg: "Hook-Cervical-Situps-Control is a required field.",
      value: "Hook-Cervical-Situps-Control",
    },
    HookCervicalSitups: {
      type: "text",
      name: "Hook-Cervical-Situps",
      label: "Hook-Cervical-Situps",
      errorMsg: "Hook-Cervical-Situps is a required field.",
      value: "Hook-Cervical-Situps",
    },
    HookREPControl: {
      type: "text",
      name: "Hook-REP-Control ",
      label: "Hook-REP-Control ",
      errorMsg: "Hook-REP-Control  is a required field.",
      value: "Hook-REP-Control ",
    },
    HookREP: {
      type: "text",
      name: "Hook-REP ",
      label: "Hook-REP ",
      errorMsg: "Hook-REP  is a required field.",
      value: "Hook-REP ",
    },
    PUpPosittoScapControl: {
      type: "text",
      name: "PUpPosittoScap-Control",
      label: "PUpPosittoScap-Control",
      errorMsg: "PUpPosittoScap-Control is a required field.",
      value: "PUpPosittoScap-Control",
    },
    PUpPosittoScap: {
      type: "text",
      name: "PUpPosittoScap",
      label: "PUpPosittoScap",
      errorMsg: "PUpPosittoScap is a required field.",
      value: "PUpPosittoScap",
    },
    BreathingControl: {
      type: "text",
      name: "Breathing-Control",
      label: "Breathing-Control",
      errorMsg: "Breathing-Control is a required field.",
      value: "Breathing-Control",
    },
    Breathing: {
      type: "text",
      name: "Breathing",
      label: "Breathing",
      errorMsg: "Breathing is a required field.",
      value: "Breathing",
    },
    SideBridgeonElbowFtControl: {
      type: "text",
      name: "Side-Bridge-on-Elbow-Ft-Control",
      label: "Side-Bridge-on-Elbow-Ft-Control",
      errorMsg: "Side-Bridge-on-Elbow-Ft-Control is a required field.",
      value: "Side-Bridge-on-Elbow-Ft-Control",
    },
    SideBridgeonElbowFt: {
      type: "text",
      name: "Side-Bridge-on-Elbow-Ft",
      label: "Side-Bridge-on-Elbow-Ft",
      errorMsg: "Side-Bridge-on-Elbow-Ft is a required field.",
      value: "Side-Bridge-on-Elbow-Ft",
    },
    SittingSideBendsArmsCrossedControl: {
      type: "text",
      name: "Sitting-SideBends-Arms-Crossed-Control",
      label: "Sitting-SideBends-Arms-Crossed-Control",
      errorMsg: "Sitting-SideBends-Arms-Crossed-Control is a required field.",
      value: "Sitting-SideBends-Arms-Crossed-Control",
    },
    SittingSideBendsArmsCrossed: {
      type: "text",
      name: "Sitting-SideBends-Arms-Crossed",
      label: "Sitting-SideBends-Arms-Crossed",
      errorMsg: "Sitting-SideBends-Arms-Crossed is a required field.",
      value: "Sitting-SideBends-Arms-Crossed",
    },
    SupineLegLiftsintoAbdControl: {
      type: "text",
      name: "Supine-LegLiftsin-to-Abd-Control",
      label: "Supine-LegLiftsin-to-Abd-Control",
      errorMsg: "Supine-LegLiftsin-to-Abd-Control is a required field.",
      value: "Supine-LegLiftsin-to-Abd-Control",
    },
    SupineLegLiftsintoAbd: {
      type: "text",
      name: "Supine-LegLiftsin-to-Abd",
      label: "Supine-LegLiftsin-to-Abd",
      errorMsg: "Supine-LegLiftsin-to-Abd is a required field.",
      value: "Supine-LegLiftsin-to-Abd",
    },
    SidelyingInnerThighLiftsControl: {
      type: "text",
      name: "Sidelying-Inner-ThighLifts-Control",
      label: "Sidelying-Inner-ThighLifts-Control",
      errorMsg: "Sidelying-Inner-ThighLifts-Control is a required field.",
      value: "Sidelying-Inner-ThighLifts-Control",
    },
    SidelyingInnerThighLifts: {
      type: "text",
      name: "Sidelying-Inner-ThighLifts",
      label: "Sidelying-Inner-ThighLifts",
      errorMsg: "Sidelying-Inner-ThighLifts is a required field.",
      value: "Sidelying-Inner-ThighLifts",
    },
    ProneForefootBlockSqueezesControl: {
      type: "text",
      name: "ProneFore-foot-Block-Squeezes-Control",
      label: "ProneFore-foot-Block-Squeezes-Control",
      errorMsg: "ProneFore-foot-Block-Squeezes-Control is a required field.",
      value: "ProneFore-foot-Block-Squeezes-Control",
    },
    ProneForefootBlockSqueezes: {
      type: "text",
      name: "ProneFore-foot-Block-Squeezes",
      label: "ProneFore-foot-Block-Squeezes",
      errorMsg: "ProneFore-foot-Block-Squeezes is a required field.",
      value: "ProneFore-foot-Block-Squeezes",
    },
    HookWallAbAdWideControl: {
      type: "text",
      name: "Hook-Wall-Ab-Ad-Wide-Control",
      label: "Hook-Wall-Ab-Ad-Wide-Control",
      errorMsg: "Hook-Wall-Ab-Ad-Wide-Control is a required field.",
      value: "Hook-Wall-Ab-Ad-Wide-Control",
    },
    HookWallAbAdWide: {
      type: "text",
      name: "Hook-Wall-Ab-Ad-Wide",
      label: "Hook-Wall-Ab-Ad-Wide",
      errorMsg: "Hook-Wall-Ab-Ad-Wide is a required field.",
      value: "Hook-Wall-Ab-Ad-Wide",
    },
    AGKCNotes: {
      type: "text",
      name: "AGKC-Notes",
      label: "AGKC-Notes",
      errorMsg: "AGKC-Notes is a required field.",
      value: "AGKC-Notes",
    },
  },
};

export default form;
