import checkout from "layouts/pages/DoctorSoapFrom/schemas/form";

const {
  formField: {
    firstName,
    name,
    lastName,
    company,
    email,
    address1,
    address2,
    country,
    dominantHand,
    city,
    zip,
    EmergencyPhoneNumber,
    EmergencyName,
    EmergencyRelation,
    publicEmail,
    bio,
    language,
    MaritalStatus,
    gender,
    Cellphonenumber,
    Cellphonenumber1,
    phonenumbrCell,
    Cellphonenumber4,
    Cellphonenumber3,
    Cellphonenumber2,
    Cellphonenumber0,
    CellphonenumberA,
    Workphonenumber,
    Phone1,
    Phone2,
    Phone3,
    Phone4,
    Phone,
    lastSectionPhone,
    DOB,
    dob,
    SocialSecurityNumber,
    NumberofChildren,
    Occupation,
    UserWorkHours,
    UserProfilePIC,
    state,
    height,
    weight,
    TODAYDATE,
    address,
    pincode,
    DL,
    Dateoflossaccident,

    PractitionerName,
    NPI,
    TIN,
    hourlyRate,

    PatientName,
    newPatient,
    patientFollowUp,
    patientNewComplaint,
    visitNumber,
    patienttodaysDate,
    patientNextReExam,
    patientDob,
    patientAge,
    patientHeight,
    patientHeightNi,
    patientWeight,
    patientWeightNi,
    patientHtnYes,
    patientHtnNo,
    patientCautions,

    isImproved,
    isNoChanges,
    isRegressed,
    isFlareUp,
    additionalAssessment,

    doe,
    isVitals,
    bp,
    mmHG,
    pulse,
    temp,
    rr,
    spo2,
    isNeurologicalExam,
    isCranialNerves,
    cranialNerves,
    isRombergs,
    rombergs,
    isDiadichodyskinesia,
    diadichodyskinesia,
    isDermatomes,
    dermatomes,
    isMyotomes,
    myotomes,
    isDtrs,
    dtrs,
    isPathological,
    pathological,
    isHomans,
    homans,

    flexion60_exam,
    flexion60_pain,
    flexion60_noPain,
    flexion60_location,
    flexion60_left,
    flexion60_right,
    cervicalRegionalNotes1,
    cervicalRegionalNotes2,

    humanSidebodyPoints,
    humanexcerciseone,
    leftshoulderdesc,
    rightshoulderdesc,
    leftthoricdesc,
    rightthoricdesc,
    leftpelvisdesc,
    rightpelvisdesc,
    lefthipdesc,
    righthipdesc,
    leftkneedesc,
    rightkneedesc,
    leftankledesc,
    rightankledesc,
    leftheaddesc,
    rightheaddesc,
    HumanFullbodyPoints,
    humanexcerciseTwo,
    ClientName,
    Chiefcomplaint,
    Painlevel,
    Practitioner,
    Date,
    PhysicianClearance,

    // 20page filed
    CrossPatternCONTRAIPSIControl,
    CrossPatternCONTRAIPSI,
    COGLoadsRLControl,
    COGLoadsRL,
    RLKnIRERControl,
    RLKnIRER,
    RLHipELEVControl,
    RLHipELEV,
    RLHipLATShiftControl,
    RLHipLATShift,
    RLHipFLEXEXTdecrControl,
    RLHipFLEXEXTdecr,
    RLHipROTforFLEXEXTControl,
    RLHipROTforFLEXEXT,
    RLPelvicFLEXEXTdecrControl,
    RLPelvicFLEXEXTdecr,
    RLPelvicROTIncrDecrControl,
    RLPelvicROTIncrDecr,
    TorsoCROTControl,
    TorsoCROT,
    TorsoOffsetRLControl,
    TorsoOffsetRL,
    TorsoLATFLEXControl,
    TorsoLATFLEX,
    HATLoadLRControl,
    HATLoadLR,
    RLFootIRERControl,
    RLFootIRER,
    RLCductIRERControl,
    RLCductIRER,
    RLArmSwingControl,
    RLArmSwing,
    RLShFLEXEXTControl,
    RLShFLEXEXT,
    RLArmCarryingAngleIncrDecrControl,
    RLArmCarryingAngleIncrDecr,
    HOHControl,
    HOH,
    HBBControl,
    HBB,
    DFControl,
    DF,
    Gaitnotes,

    // 21 page Filed
    COGTensionBreathingPRControl,
    COGTensionBreathingPR,
    RombergTestControl,
    RombergTest,
    StandingHOHPTBothControl,
    StandingHOHPTBoth,
    HoHminus,
    HoHplusone,
    HoHplustwo,
    HoHplusthree,
    HoHOcc,
    HoHC,
    HoHSh,
    HoHSc,
    HoHT1,
    HoHT,
    HoHMT,
    HoHL,
    HoHP,
    HoHSa,
    HoHH,
    HoHK,
    HoHA,
    PTminus,
    PTplusone,
    PTplustwo,
    PTplusthree,
    PTOcc,
    PTC,
    PTSh,
    PTSc,
    PTT1,
    PTT,
    PTMT,
    PTL,
    PTP,
    PTSa,
    PTH,
    PTK,
    PTA,
    Bothminus,
    Bothplusone,
    Bothplustwo,
    Bothplusthree,
    BothOcc,
    BothC,
    BothSh,
    BothSc,
    BothT1,
    BothT,
    BothMT,
    BothL,
    BothP,
    BothSa,
    BothH,
    BothK,
    BothA,
    CDHypo,
    CDHyper,
    CDOcc,
    CDC,
    CDSh,
    CDSc,
    CDT1,
    CDT,
    CDMT,
    CDL,
    CDP,
    CDSa,
    CDH,
    CDK,
    CDA,
    StandingGoalPostsControl,
    StandingGoalPosts,
    StandingTorsoRotationControl,
    StandingTorsoRotation,
    StandingWallTestControl,
    StandingWallTest,
    StandingWallTestwHOHPTBothControl,
    StandingWallTestwHOHPTBoth,
    StandingWallAngelsControl,
    StandingWallAngels,
    StandingWallLateralBendsReachControl,
    StandingWallLateralBendsReach,
    StandingNeckROMControl,
    StandingNeckROM,
    JawOpeningandLateralDeviationControl,
    JawOpeningandLateralDeviation,
    GilletSIJFunctionTestControl,
    GilletSIJFunctionTest,
    StandingStorkWalksControl,
    StandingStorkWalks,
    TrendelenburgTestControl,
    TrendelenburgTest,
    StepUpsControl,
    StepUps,
    StandingToeTouchControl,
    StandingToeTouch,
    SquatControl,
    Squat,
    LungesControl,
    Lunges,
    SittingAnkleKneeCrossoverControl,
    SittingAnkleKneeCrossover,
    SittingCatsandDogsControl,
    SittingCatsandDogs,
    SittingSingleHipLiftsControl,
    SittingSingleHipLifts,
    HooklyingPositionControl,
    HooklyingPosition,
    HooklyingLegRotationsControl,
    HooklyingLegRotations,
    LyingSupineControl,
    LyingSupine,
    SBControl,
    SB,
    IMLSIJTestControl,
    IMLSIJTest,
    LyingProneControl,
    LyingProne,
    ProneSingleLegLiftsControl,
    ProneSingleLegLifts,
    SupineSingleLegActiveBridgesControl,
    SupineSingleLegActiveBridges,

    // 22 page
    HookCervicalSitupsControl,
    HookCervicalSitups,
    HookREPControl,
    HookREP,
    PUpPosittoScapControl,
    PUpPosittoScap,
    BreathingControl,
    Breathing,
    SideBridgeonElbowFtControl,
    SideBridgeonElbowFt,
    SittingSideBendsArmsCrossedControl,
    SittingSideBendsArmsCrossed,
    SupineLegLiftsintoAbdControl,
    SupineLegLiftsintoAbd,
    SidelyingInnerThighLiftsControl,
    SidelyingInnerThighLifts,
    ProneForefootBlockSqueezesControl,
    ProneForefootBlockSqueezes,
    HookWallAbAdWideControl,
    HookWallAbAdWide,
    AGKCNotes,
  },
} = checkout;

const initialValues1 = {

  name:"",
  todayDate:"",


} 
const initialValues = {
  [dominantHand.name]: "",
  [firstName.name]: "",
  [name.name]: "",
  [lastName.name]: "",
  [company.name]: "",
  [email.name]: "",
  [DL.name]: "",
  [height.name]: "",
  [weight.name]: "",
  [address.name]: "",
  [pincode.name]: "",
  [address1.name]: "",
  [address2.name]: "",
  [city.name]: "",
  [zip.name]: "",
  [TODAYDATE.name]: "",
  [EmergencyPhoneNumber.name]: "",
  [EmergencyName.name]: "",
  [EmergencyRelation.name]: "",
  [publicEmail.name]: "",
  [bio.name]: "",
  [language.name]: "",
  [MaritalStatus.name]: "",
  [gender.name]: "",
  [Cellphonenumber1.name]: "",
  [phonenumbrCell.name] : "",
  [Cellphonenumber.name]: "",
  [Cellphonenumber4.name]: "",
  [Cellphonenumber3.name]: "",
  [Cellphonenumber2.name]: "",
  [Cellphonenumber0.name]: "",
  [CellphonenumberA.name]: "",
  [Workphonenumber.name]: "",
  [Phone1.name]: "",
  [lastSectionPhone.name]: "",
  [Phone2.name]: "",
  [Phone3.name]: "",
  [Phone4.name]: "",
  [Phone.name]: "",
  [UserProfilePIC.name]: "",
  [DOB.name]: "",
  [dob.name]: "",
  [SocialSecurityNumber.name]: "",
  [NumberofChildren.name]: "",
  [Occupation.name]: "",
  [UserWorkHours.name]: "",
  [state.name]: "",
  // [country.name]:"",
  [Dateoflossaccident.name]: "",

  [PractitionerName.name]: "",
  [NPI.name]: "",
  [TIN.name]: "",
  [hourlyRate.name]: "",

  [isImproved.name]: false,
  [isNoChanges.name]: false,
  [isRegressed.name]: false,
  [isFlareUp.name]: false,
  [additionalAssessment.name]: "",

  [doe.name]: "",
  [isVitals.name]: "",
  [bp.name]: "",
  [mmHG.name]: "",
  [pulse.name]: "",
  [temp.name]: "",
  [rr.name]: "",
  [spo2.name]: "",
  [isNeurologicalExam.name]: false,
  [isCranialNerves.name]: false,
  [cranialNerves.name]: "",
  [isRombergs.name]: false,
  [rombergs.name]: "",
  [isDiadichodyskinesia.name]: false,
  [diadichodyskinesia.name]: "",
  [isDermatomes.name]: false,
  [dermatomes.name]: "",
  [isMyotomes.name]: false,
  [myotomes.name]: "",
  [isDtrs.name]: false,
  [dtrs.name]: "",
  [isPathological.name]: false,
  [pathological.name]: "",
  [isHomans.name]: false,
  [homans.name]: "",

  [flexion60_exam.name]: "",
  [flexion60_pain.name]: false,
  [flexion60_noPain.name]: false,
  [flexion60_location.name]: "",
  [flexion60_left.name]: "",
  [flexion60_right.name]: "",

  [cervicalRegionalNotes1.name]: "",
  [cervicalRegionalNotes2.name]: "",

  [humanSidebodyPoints.name]: "",
  [humanexcerciseone.name]: "",
  [leftshoulderdesc.name]: "",
  [rightshoulderdesc.name]: "",
  [leftthoricdesc.name]: "",
  [rightthoricdesc.name]: "",
  [leftpelvisdesc.name]: "",
  [rightpelvisdesc.name]: "",
  [lefthipdesc.name]: "",
  [righthipdesc.name]: "",
  [leftkneedesc.name]: "",
  [rightkneedesc.name]: "",
  [leftankledesc.name]: "",
  [rightankledesc.name]: "",
  [leftheaddesc.name]: "",
  [rightheaddesc.name]: "",
  [HumanFullbodyPoints.name]: "",
  [humanexcerciseTwo.name]: "",
  [ClientName.name]: "",
  [Chiefcomplaint.name]: "",
  [Painlevel.name]: "",
  [Practitioner.name]: "",
  [Date.name]: "",
  [PhysicianClearance.name]: "",

  // 20 page filed
  [CrossPatternCONTRAIPSI.name]: "",
  [CrossPatternCONTRAIPSIControl.name]: "",
  [COGLoadsRL.name]: "",
  [COGLoadsRLControl.name]: "",
  [RLKnIRER.name]: "",
  [RLHipELEVControl.name]: "",
  [RLHipELEV.name]: "",
  [RLHipLATShiftControl.name]: "",
  [RLHipLATShift.name]: "",
  [RLHipFLEXEXTdecrControl.name]: "",
  [RLHipFLEXEXTdecr.name]: "",
  [RLHipROTforFLEXEXTControl.name]: "",
  [RLHipROTforFLEXEXT.name]: "",
  [RLPelvicFLEXEXTdecrControl.name]: "",
  [RLPelvicFLEXEXTdecr.name]: "",
  [RLPelvicROTIncrDecrControl.name]: "",
  [RLPelvicROTIncrDecr.name]: "",
  [TorsoCROTControl.name]: "",
  [TorsoCROT.name]: "",
  [TorsoOffsetRLControl.name]: "",
  [TorsoOffsetRL.name]: "",
  [TorsoLATFLEXControl.name]: "",
  [TorsoLATFLEX.name]: "",
  [HATLoadLRControl.name]: "",
  [HATLoadLR.name]: "",
  [RLFootIRERControl.name]: "",
  [RLFootIRER.name]: "",
  [RLCductIRERControl.name]: "",
  [RLCductIRER.name]: "",
  [RLArmSwingControl.name]: "",
  [RLArmSwing.name]: "",
  [RLShFLEXEXTControl.name]: "",
  [RLShFLEXEXT.name]: "",
  [RLArmCarryingAngleIncrDecrControl.name]: "",
  [RLArmCarryingAngleIncrDecr.name]: "",
  [HOHControl.name]: "",
  [HOH.name]: "",
  [HBBControl.name]: "",
  [HBB.name]: "",
  [DFControl.name]: "",
  [DF.name]: "",
  [Gaitnotes.name]: "",

  // 21 page Filed
  [COGTensionBreathingPRControl.name]: "",
  [COGTensionBreathingPR.name]: "",
  [RombergTestControl.name]: "",
  [RombergTest.name]: "",
  [StandingHOHPTBothControl.name]: "",
  [StandingHOHPTBoth.name]: "",
  [HoHminus.name]: false,
  [HoHplusone.name]: false,
  [HoHplustwo.name]: false,
  [HoHplusthree.name]: false,
  [HoHOcc.name]: false,
  [HoHC.name]: false,
  [HoHSh.name]: false,
  [HoHSc.name]: false,
  [HoHT1.name]: false,
  [HoHT.name]: false,
  [HoHMT.name]: false,
  [HoHL.name]: false,
  [HoHP.name]: false,
  [HoHSa.name]: false,
  [HoHH.name]: false,
  [HoHK.name]: false,
  [HoHA.name]: false,
  [PTminus.name]: false,
  [PTplusone.name]: false,
  [PTplustwo.name]: false,
  [PTplusthree.name]: false,
  [PTOcc.name]: false,
  [PTC.name]: false,
  [PTSh.name]: false,
  [PTSc.name]: false,
  [PTT1.name]: false,
  [PTT.name]: false,
  [PTMT.name]: false,
  [PTL.name]: false,
  [PTP.name]: false,
  [PTSa.name]: false,
  [PTH.name]: false,
  [PTK.name]: false,
  [PTA.name]: false,
  [Bothminus.name]: false,
  [Bothplusone.name]: false,
  [Bothplustwo.name]: false,
  [Bothplusthree.name]: false,
  [BothOcc.name]: false,
  [BothC.name]: false,
  [BothSh.name]: false,
  [BothSc.name]: false,
  [BothT1.name]: false,
  [BothT.name]: false,
  [BothMT.name]: false,
  [BothL.name]: false,
  [BothP.name]: false,
  [BothSa.name]: false,
  [BothH.name]: false,
  [BothK.name]: false,
  [BothA.name]: false,
  [CDHypo.name]: false,
  [CDHyper.name]: false,
  [CDOcc.name]: false,
  [CDC.name]: false,
  [CDSh.name]: false,
  [CDSc.name]: false,
  [CDT1.name]: false,
  [CDT.name]: false,
  [CDMT.name]: false,
  [CDL.name]: false,
  [CDP.name]: false,
  [CDSa.name]: false,
  [CDH.name]: false,
  [CDK.name]: false,
  [CDA.name]: false,
  [StandingGoalPostsControl.name]: "",
  [StandingGoalPosts.name]: "",
  [StandingTorsoRotationControl.name]: "",
  [StandingTorsoRotation.name]: "",
  [StandingWallTestControl.name]: "",
  [StandingWallTest.name]: "",
  [StandingWallTestwHOHPTBothControl.name]: "",
  [StandingWallTestwHOHPTBoth.name]: "",
  [StandingWallAngelsControl.name]: "",
  [StandingWallAngels.name]: "",
  [StandingWallLateralBendsReachControl.name]: "",
  [StandingWallLateralBendsReach.name]: "",
  [StandingNeckROMControl.name]: "",
  [StandingNeckROM.name]: "",
  [JawOpeningandLateralDeviationControl.name]: "",
  [JawOpeningandLateralDeviation.name]: "",
  [GilletSIJFunctionTestControl.name]: "",
  [GilletSIJFunctionTest.name]: "",
  [StandingStorkWalksControl.name]: "",
  [StandingStorkWalks.name]: "",
  [TrendelenburgTestControl.name]: "",
  [TrendelenburgTest.name]: "",
  [StepUpsControl.name]: "",
  [StepUps.name]: "",
  [StandingToeTouchControl.name]: "",
  [StandingToeTouch.name]: "",
  [SquatControl.name]: "",
  [Squat.name]: "",
  [LungesControl.name]: "",
  [Lunges.name]: "",
  [SittingAnkleKneeCrossoverControl.name]: "",
  [SittingAnkleKneeCrossover.name]: "",
  [SittingCatsandDogsControl.name]: "",
  [SittingCatsandDogs.name]: "",
  [SittingSingleHipLiftsControl.name]: "",
  [SittingSingleHipLifts.name]: "",
  [HooklyingPositionControl.name]: "",
  [HooklyingPosition.name]: "",
  [HooklyingLegRotationsControl.name]: "",
  [HooklyingLegRotations.name]: "",
  [LyingSupineControl.name]: "",
  [LyingSupine.name]: "",
  [SBControl.name]: "",
  [SB.name]: "",
  [IMLSIJTestControl.name]: "",
  [IMLSIJTest.name]: "",
  [LyingProneControl.name]: "",
  [LyingProne.name]: "",
  [ProneSingleLegLiftsControl.name]: "",
  [ProneSingleLegLifts.name]: "",
  [SupineSingleLegActiveBridgesControl.name]: "",
  [SupineSingleLegActiveBridges.name]: "",

  // 22 page
  [HookCervicalSitupsControl.name]: "",
  [HookCervicalSitups.name]: "",
  [HookREPControl.name]: "",
  [HookREP.name]: "",
  [PUpPosittoScapControl.name]: "",
  [PUpPosittoScap.name]: "",
  [BreathingControl.name]: "",
  [Breathing.name]: "",
  [SideBridgeonElbowFtControl.name]: "",
  [SideBridgeonElbowFt.name]: "",
  [SittingSideBendsArmsCrossedControl.name]: "",
  [SittingSideBendsArmsCrossed.name]: "",
  [SupineLegLiftsintoAbdControl.name]: "",
  [SupineLegLiftsintoAbd.name]: "",
  [SidelyingInnerThighLiftsControl.name]: "",
  [SidelyingInnerThighLifts.name]: "",
  [ProneForefootBlockSqueezesControl.name]: "",
  [ProneForefootBlockSqueezes.name]: "",
  [HookWallAbAdWideControl.name]: "",
  [HookWallAbAdWide.name]: "",
  [AGKCNotes.name]: "",

  [PatientName.name]: "",
  [newPatient.name]: false,
  [patientFollowUp.name]: false,
  [patientNewComplaint.name]: false,
  [visitNumber.name]: "",
  [patienttodaysDate.name]: "",
  [patientNextReExam.name]: "",
  [patientDob.name]: "",
  [patientAge.name]: "",
  [patientHeight.name]: "",
  [patientHeightNi.name]: false,
  [patientWeight.name]: "",
  [patientWeightNi.name]: false,
  [patientHtnYes.name]: false,
  [patientHtnNo.name]: false,
  [patientCautions.name]: "",

  [isImproved.name]: false,
  [isNoChanges.name]: false,
  [isRegressed.name]: false,
  [isFlareUp.name]: false,
  [additionalAssessment.name]: "",

  [doe.name]: "",
  [isVitals.name]: false,
  [bp.name]: "",
  [mmHG.name]: "",
  [pulse.name]: "",
  [temp.name]: "",
  [rr.name]: "",
  [spo2.name]: "",
  [isNeurologicalExam.name]: false,
  [isCranialNerves.name]: false,
  [cranialNerves.name]: "",
  [isRombergs.name]: false,
  [rombergs.name]: "",
  [isDiadichodyskinesia.name]: false,
  [diadichodyskinesia.name]: "",
  [isDermatomes.name]: false,
  [dermatomes.name]: "",
  [isMyotomes.name]: false,
  [myotomes.name]: "",
  [isDtrs.name]: false,
  [dtrs.name]: "",
  [isPathological.name]: false,
  [pathological.name]: "",
  [isHomans.name]: false,
  [homans.name]: "",

  [flexion60_exam.name]: "",
  [flexion60_pain.name]: false,
  [flexion60_noPain.name]: false,
  [flexion60_location.name]: "",
  [flexion60_left.name]: "",
  [flexion60_right.name]: "",

  [cervicalRegionalNotes1.name]: "",
  [cervicalRegionalNotes2.name]: "",
};

export default {initialValues,initialValues1};
