import moment from "moment";
const initialValues = {
  page27: [
    {
      name: "",
      age: "",
      gender: "",
      date: "",
      formCreatedDate: moment().format("DD-MM-YYYY"),
      sectionsA: [
        {
          name: "Is your memory noticeably declining? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Are you having a hard time remembering names and phone numbers?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Is your ability to focus noticeably declining? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Has it become harder for you to learn new things? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you have a hard time remembering your appointments? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Is your temperament generally getting worse? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Is your attention span decreasing?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you find yourself down or sad?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you become fatigued when driving compared to in the past?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you become fatigued when reading compared to in the past?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you walk into rooms and forget why?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you pick up your cell phone and forget why?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
      ],
      sectionsB: [
        {
          name: "How high is your stress level? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you feel you have something that must be done? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Do you feel you never have time for yourself?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you feel you are not getting enough sleep or rest?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Do you find it difficult to get regular exercise?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Do you feel uncared for by the people in your life? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Do you feel you are not accomplishing your life’s purpose?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Is sharing your problems with someone difficult for you? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
      ],
      sectionsC1: [
        {
          name: "How often do you get irritable, shaky, or have light-headedness between meals?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you feel energized after eating? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you have difficulty eating large meals in the morning?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often does your energy level drop in the afternoon? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you crave sugar and sweets in the afternoon?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you wake up in the middle of the night?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you have difficulty concentrating before eating?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you depend on coffee to keep yourself going?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you feel agitated, easily upset, and nervous between meals?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
      ],
      sectionsC2: [
        {
          name: "How often do you get fatigued after meals? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you crave sugar and sweets after meals?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you feel you need stimulants, such as coffee, after meals?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you have difficulty losing weight? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How much larger is your waist girth compared to your hip girth?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you urinate?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Have your thirst and appetite increased?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you gain weight when under stress?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        // {
        //   name: "How often do you urinate?",
        //   checkbox1: false,
        //   checkbox2: false,
        //   checkbox3: false,
        //   checkbox4: false,
        // },
        // {
        //   name: "Have your thirst and appetite increased?",
        //   checkbox1: false,
        //   checkbox2: false,
        //   checkbox3: false,
        //   checkbox4: false,
        // },
        {
          name: "How often do you have difficulty falling asleep?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
      ],
      sections1: [
        {
          name: "Are you losing interest in hobbies?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you feel overwhelmed? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you have feelings of inner rage? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you have feelings of paranoia? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you feel sad or down for no reason?  ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you feel like you are not enjoying life? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you feel you lack artistic appreciation? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you feel depressed in overcast weather? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How much are you losing your enthusiasm for your favorite activities? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How much are you losing your enjoyment for your favorite foods?  ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How much are you losing your enjoyment of friendships and relationships? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you have difficulty falling into deep, restful sleep? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you have feelings of dependency on others? ",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you feel more susceptible to pain?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How often do you have feelings of unprovoked anger?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "How much are you losing interest in life?",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
      ],
    },
  ],
};

export default initialValues;
