import Basket from "examples/Icons/Basket";
import CreditCard from "examples/Icons/CreditCard";
import CustomerSupport from "examples/Icons/CustomerSupport";
import Document from "examples/Icons/Document";
import Office from "examples/Icons/Office";
import Shop from "examples/Icons/Shop";
import SpaceShip from "examples/Icons/SpaceShip";
import SchoolIcon from "@mui/icons-material/School";
const routes = [
  {
    type: "collapse",
    name: "Informed Consent",
    key: "informed-consent",
    route: "/informed-consent",
    id: "informedConsent",
    icon: <Shop size="12px" />,
    noCollapse: true,
    isClient: true,
    isDoctor: true,
  },
  {
    type: "collapse",
    name: "Practitioner Agreement",
    key: "associate-practitioner-agreement",
    route: "/associate-practitioner-agreement",
    id: "associate-practitioner-agreement",
    icon: <Shop size="12px" />,
    noCollapse: true,
    isClient: false,
    isDoctor: true,
  },
  {
    type: "collapse",
    name: "Welcome",
    key: "welcome",
    route: "/welcome",
    id: "welcome",
    icon: <Shop size="12px" />,
    noCollapse: true,
    isClient: true,
    isDoctor: true,
  },
  // {
  //   type: "collapse",
  //   name: "Home",
  //   key: "home",
  //   route: "/home",
  //   id: "home",
  //   icon: <Shop size="12px" />,
  //   noCollapse: true,
  //   isClient: true,
  //   isDoctor: true
  // },
  // { type: "divider", key: "divider-2" },
  // { type: "title", title: "", key: "title-msg" },

  {
    type: "collapse",
    name: "Services",
    key: "services",
    route: "/services",
    id: "services",
    icon: <Office size="12px" />,
    noCollapse: true,
    isClient: true,
    isDoctor: true,
  },

  {
    type: "collapse",
    name: "My Services",
    key: "myServices",
    route: "/myServices",
    id: "myServices",
    icon: <Office size="12px" />,
    noCollapse: true,
    isClient: true,
    isDoctor: true,
  },
  // {
  //   type: "collapse",
  //   name: "Client Intake Form",
  //   key: "client-intake-form",
  //   route: "/client-intake-form",
  //   id: "client-intake-form",
  //   icon: <Office size="12px" />,
  //   noCollapse: true,
  //   isClient: true,
  // },
  {
    type: "collapse",
    name: "Calendar",
    key: "calendar",
    route: "/calendar",
    id: "calendar",
    icon: <Basket size="12px" />,
    noCollapse: true,
    isClient: true,
    isDoctor: true,
  },
  // only for doctor access
  // {
  //   type: "collapse",
  //   name: "Schedule",
  //   key: "schedule",
  //   route: "/schedule",
  //   id: "schedule",
  //   icon: <Basket size="12px" />,
  //   noCollapse: true,
  //   isClient: false,
  // },
  {
    type: "collapse",
    name: "Book Appointments",
    key: "book-appointments",
    id: "book-appointments",
    route: "/book-appointments",
    icon: <Basket size="12px" />,
    noCollapse: true,
    isClient: true,
    isDoctor: true,
  },
  {
    type: "collapse",
    name: "Upcoming Practitioner Apts",
    key: "upcoming-appointment",
    id: "upcoming-appointment",
    route: "/upcoming-appointment",
    icon: <Document size="12px" />,
    noCollapse: true,
    isClient: false,
    isDoctor: true,
  },
  {
    type: "collapse",
    name: "Upcoming Appointments",
    key: "upcoming-appointments",
    id: "upcoming-appointments",
    route: "/upcoming-appointments",
    icon: <Document size="12px" />,
    noCollapse: true,
    isClient: true,
    isDoctor: false,
  },
  {
    type: "collapse",
    name: "Upcoming Clients",
    key: "upcoming-Clients",
    route: "/upcoming-Clients",
    id: "upcomingClients",
    icon: <Basket size="12px" />,
    noCollapse: true,
    isClient: false,
    isDoctor: true,
  },
  {
    type: "collapse",
    name: "Upcoming Events",
    key: "upcoming-Events",
    route: "/upcoming-Events",
    id: "upcomingEvents",
    icon: <Basket size="12px" />,
    noCollapse: true,
    isClient: true,
    isDoctor: true,
  },
  {
    type: "collapse",
    name: "Photo Therapy",
    key: "photo-therapy",
    id: "photo-therapy",
    route: "/photo-therapy",
    icon: <Document size="12px" />,
    noCollapse: true,
    isClient: true,
    isDoctor: true,
  },
  {
    type: "collapse",
    name: "Video Messaging and Photo Therapy",
    key: "video-messaging-therapy",
    id: "video-messaging-therapy",
    route: "/video-messaging-therapy",
    icon: <SpaceShip size="12px" />,
    noCollapse: true,
    isClient: true,
    isDoctor: true,
  },
  {
    type: "collapse",
    name: "Live Video Therapy Portal",
    key: "live-video-portal",
    id: "live-video-portal",
    route: "/live-video-portal",
    icon: <CustomerSupport size="12px" />,
    noCollapse: true,
    isClient: true,
    isDoctor: true,
  },
  {
    type: "collapse",
    name: "Live In Person Portal",
    key: "live-in-person-portal",
    id: "live-in-person-portal",
    route: "/live-in-person-portal",
    icon: <CustomerSupport size="12px" />,
    noCollapse: true,
    isClient: true,
    isDoctor: true,
  },
  {
    type: "collapse",
    name: "Photos and Videos",
    key: "photo-video",
    id: "photo-video",
    route: "/photo-video",
    icon: <CreditCard size="12px" />,
    noCollapse: true,
    isClient: true,
    isDoctor: true,
  },
  {
    type: "collapse",
    name: "Reports & Labs",
    key: "labs",
    id: "labs",
    route: "/labs",
    icon: <Shop size="12px" />,
    noCollapse: true,
    isClient: true,
    isDoctor: true,
  },
  {
    type: "collapse",
    name: "Client Records",
    key: "patient-Records",
    id: "patient-Records",
    route: "/patient-Records",
    icon: <Basket size="12px" />,
    noCollapse: true,
    isClient: false,
    isDoctor: true,
  },
  {
    type: "collapse",
    name: "Sequences",
    id: "sequences",
    key: "sequences",
    route: "/sequences",
    icon: <Basket size="12px" />,
    noCollapse: true,
    isClient: true,
    isDoctor: true,
  },
  {
    type: "collapse",
    name: "Nutrition",
    key: "nutrition",
    id: "nutrition",
    route: "/nutrition",
    icon: <Office size="12px" />,
    noCollapse: true,
    isClient: true,
    isDoctor: true,
  },
  {
    type: "collapse",
    name: "Daily Updates",
    key: "daily-updates",
    id: "daily-updates",
    route: "/daily-updates",
    icon: <Shop size="12px" />,
    noCollapse: true,
    isClient: true,
    isDoctor: true,
  },
  {
    type: "collapse",
    name: "Progress Chart",
    key: "progress-chart",
    id: "progress-chart",
    route: "/progress-chart",
    icon: <Basket size="12px" />,
    noCollapse: true,
    isClient: true,
    isDoctor: true,
  },
  // for a doctor access

  // {
  //   type: "collapse",
  //   name: "SOAP Notes",
  //   key: "SOAP-Note",
  //   id: "SOAP-Note",
  //   route: "/SOAP-Note",
  //   icon: <Basket size="12px" />,
  //   noCollapse: true,
  //   isClient: false,
  //   isDoctor: true
  // },
  {
    type: "collapse",
    name: "Clinical Guideline Program",
    key: "Clinical-Guideline-Program",
    id: "Clinical-Guideline-Program",
    route: "/Clinical-Guideline-Program",
    icon: <Basket size="12px" />,
    noCollapse: true,
    isClient: false,
    isDoctor: true,
  },
  {
    type: "collapse",
    name: "Sequence Generator",
    key: "Sequence-Generator",
    id: "Sequence-Generator",
    route: "/Sequence-Generator",
    icon: <Basket size="12px" />,
    noCollapse: true,
    isClient: false,
    isDoctor: true,
  },
  {
    type: "collapse",
    name: "Work History",
    key: "Work-History",
    id: "Work-History",
    route: "/Work-History",
    icon: <Basket size="12px" />,
    noCollapse: true,
    isClient: false,
    isDoctor: true,
  },
  {
    type: "collapse",
    name: "Practitioner Performance",
    key: "practitioner-performance",
    id: "practitioner-performance",
    route: "/practitioner-performance",
    icon: <Basket size="12px" />,
    noCollapse: true,
    isClient: false,
    isDoctor: true,
  },
  {
    type: "collapse",
    name: "Education Services",
    key: "Education",
    id: "Education",
    route: "/Education",
    icon: <Basket size="12px" />,
    noCollapse: true,
    isClient: false,
    isDoctor: true,
  },
  {
    type: "collapse",
    name: "My Education Material",
    key: "Education-Material",
    id: "Education-Material",
    route: "/Education-Material",
    icon: <SchoolIcon size="12px" />,
    noCollapse: true,
    isClient: false,
    isDoctor: true,
  },
  {
    type: "collapse",
    name: "Equipment",
    key: "equipment",
    id: "equipment",
    route: "/equipment",
    icon: <CreditCard size="12px" />,
    noCollapse: true,
    isClient: true,
    isDoctor: true,
  },
  // { type: "divider", key: "divider-1" },
  // { type: "title", title: "", key: "title-docs" },
  {
    type: "collapse",
    name: "Contact Us",
    key: "contact-us",
    id: "contact-us",
    route: "/contact-us",
    icon: <CreditCard size="12px" />,
    noCollapse: true,
    isClient: true,
    isDoctor: true,
  },
];

export default routes;
