import moment from "moment";
const initialValues = {
  page13: [
    {
      formCreatedDate: moment().format("DD-MM-YYYY"),
      name: "",
      date: "",
      neckpainyear: "",
      neckpainmonth: "",
      neckpainweek: "",
      backpainyear: "",
      backpainmonth: "",
      backpainweek: "",

      // left body
      abc: false,
      lhead: false,
      lbrain: false,
      lbrainleft: false,
      lbrainright: false,
      lchickleft: false,
      lchickright: false,
      lshoulderleft: false,
      lthorex: false,
      lshoulderright: false,
      lchest: false,
      larmleft: false,
      larmright: false,
      llungsleft: false,
      llungsright: false,
      lelbowleft: false,
      lelbowright: false,
      lumbilicusleft: false,
      lumbilicusright: false,
      lforarmleft: false,
      lforarmright: false,
      lhandleft: false,
      lhandright: false,
      ladomenleft: false,
      ladomen: false,
      ladomenright: false,
      lthighleft: false,
      lthighright: false,
      lkneeleft: false,
      lkneeright: false,
      lcalfleft: false,
      lcalfright: false,
      llegsleft: false,
      llegsright: false,
      lfeetleft: false,
      lfeetright: false,
      ltoesleft: false,
      ltoesright: false,

      // middle part

      middlefirstone: false,
      middlefirsttwo: false,
      middlefirstthree: false,
      middlefirstfour: false,
      middlefirstfive: false,
      middlefirstsix: false,
      middlefirstseven: false,
      middlefirsteight: false,
      middlefirstnine: false,
      middlefirstten: false,
      middlefirsteleven: false,
      middlefirsttwleve: false,
      middlefirstthirteen: false,
      middlefirstfourteen: false,
      middlefirstfifteen: false,

      middlesecondone: false,
      middlesecondtwo: false,
      middlesecondthree: false,
      middlesecondfour: false,
      middlesecondfive: false,
      middlesecondsix: false,
      middlesecondseven: false,
      middlesecondeight: false,
      middlesecondnine: false,
      middlesecondten: false,
      middlesecondeleven: false,
      middlesecondtwleve: false,
      middlesecondthirteen: false,
      middlesecondfourteen: false,
      middlesecondfifteen: false,

      // right part

      rightbrain: false,
      rightmounth: false,
      rightthroat: false,
      rightneckleft: false,
      rightneckright: false,
      rightshoulderleft: false,
      rightchest: false,
      rightshoulderright: false,
      rightback: false,
      rightarmleft: false,
      rightarmright: false,
      rightloin: false,
      rightelbowleft: false,
      rightumnilicus: false,
      rightelbowright: false,
      rightforarmleft: false,
      righthipleft: false,
      rightadomen: false,
      righthipright: false,
      rightforarmright: false,
      righthandleft: false,
      rightbuttockleft: false,
      rightbuttockright: false,
      righthandright: false,
      rightpalmleft: false,
      rightpenish: false,
      rightpalmright: false,
      rightthighleft: false,
      rightthighright: false,
      rightkneeleft: false,
      rightkneeright: false,
      rightcalfleft: false,
      rightcalfright: false,
      rightlegsleft: false,
      rightlegsright: false,
      rightfootleft: false,
      rightfootright: false,
      righttoesleft: false,
      righttoesright: false,

      // endpart
      conditions: [""],
      // condition1: "",
      // condition2: "",
      // condition3: "",
      // condition4: "",
      // condition5: "",
      // condition6: "",
      // condition7: "",
      // condition8: "",
      // condition9: "",
    },
  ],
};

export default initialValues;
