import moment from "moment";
const initialValues = {
  page26: [
    {
      formCreatedDate: moment().format("DD-MM-YYYY"),
      section9: [
        {
          name: "A diagnosis of celiac disease, gluten sensitivity, hypothyroidism, or an autoimmune disease",
          checkboxredio9: "",
        },
        {
          name: "Family members who have been diagnosed with an autoimmune disease",
          checkboxredio9: "",
        },
        {
          name: "Family members who have been diagnosed with celiac disease or gluten sensitivity",
          checkboxredio9: "",
        },
        {
          name: "Changes in brain function with stress, poor sleep, or immune activation",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
      ],

      section10: [
        {
          name: "A loss of pleasure in hobbies and interests",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Feel overwhelmed with ideas to manage",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "	 Feelings of inner rage or unprovoked anger",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Feelings of paranoia",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Feelings of sadness for no reason",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "A loss of enjoyment in life",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "A lack of artistic appreciation",
          checkboxredio1: "",
        },

        {
          name: "Feelings of sadness in overcast weather",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },

        {
          name: "A loss of enthusiasm for favorite activities",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "	 A loss of enjoyment in favorite foods",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "A loss of enjoyment in friendships and relationships",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Inability to fall into deep, restful sleep",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Feelings of dependency on others",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Feelings of susceptibility to pain",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
      ],

      section11: [
        {
          name: "Feelings of worthlessness",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Feelings of hopelessness",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Self-destructive thoughts",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "	 Inability to handle stress",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Anger and aggression while under stress",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Feelings of tiredness, even after many hours of sleep 0",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "A desire to isolate yourself from others",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },

        {
          name: "An unexplained lack of concern for family and friends",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "An inability to finish tasks",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Feelings of anger for minor reasons",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
      ],

      section12: [
        {
          name: "A decrease in visual memory (shapes and images)",
          checkboxredio12: "",
        },
        {
          name: "A decrease in verbal memory",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Occurrence of memory lapses",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "A decrease in creativity",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "A decrease in comprehension",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty calculating numbers",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Difficulty recognizing objects and faces",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "A change in opinion about yourself",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Slow mental recall",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
      ],

      section13: [
        {
          name: "A decrease in mental alertness",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "A decrease in mental speed",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "	 A decrease in concentration quality",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "	 Slow cognitive processing",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Impaired mental performance",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "An increase in the ability to be distracted",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Need coffee or caffeine sources to improve mental function",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
      ],

      section14: [
        {
          name: "	 Feelings of nervousness or panic for no reason",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Feelings of dread",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Feelings of a “knot” in your stomach",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "	 Feelings of being overwhelmed for no reason",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "	 Feelings of guilt about everyday decisions",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "A restless mind",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "An inability to turn off the mind when relaxing",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Disorganized attention",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Worry over things never thought about before",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
        {
          name: "Feelings of inner tension and inner excitability",
          checkbox1: false,
          checkbox2: false,
          checkbox3: false,
          checkbox4: false,
        },
      ],
    },
  ],
};

export default initialValues;
