const initialValues = {
    name: "",
    todaydate: "",
    dob: "",
    height: "",
    weight: "",
    dominant: "",
    address: "",
    city: "",
    zip: "",
    Cellphonenumber1: "",
    nikunj:"",
    phonenumbrWork: "",
    email: "",
    dl: "",
    health:"",
    policy:"",
    address1:"",
    city1: "",
    zip1:"",
    adjuster:"",
    phone:"",
    car:"",
    address2:"",
    city2:"",
    zip2:"",
    adjuster1:"",
    phone1:"",
    agent:"",
    phone2:"",
    policy1:"",
    claim:"",
    medicalpayments:"",
    uninsuredmotorist:"",
    lawfirm:"",
    address3:"",
    city3:"",
    zip3:"",
    lawyer:"",
    phone3:"",
    carpolicy:"",
    patient:"",
    lossaccident:"",
    afteraccident:"",
    medicaltreatment:"",
    income:"",
    propertydamage:"",
    personal: "",
    phone4:"",
    address4:"",
    city4:"",
    zip4:"",
    lastname:"",
    type:"",
    lastphone:"",
    lastamount:"",
    record:""
}
export default initialValues;