const form = {
   formField : {
    dizzinessCheck:{
        type:'checkbox',
        name:"dizzinessCheck"
      },
      dizzinessinput:{
        type:'text',
        name:'dizzinessinput'
      },
      DiplopiaCheck:{
        type:'checkbox',
        name:"DiplopiaCheck"
      },
      Diplopiainput:{
        type:'text',
        name:"Diplopiainput"
      },
      DysphagiaCheck:{
        type:'checkbox',
        name:"DysphagiaCheck"
      },
      DysphagiaInput:{
        type:'text',
        name:"DysphagiaInput"
      },
      DysphasiaCheck:{
        type:'checkbox',
        name:"DysphasiaCheck"
      },
      DysphasiaInput:{
        type:'text',
        name:"DysphasiaInput"
      },
      DropCheck:{
        type:'checkbox',
        name:"DropCheck"
      },
      DropInput:{
        type:'text',
        name:"DropInput"
      },
      NystagmusCheck:{
        type:'checkbox',
        name:"NystagmusCheck"
      },
      NystagmusInput:{
        type:'text',
        name:"NystagmusInput"
      },

      NauseaCheck:{
        type:'checkbox',
        name:"NauseaCheck"
      },
      NauseaInput:{
        type:'text',
        name:"NauseaInput"
      },
      NumbnessCheck:{
        type:'checkbox',
        name:"NumbnessCheck"
      },
      NumbnessInput:{
        type:'text',
        name:"NumbnessInput"
      },
      ExtremeCheck:{
        type:'checkbox',
        name:"ExtremeCheck"
      },
      ExtremeInput:{
        type:'text',
        name:"ExtremeInput"
      },
      coordCheck:{
        type:'checkbox',
        name:"coordCheck"
      },
      coordInput:{
        type:'text',
        name:"coordInput"
      },
      eyesCheck:{
        type:'checkbox',
        name:"eyesCheck"
      },
      eyesInput:{
        type:'text',
        name:"eyesInput"
      },
      ConfusionCheck:{
        type:'checkbox',
        name:"ConfusionCheck"
      },
      ConfusionInput:{
        type:'text',
        name:"ConfusionInput"
      },
      
      //CACheckbox schema

      CancerCheck:{
        type:'checkbox',
        name:"CancerCheck"
      },
      CancerInput:{
        type:'text',
        name:"CancerInput"
      },
      RecentCheck:{
        type:'checkbox',
        name:"RecentCheck"
      },
      RecentInput:{
        type:'text',
        name:"RecentInput"
      },
      
      FeverCheck:{
        type:'checkbox',
        name:"FeverCheck"
      },
      FeverInput:{
        type:'text',
        name:"FeverInput"
      },
      ChillsCheck:{
        type:'checkbox',
        name:"ChillsCheck"
      },
      ChillsInput:{
        type:'text',
        name:"ChillsInput"
      },
      SweatsCheck:{
        type:'checkbox',
        name:"SweatsCheck"
      },
      SweatsInput:{
        type:'text',
        name:"SweatsInput"
      },
      wakesCheck:{
        type:'checkbox',
        name:"wakesCheck"
      },
      wakesInput:{
        type:'text',
        name:"wakesInput"
      },
      CoughingCheck:{
        type:'checkbox',
        name:"CoughingCheck"
      },
      CoughingInput:{
        type:'text',
        name:"CoughingInput"
      },
      BladderCheck:{
        type:'checkbox',
        name:"BladderCheck"
      },
      BladderInput:{
        type:'text',
        name:"BladderInput"
      },
      BloodCheck:{
        type:'checkbox',
        name:"BloodCheck"
      },
      BloodInput:{
        type:'text',
        name:"BloodInput"
      },
      BowelCheck:{
        type:'checkbox',
        name:"BowelCheck"
      },
      BowelInput:{
        type:'text',
        name:"BowelInput"
      },
      urinationCheck:{
        type:'checkbox',
        name:"urinationCheck"
      },
      urinationInput:{
        type:'text',
        name:"urinationInput"
      },
//CardiacCheckBoxes 
      ChestCheck:{
        type:'checkbox',
        name:"ChestCheck"
      },
      ChestInput:{
        type:'text',
        name:"ChestInput"
      },
      SOBCheck:{
        type:'checkbox',
        name:"SOBCheck"
      },
      SOBInput:{
        type:'text',
        name:"SOBInput"
      },
      breathingCheck:{
        type:'checkbox',
        name:"breathingCheck"
      },
      breathingInput:{
        type:'text',
        name:"breathingInput"
      },
      AttackCheck:{
        type:'checkbox',
        name:"AttackCheck"
      },
      AttackInput:{
        type:'text',
        name:"AttackInput"
      },
      HeartbeatCheck:{
        type:'checkbox',
        name:"HeartbeatCheck"
      },
      HeartbeatInput:{
        type:'text',
        name:"HeartbeatInput"
      },
      HBPCheck:{
        type:'checkbox',
        name:"HBPCheck"
      },
      HBPInput:{
        type:'text',
        name:"HBPInput"
      },
      LBPCheck:{
        type:'checkbox',
        name:"LBPCheck"
      },
      LBPInput:{
        type:'text',
        name:"LBPInput"
      },
      NVCheck:{
        type:'checkbox',
        name:"NVCheck"
      },
      NVInput:{
        type:'text',
        name:"NVInput"
      },
      SmokesCheck:{
        type:'checkbox',
        name:"SmokesCheck"
      },
      SmokesInput:{
        type:'text',
        name:"SmokesInput"
      },

      StrokeCheck:{
        type:'checkbox',
        name:"StrokeCheck"
      },
      StrokeInput:{
        type:'text',
        name:"StrokeInput"
      },
      VascularCheck:{
        type:'checkbox',
        name:"VascularCheck"
      },
      VascularInput:{
        type:'text',
        name:"VascularInput"
      },
      LocCheck:{
        type:'checkbox',
        name:"LocCheck"
      },
      LocInput:{
        type:'text',
        name:"LocInput"
      },
      LostCheck:{
        type:'checkbox',
        name:"LostCheck"
      },
      LostInput:{
        type:'text',
        name:"LostInput"
      },
      VisionCheck:{
        type:'checkbox',
        name:"VisionCheck"
      },
      VisionInput:{
        type:'text',
        name:"VisionInput"
      },
      VertigoCheck:{
        type:'checkbox',
        name:"VertigoCheck"
      },
      VertigoInput:{
        type:'text',
        name:"VertigoInput"
      },
      BalanceCheck:{
        type:'checkbox',
        name:"BalanceCheck"
      },
      BalanceInput:{
        type:'text',
        name:"BalanceInput"
      },
      DexterityCheck:{
        type:'checkbox',
        name:"DexterityCheck"
      },
      DexterityInput:{
        type:'text',
        name:"DexterityInput"
      },
      MyelopathicCheck:{
        type:'checkbox',
        name:"MyelopathicCheck"
      },
      MyelopathicInput:{
        type:'text',
        name:"MyelopathicInput"
      },
      SmokesCheck:{
        type:'checkbox',
        name:"SmokesCheck"
      },
      ChangesInput:{
        type:'text',
        name:"ChangesInput"
      },
      ChangesCheck:{
        type:'checkbox',
        name:"ChangesCheck"
      },
      SuddenInput:{
        type:'text',
        name:"SuddenInput"
      },
      SuddenCheck:{
        type:'checkbox',
        name:"SuddenCheck"
      },
      LocalizedInput:{
        type:'text',
        name:"LocalizedInput"
      },
      LocalizedCheck:{
        type:'checkbox',
        name:"LocalizedCheck"
      },
      sensationInput:{
        type:'text',
        name:"sensationInput"
      },
      sensationCheck:{
        type:'checkbox',
        name:"sensationCheck"
      },
      DifficultyInput:{
        type:'text',
        name:"DifficultyInput"
      },
      DifficultyCheck:{
        type:'checkbox',
        name:"DifficultyCheck"
      },
      MentalInput:{
        type:'text',
        name:"MentalInput"
      },
      MentalCheck:{
        type:'checkbox',
        name:"MentalCheck"
      },
      DiabetesInput:{
        type:'text',
        name:"DiabetesInput"
      },
      DiabetesCheck:{
        type:'checkbox',
        name:"DiabetesCheck"
      },



      LungInput:{
        type:'text',
        name:"LungInput"
      },
      LungCheck:{
        type:'checkbox',
        name:"LungCheck"
      },
      NeuroInput:{
        type:'text',
        name:"NeuroInput"
      },
      NeuroCheck:{
        type:'checkbox',
        name:"NeuroCheck"
      },
      SeizuresInput:{
        type:'text',
        name:"SeizuresInput"
      },
      SeizuresCheck:{
        type:'checkbox',
        name:"SeizuresCheck"
      },
      ThyroidInput:{
        type:'text',
        name:"ThyroidInput"
      },
      ThyroidCheck:{
        type:'checkbox',
        name:"ThyroidCheck"
      },
      ConcussionsInput:{
        type:'text',
        name:"ConcussionsInput"
      },
      ConcussionsCheck:{
        type:'checkbox',
        name:"ConcussionsCheck"
      },
      HeadInput:{
        type:'text',
        name:"HeadInput"
      },
      HeadCheck:{
        type:'checkbox',
        name:"HeadCheck"
      },
      MVAInput:{
        type:'text',
        name:"MVAInput"
      },
      MVACheck:{
        type:'checkbox',
        name:"MVACheck"
      },
      TraumaInput:{
        type:'text',
        name:"TraumaInput"
      },
      TraumaCheck:{
        type:'checkbox',
        name:"TraumaCheck"
      },
      CesareanInput:{
        type:'text',
        name:"CesareanInput"
      },
      CesareanCheck:{
        type:'checkbox',
        name:"CesareanCheck"
      },
      OtherInput:{
        type:'text',
        name:"OtherInput"
      },
      OtherCheck:{
        type:'checkbox',
        name:"OtherCheck"
      },

    }

}

export default form;