import moment from "moment";
import checkout from "./form";

const {
  formField: {
    dizzinessCheck,
    dizzinessinput,
    DiplopiaCheck,
    Diplopiainput,
    DysphagiaCheck,
    DysphagiaInput,
    DysphasiaCheck,
    DysphasiaInput,
    DropCheck,
    DropInput,
    NystagmusCheck,
    NystagmusInput,
    NauseaCheck,
    NauseaInput,
    NumbnessCheck,
    NumbnessInput,
    ExtremeCheck,
    ExtremeInput,
    coordCheck,
    coordInput,
    eyesCheck,
    eyesInput,
    ConfusionCheck,
    ConfusionInput,

    CancerCheck,
    CancerInput,
    RecentCheck,
    RecentInput,

    FeverCheck,
    FeverInput,

    ChillsCheck,
    ChillsInput,

    SweatsCheck,
    SweatsInput,
    wakesCheck,
    wakesInput,
    CoughingCheck,
    CoughingInput,
    BladderCheck,
    BladderInput,
    BloodCheck,
    BloodInput,
    BowelCheck,
    BowelInput,
    urinationCheck,
    urinationInput,

    ChestCheck,
    ChestInput,
    SOBCheck,
    SOBInput,
    breathingCheck,
    breathingInput,
    AttackCheck,
    AttackInput,
    HeartbeatCheck,
    HeartbeatInput,
    HBPCheck,
    HBPInput,
    LBPCheck,
    LBPInput,
    NVCheck,
    NVInput,
    SmokesCheck,
    SmokesInput,
    AlcoholCheck,

    StrokeCheck,
    StrokeInput,
    VascularCheck,
    VascularInput,
    LocCheck,
    LocInput,
    VisionCheck,
    VisionInput,
    LostCheck,
    LostInput,
    VertigoCheck,
    VertigoInput,
    BalanceCheck,
    BalanceInput,

    DexterityCheck,
    DexterityInput,
    MyelopathicCheck,
    MyelopathicInput,
    ChangesCheck,
    ChangesInput,
    SuddenCheck,
    SuddenInput,
    LocalizedCheck,
    LocalizedInput,
    sensationCheck,
    sensationInput,
    DifficultyCheck,
    DifficultyInput,
    MentalCheck,
    MentalInput,
    DiabetesCheck,
    DiabetesInput,

    LungCheck,
    LungInput,
    NeuroCheck,
    NeuroInput,
    SeizuresCheck,
    SeizuresInput,
    ThyroidCheck,
    ThyroidInput,
    ConcussionsCheck,
    ConcussionsInput,
    HeadCheck,
    HeadInput,
    MVACheck,
    MVAInput,

    TraumaCheck,
    TraumaInput,
    CesareanCheck,
    CesareanInput,
    OtherCheck,
    OtherInput,
  },
} = checkout;

const initialValues = {
  tenthPage: [
    {
      [dizzinessCheck.name]: false,
      [dizzinessinput.name]: "",
      [DiplopiaCheck.name]: false,
      [Diplopiainput.name]: "",
      [DysphagiaCheck.name]: false,
      [DysphagiaInput.name]: "",
      [DysphasiaCheck.name]: false,
      [DysphasiaInput.name]: "",
      [DropCheck.name]: false,
      [DropInput.name]: "",
      [NystagmusCheck.name]: false,
      [NystagmusInput.name]: "",

      [NauseaCheck.name]: false,
      [NauseaInput.name]: "",
      [NumbnessCheck.name]: false,
      [NumbnessInput.name]: "",
      [ExtremeCheck.name]: false,
      [ExtremeInput.name]: "",
      [coordCheck.name]: false,
      [coordInput.name]: "",
      [eyesCheck.name]: false,
      [eyesInput.name]: "",
      [ConfusionCheck.name]: false,
      [ConfusionInput.name]: "",

      [CancerCheck.name]: false,
      [CancerInput.name]: "",
      [RecentCheck.name]: false,
      [RecentInput.name]: "",
      [FeverCheck.name]: false,
      [FeverInput.name]: "",
      [ChillsCheck.name]: false,
      [ChillsInput.name]: "",
      [SweatsCheck.name]: false,
      [SweatsInput.name]: "",
      [wakesCheck.name]: false,
      [wakesInput.name]: "",
      [CoughingCheck.name]: false,
      [CoughingInput.name]: "",
      [BladderCheck.name]: false,
      [BladderInput.name]: "",
      [BloodCheck.name]: false,
      [BloodInput.name]: "",
      [BowelCheck.name]: false,
      [BowelInput.name]: "",
      [urinationCheck.name]: false,
      [urinationInput.name]: "",

      [ChestCheck.name]: false,
      [ChestInput.name]: "",
      [SOBCheck.name]: false,
      [SOBInput.name]: "",
      [breathingCheck.name]: false,
      [breathingInput.name]: "",
      [AttackCheck.name]: false,
      [AttackInput.name]: "",
      [HeartbeatCheck.name]: false,
      [HeartbeatInput.name]: "",
      [HBPCheck.name]: false,
      [HBPInput.name]: "",
      [LBPCheck.name]: false,
      [LBPInput.name]: "",
      [NVCheck.name]: false,
      [NVInput.name]: "",
      [SmokesCheck.name]: false,
      [SmokesInput.name]: "",

      //CVACheckboxes
      [StrokeCheck.name]: false,
      [StrokeInput.name]: "",
      [VascularCheck.name]: false,
      [VascularInput.name]: "",
      [LocCheck.name]: false,
      [LocInput.name]: "",
      [LostCheck.name]: false,
      [LostInput.name]: "",
      [VisionCheck.name]: false,
      [VisionInput.name]: "",
      [VertigoCheck.name]: false,
      [VertigoInput.name]: "",
      [BalanceCheck.name]: false,
      [BalanceInput.name]: "",
      [DexterityCheck.name]: false,
      [DexterityInput.name]: "",
      [MyelopathicCheck.name]: false,
      [MyelopathicInput.name]: "",

      [ChangesCheck.name]: false,
      [ChangesInput.name]: "",

      [SuddenCheck.name]: false,
      [SuddenInput.name]: "",
      [LocalizedCheck.name]: false,
      [LocalizedInput.name]: "",
      [sensationCheck.name]: false,
      [sensationInput.name]: "",
      [DifficultyCheck.name]: false,
      [DifficultyInput.name]: "",
      [MentalCheck.name]: false,
      [MentalInput.name]: "",

      [DiabetesCheck.name]: false,
      [DiabetesInput.name]: "",
      [LungCheck.name]: false,
      [LungInput.name]: "",
      [NeuroCheck.name]: false,
      [NeuroInput.name]: "",
      [SeizuresCheck.name]: false,
      [SeizuresInput.name]: "",
      [ThyroidCheck.name]: false,
      [ThyroidInput.name]: "",
      [ConcussionsCheck.name]: false,
      [ConcussionsInput.name]: "",
      [HeadCheck.name]: false,
      [HeadInput.name]: "",
      [MVACheck.name]: false,
      [MVAInput.name]: "",
      [TraumaCheck.name]: false,
      [TraumaInput.name]: "",
      [CesareanCheck.name]: false,
      [CesareanInput.name]: "",

      [OtherCheck.name]: false,
      [OtherInput.name]: "",
      formCreatedDate: moment().format("DD-MM-YYYY"),
      patientDetailsForm: {
        PractitionerName: "",
        NPI: "",
        TIN: "",
        hourlyRate: "",
        patientName: "",
        name: "",
        isNewPatient: false,
        isFollowUpPatient: false,
        isNewComplaintPatient: false,
        patientVisitNumber: "",
        patientTodaysDate: "",
        patientNextReExam: "",
        patientDob: "",
        patientAge: "",
        patientHeight: "",
        patientHeightNI: false,
        patientWeight: "",
        patientWeightNI: false,
        patientHtnYes: false,
        patientHtnNo: false,
        patientCautions: "",
      },
    },
  ],
};

export default initialValues;
