const form = {
    formField:{
        clunkSoundwithNeckNever:{
            type:'text',
            name:"clunkSoundwithNeckNever"
          },
          clunkSoundwithNeckHealed:{
            type:'text',
            name:"clunkSoundwithNeckHealed"
          },
          clunkSoundwithNeckStillHave:{
            type:'text',
            name:"clunkSoundwithNeckStillHave"
          },
          clunkSoundwithNeckImprovedLittle:{
            type:'text',
            name:"clunkSoundwithNeckImprovedLittle"
          },
          clunkSoundwithNeckImprovedMedium:{
            type:'text',
            name:"clunkSoundwithNeckImprovedMedium"
          },
          clunkSoundwithNeckImprovedLot:{
            type:'text',
            name:"clunkSoundwithNeckImprovedLot"
          },
          clunkSoundwithNeckNotImproving:{
            type:'text',
            name:"clunkSoundwithNeckNotImproving"
          },
          clunkSoundwithNeckGettingWorse:{
            type:'text',
            name:"clunkSoundwithNeckGettingWorse"
          },

          neckPainNever:{
            type:'text',
            name:"neckPainNever"
          },
          neckPainHealed:{
            type:'text',
            name:"neckPainHealed"
          },
          neckPainStillHave:{
            type:'text',
            name:"neckPainStillHave"
          },
          neckPainImprovedLittle:{
            type:'text',
            name:"neckPainImprovedLittle"
          },
          neckPainImprovedMedium:{
            type:'text',
            name:"neckPainImprovedMedium"
          },
          neckPainImprovedLot:{
            type:'text',
            name:"neckPainImprovedLot"
          },
          neckPainNotImproving:{
            type:'text',
            name:"neckPainNotImproving"
          },
          neckPainGettingWorse:{
            type:'text',
            name:"neckPainGettingWorse"
          },

          upperBackPainNever:{
            type:'text',
            name:"upperBackPainNever"
          },
          upperBackPainHealed:{
            type:'text',
            name:"upperBackPainHealed"
          },
          upperBackPainStillHave:{
            type:'text',
            name:"upperBackPainStillHave"
          },
          upperBackPainImprovedLittle:{
            type:'text',
            name:"upperBackPainImprovedLittle"
          },
          upperBackPainImprovedMedium:{
            type:'text',
            name:"upperBackPainImprovedMedium"
          },
          upperBackPainImprovedLot:{
            type:'text',
            name:"upperBackPainImprovedLot"
          },
          upperBackPainNotImproving:{
            type:'text',
            name:"upperBackPainNotImproving"
          },
          upperBackPainGettingWorse:{
            type:'text',
            name:"upperBackPainGettingWorse"
          },

          lowBackPainNever:{
            type:'text',
            name:"lowBackPainNever"
          },
          lowBackPainHealed:{
            type:'text',
            name:"lowBackPainHealed"
          },
          lowBackPainStillHave:{
            type:'text',
            name:"lowBackPainStillHave"
          },
          lowBackPainImprovedLittle:{
            type:'text',
            name:"lowBackPainImprovedLittle"
          },
          lowBackPainImprovedMedium:{
            type:'text',
            name:"lowBackPainImprovedMedium"
          },
          lowBackPainImprovedLot:{
            type:'text',
            name:"lowBackPainImprovedLot"
          },
          lowBackPainNotImproving:{
            type:'text',
            name:"lowBackPainNotImproving"
          },
          lowBackPainGettingWorse:{
            type:'text',
            name:"lowBackPainGettingWorse"
          },

          
          shoulderPainLeftNever:{
            type:'text',
            name:"shoulderPainLeftNever"
          },
          shoulderPainLeftHealed:{
            type:'text',
            name:"shoulderPainLeftHealed"
          },
          shoulderPainLeftStillHave:{
            type:'text',
            name:"shoulderPainLeftStillHave"
          },
          shoulderPainLeftImprovedLittle:{
            type:'text',
            name:"shoulderPainLeftImprovedLittle"
          },
          shoulderPainLeftImprovedMedium:{
            type:'text',
            name:"shoulderPainLeftImprovedMedium"
          },
          shoulderPainLeftImprovedLot:{
            type:'text',
            name:"shoulderPainLeftImprovedLot"
          },
          shoulderPainLeftNotImproving:{
            type:'text',
            name:"shoulderPainLeftNotImproving"
          },
          shoulderPainLeftGettingWorse:{
            type:'text',
            name:"shoulderPainLeftGettingWorse"
          },

          shoulderPainRightNever:{
            type:'text',
            name:"shoulderPainRightNever"
          },
          shoulderPainRightHealed:{
            type:'text',
            name:"shoulderPainRightHealed"
          },
          shoulderPainRightStillHave:{
            type:'text',
            name:"shoulderPainRightStillHave"
          },
          shoulderPainRightImprovedLittle:{
            type:'text',
            name:"shoulderPainRightImprovedLittle"
          },
          shoulderPainRightImprovedMedium:{
            type:'text',
            name:"shoulderPainRightImprovedMedium"
          },
          shoulderPainRightImprovedLot:{
            type:'text',
            name:"shoulderPainRightImprovedLot"
          },
          shoulderPainRightNotImproving:{
            type:'text',
            name:"shoulderPainRightNotImproving"
          },
          shoulderPainRightGettingWorse:{
            type:'text',
            name:"shoulderPainRightGettingWorse"
          },

          //kk

          elbowPainLeftNever:{
            type:'text',
            name:"elbowPainLeftNever"
          },
          elbowPainLeftHealed:{
            type:'text',
            name:"elbowPainLeftHealed"
          },
          elbowPainLeftStillHave:{
            type:'text',
            name:"elbowPainLeftStillHave"
          },
          elbowPainLeftImprovedLittle:{
            type:'text',
            name:"elbowPainLeftImprovedLittle"
          },
          elbowPainLeftImprovedMedium:{
            type:'text',
            name:"elbowPainLeftImprovedMedium"
          },
          elbowPainLeftImprovedLot:{
            type:'text',
            name:"elbowPainLeftImprovedLot"
          },
          elbowPainLeftNotImproving:{
            type:'text',
            name:"elbowPainLeftNotImproving"
          },
          elbowPainLeftGettingWorse:{
            type:'text',
            name:"elbowPainLeftGettingWorse"
          },


          elbowPainRightNever:{
            type:'text',
            name:"elbowPainRightNever"
          },
          elbowPainRightHealed:{
            type:'text',
            name:"elbowPainRightHealed"
          },
          elbowPainRightStillHave:{
            type:'text',
            name:"elbowPainRightStillHave"
          },
          elbowPainRightImprovedLittle:{
            type:'text',
            name:"elbowPainRightImprovedLittle"
          },
          elbowPainRightImprovedMedium:{
            type:'text',
            name:"elbowPainRightImprovedMedium"
          },
          elbowPainRightImprovedLot:{
            type:'text',
            name:"elbowPainRightImprovedLot"
          },
          elbowPainRightNotImproving:{
            type:'text',
            name:"elbowPainRightNotImproving"
          },
          elbowPainRightGettingWorse:{
            type:'text',
            name:"elbowPainRightGettingWorse"
          },


          wristPainLeftNever:{
            type:'text',
            name:"wristPainLeftNever"
          },
          wristPainLeftHealed:{
            type:'text',
            name:"wristPainLeftHealed"
          },
          wristPainLeftStillHave:{
            type:'text',
            name:"wristPainLeftStillHave"
          },
          wristPainLeftImprovedLittle:{
            type:'text',
            name:"wristPainLeftImprovedLittle"
          },
          wristPainLeftImprovedMedium:{
            type:'text',
            name:"wristPainLeftImprovedMedium"
          },
          wristPainLeftImprovedLot:{
            type:'text',
            name:"wristPainLeftImprovedLot"
          },
          wristPainLeftNotImproving:{
            type:'text',
            name:"wristPainLeftNotImproving"
          },
          wristPainLeftGettingWorse:{
            type:'text',
            name:"wristPainLeftGettingWorse"
          },


          wristPainRightNever:{
            type:'text',
            name:"wristPainRightNever"
          },
          wristPainRightHealed:{
            type:'text',
            name:"wristPainRightHealed"
          },
          wristPainRightStillHave:{
            type:'text',
            name:"wristPainRightStillHave"
          },
          wristPainRightImprovedLittle:{
            type:'text',
            name:"wristPainRightImprovedLittle"
          },
          wristPainRightImprovedMedium:{
            type:'text',
            name:"wristPainRightImprovedMedium"
          },
          wristPainRightImprovedLot:{
            type:'text',
            name:"wristPainRightImprovedLot"
          },
          wristPainRightNotImproving:{
            type:'text',
            name:"wristPainRightNotImproving"
          },
          wristPainRightGettingWorse:{
            type:'text',
            name:"wristPainRightGettingWorse"
          },

          handfingerPainLeftNever:{
            type:'text',
            name:"handfingerPainLeftNever"
          },
          handfingerPainLeftHealed:{
            type:'text',
            name:"handfingerPainLeftHealed"
          },
          handfingerPainLeftStillHave:{
            type:'text',
            name:"handfingerPainLeftStillHave"
          },
          handfingerPainLeftImprovedLittle:{
            type:'text',
            name:"handfingerPainLeftImprovedLittle"
          },
          handfingerPainLeftImprovedMedium:{
            type:'text',
            name:"handfingerPainLeftImprovedMedium"
          },
          handfingerPainLeftImprovedLot:{
            type:'text',
            name:"handfingerPainLeftImprovedLot"
          },
          handfingerPainLeftNotImproving:{
            type:'text',
            name:"handfingerPainLeftNotImproving"
          },
          handfingerPainLeftGettingWorse:{
            type:'text',
            name:"handfingerPainLeftGettingWorse"
          },

          handfingerPainRightNever:{
            type:'text',
            name:"handfingerPainRightNever"
          },
          handfingerPainRightHealed:{
            type:'text',
            name:"handfingerPainRightHealed"
          },
          handfingerPainRightStillHave:{
            type:'text',
            name:"handfingerPainRightStillHave"
          },
          handfingerPainRightImprovedLittle:{
            type:'text',
            name:"handfingerPainRightImprovedLittle"
          },
          handfingerPainRightImprovedMedium:{
            type:'text',
            name:"handfingerPainRightImprovedMedium"
          },
          handfingerPainRightImprovedLot:{
            type:'text',
            name:"handfingerPainRightImprovedLot"
          },
          handfingerPainRightNotImproving:{
            type:'text',
            name:"handfingerPainRightNotImproving"
          },
          handfingerPainRightGettingWorse:{
            type:'text',
            name:"handfingerPainRightGettingWorse"
          },

          hipPainLeftNever:{
            type:'text',
            name:"hipPainLeftNever"
          },
          hipPainLeftHealed:{
            type:'text',
            name:"hipPainLeftHealed"
          },
          hipPainLeftStillHave:{
            type:'text',
            name:"hipPainLeftStillHave"
          },
          hipPainLeftImprovedLittle:{
            type:'text',
            name:"hipPainLeftImprovedLittle"
          },
          hipPainLeftImprovedMedium:{
            type:'text',
            name:"hipPainLeftImprovedMedium"
          },
          hipPainLeftImprovedLot:{
            type:'text',
            name:"hipPainLeftImprovedLot"
          },
          hipPainLeftNotImproving:{
            type:'text',
            name:"hipPainLeftNotImproving"
          },
          hipPainLeftGettingWorse:{
            type:'text',
            name:"hipPainLeftGettingWorse"
          },

          hipPainRightNever:{
            type:'text',
            name:"hipPainRightNever"
          },
          hipPainRightHealed:{
            type:'text',
            name:"hipPainRightHealed"
          },
          hipPainRightStillHave:{
            type:'text',
            name:"hipPainRightStillHave"
          },
          hipPainRightImprovedLittle:{
            type:'text',
            name:"hipPainRightImprovedLittle"
          },
          hipPainRightImprovedMedium:{
            type:'text',
            name:"hipPainRightImprovedMedium"
          },
          hipPainRightImprovedLot:{
            type:'text',
            name:"hipPainRightImprovedLot"
          },
          hipPainRightNotImproving:{
            type:'text',
            name:"hipPainRightNotImproving"
          },
          hipPainRightGettingWorse:{
            type:'text',
            name:"hipPainRightGettingWorse"
          },

          kneePainLeftNever:{
            type:'text',
            name:"wristPainRightNever"
          },
          kneePainLeftHealed:{
            type:'text',
            name:"kneePainLeftHealed"
          },
          kneePainLeftStillHave:{
            type:'text',
            name:"kneePainLeftStillHave"
          },
          kneePainLeftImprovedLittle:{
            type:'text',
            name:"kneePainLeftImprovedLittle"
          },
          kneePainLeftImprovedMedium:{
            type:'text',
            name:"kneePainLeftImprovedMedium"
          },
          kneePainLeftImprovedLot:{
            type:'text',
            name:"kneePainLeftImprovedLot"
          },
          kneePainLeftNotImproving:{
            type:'text',
            name:"kneePainLeftNotImproving"
          },
          kneePainLeftGettingWorse:{
            type:'text',
            name:"kneePainLeftGettingWorse"
          },

          kneePainRightNever:{
            type:'text',
            name:"kneePainRightNever"
          },
          kneePainRightHealed:{
            type:'text',
            name:"kneePainRightHealed"
          },
          kneePainRightStillHave:{
            type:'text',
            name:"kneePainRightStillHave"
          },
          kneePainRightImprovedLittle:{
            type:'text',
            name:"kneePainRightImprovedLittle"
          },
          kneePainRightImprovedMedium:{
            type:'text',
            name:"kneePainRightImprovedMedium"
          },
          kneePainRightImprovedLot:{
            type:'text',
            name:"kneePainRightImprovedLot"
          },
          kneePainRightNotImproving:{
            type:'text',
            name:"kneePainRightNotImproving"
          },
          kneePainRightGettingWorse:{
            type:'text',
            name:"kneePainRightGettingWorse"
          },



          ankleFootpainLeftNever:{
            type:'text',
            name:"ankleFootpainLeftNever"
          },
          ankleFootpainLeftHealed:{
            type:'text',
            name:"ankleFootpainLeftHealed"
          },
          ankleFootpainLeftStillHave:{
            type:'text',
            name:"ankleFootpainLeftStillHave"
          },
          ankleFootpainLeftImprovedLittle:{
            type:'text',
            name:"ankleFootpainLeftImprovedLittle"
          },
          ankleFootpainLeftImprovedMedium:{
            type:'text',
            name:"ankleFootpainLeftImprovedMedium"
          },
          ankleFootpainLeftImprovedLot:{
            type:'text',
            name:"ankleFootpainLeftImprovedLot"
          },
          ankleFootpainLeftNotImproving:{
            type:'text',
            name:"ankleFootpainLeftNotImproving"
          },
          ankleFootpainLeftGettingWorse:{
            type:'text',
            name:"ankleFootpainLeftGettingWorse"
          },

          ankleFootpainRightNever:{
            type:'text',
            name:"ankleFootpainRightNever"
          },
          ankleFootpainRightHealed:{
            type:'text',
            name:"ankleFootpainRightHealed"
          },
          ankleFootpainRightStillHave:{
            type:'text',
            name:"ankleFootpainRightStillHave"
          },
          ankleFootpainRightImprovedLittle:{
            type:'text',
            name:"ankleFootpainRightImprovedLittle"
          },
          ankleFootpainRightImprovedMedium:{
            type:'text',
            name:"ankleFootpainRightImprovedMedium"
          },
          ankleFootpainRightImprovedLot:{
            type:'text',
            name:"ankleFootpainRightImprovedLot"
          },
          ankleFootpainRightNotImproving:{
            type:'text',
            name:"ankleFootpainRightNotImproving"
          },
          ankleFootpainRightGettingWorse:{
            type:'text',
            name:"ankleFootpainRightGettingWorse"
          },

          jawChewingPainLeftNever:{
            type:'text',
            name:"jawChewingPainLeftNever"
          },
          jawChewingPainLeftHealed:{
            type:'text',
            name:"jawChewingPainLeftHealed"
          },
          jawChewingPainLeftStillHave:{
            type:'text',
            name:"jawChewingPainLeftStillHave"
          },
          jawChewingPainLeftImprovedLittle:{
            type:'text',
            name:"jawChewingPainLeftImprovedLittle"
          },
          jawChewingPainLeftImprovedMedium:{
            type:'text',
            name:"jawChewingPainLeftImprovedMedium"
          },
          jawChewingPainLeftImprovedLot:{
            type:'text',
            name:"jawChewingPainLeftImprovedLot"
          },
          jawChewingPainLeftNotImproving:{
            type:'text',
            name:"jawChewingPainLeftNotImproving"
          },
          jawChewingPainLeftGettingWorse:{
            type:'text',
            name:"jawChewingPainLeftGettingWorse"
          },

          jawChewingPainRightNever:{
            type:'text',
            name:"jawChewingPainRightNever"
          },
          jawChewingPainRightHealed:{
            type:'text',
            name:"jawChewingPainRightHealed"
          },
          jawChewingPainRightStillHave:{
            type:'text',
            name:"jawChewingPainRightStillHave"
          },
          jawChewingPainRightImprovedLittle:{
            type:'text',
            name:"jawChewingPainRightImprovedLittle"
          },
          jawChewingPainRightImprovedMedium:{
            type:'text',
            name:"jawChewingPainRightImprovedMedium"
          },
          jawChewingPainRightImprovedLot:{
            type:'text',
            name:"jawChewingPainRightImprovedLot"
          },
          jawChewingPainRightNotImproving:{
            type:'text',
            name:"jawChewingPainRightNotImproving"
          },
          jawChewingPainRightGettingWorse:{
            type:'text',
            name:"jawChewingPainRightGettingWorse"
          },

          facePainNever:{
            type:'text',
            name:"facePainNever"
          },
          facePainHealed:{
            type:'text',
            name:"facePainHealed"
          },
          facePainStillHave:{
            type:'text',
            name:"facePainStillHave"
          },
          facePainImprovedLittle:{
            type:'text',
            name:"facePainImprovedLittle"
          },
          facePainImprovedMedium:{
            type:'text',
            name:"facePainImprovedMedium"
          },
          facePainImprovedLot:{
            type:'text',
            name:"facePainImprovedLot"
          },
          facePainNotImproving:{
            type:'text',
            name:"facePainNotImproving"
          },
          facePainGettingWorse:{
            type:'text',
            name:"facePainGettingWorse"
          },

          chestribsPainNever:{
            type:'text',
            name:"chestribsPainNever"
          },
          chestribsPainHealed:{
            type:'text',
            name:"chestribsPainHealed"
          },
          chestribsPainStillHave:{
            type:'text',
            name:"chestribsPainStillHave"
          },
          chestribsPainImprovedLittle:{
            type:'text',
            name:"chestribsPainImprovedLittle"
          },
          chestribsPainImprovedMedium:{
            type:'text',
            name:"chestribsPainImprovedMedium"
          },
          chestribsPainImprovedLot:{
            type:'text',
            name:"chestribsPainImprovedLot"
          },
          chestribsPainNotImproving:{
            type:'text',
            name:"chestribsPainNotImproving"
          },
          chestribsPainGettingWorse:{
            type:'text',
            name:"chestribsPainGettingWorse"
          },

          stomachPainNever:{
            type:'text',
            name:"stomachPainNever"
          },
          stomachPainHealed:{
            type:'text',
            name:"stomachPainHealed"
          },
          stomachPainStillHave:{
            type:'text',
            name:"stomachPainStillHave"
          },
          stomachPainImprovedLittle:{
            type:'text',
            name:"stomachPainImprovedLittle"
          },
          stomachPainImprovedMedium:{
            type:'text',
            name:"stomachPainImprovedMedium"
          },
          stomachPainImprovedLot:{
            type:'text',
            name:"stomachPainImprovedLot"
          },
          stomachPainNotImproving:{
            type:'text',
            name:"stomachPainNotImproving"
          },
          stomachPainGettingWorse:{
            type:'text',
            name:"stomachPainGettingWorse"
          },

          BrnisesonNever:{
            type:'text',
            name:"BrnisesonNever"
          },
          BrnisesonHealed:{
            type:'text',
            name:"BrnisesonHealed"
          },
          BrnisesonStillHave:{
            type:'text',
            name:"BrnisesonStillHave"
          },
          BrnisesonImprovedLittle:{
            type:'text',
            name:"BrnisesonImprovedLittle"
          },
          BrnisesonImprovedMedium:{
            type:'text',
            name:"BrnisesonImprovedMedium"
          },
          BrnisesonImprovedLot:{
            type:'text',
            name:"BrnisesonImprovedLot"
          },
          BrnisesonNotImproving:{
            type:'text',
            name:"BrnisesonNotImproving"
          },
          BrnisesonGettingWorse:{
            type:'text',
            name:"BrnisesonGettingWorse"
          },

          cutsscrapesOnNever:{
            type:'text',
            name:"cutsscrapesOnNever"
          },
          cutsscrapesOnHealed:{
            type:'text',
            name:"cutsscrapesOnHealed"
          },
          cutsscrapesOnStillHave:{
            type:'text',
            name:"cutsscrapesOnStillHave"
          },
          cutsscrapesOnImprovedLittle:{
            type:'text',
            name:"cutsscrapesOnImprovedLittle"
          },
          cutsscrapesOnImprovedMedium:{
            type:'text',
            name:"cutsscrapesOnImprovedMedium"
          },
          cutsscrapesOnImprovedLot:{
            type:'text',
            name:"cutsscrapesOnImprovedLot"
          },
          cutsscrapesOnNotImproving:{
            type:'text',
            name:"cutsscrapesOnNotImproving"
          },
          cutsscrapesOnGettingWorse:{
            type:'text',
            name:"cutsscrapesOnGettingWorse"
          },

          scarsOnNever:{
            type:'text',
            name:"scarsOnNever"
          },
          scarsOnHealed:{
            type:'text',
            name:"scarsOnHealed"
          },
          scarsOnStillHave:{
            type:'text',
            name:"scarsOnStillHave"
          },
          scarsOnImprovedLittle:{
            type:'text',
            name:"scarsOnImprovedLittle"
          },
          scarsOnImprovedMedium:{
            type:'text',
            name:"scarsOnImprovedMedium"
          },
          scarsOnImprovedLot:{
            type:'text',
            name:"scarsOnImprovedLot"
          },
          scarsOnNotImproving:{
            type:'text',
            name:"scarsOnNotImproving"
          },
          scarsOnGettingWorse:{
            type:'text',
            name:"scarsOnGettingWorse"
          },

          numbtinglingArmHandLeftNever:{
            type:'text',
            name:"numbtinglingArmHandLeftNever"
          },
          numbtinglingArmHandLeftHealed:{
            type:'text',
            name:"numbtinglingArmHandLeftHealed"
          },
          numbtinglingArmHandLeftStillHave:{
            type:'text',
            name:"numbtinglingArmHandLeftStillHave"
          },
          numbtinglingArmHandLeftImprovedLittle:{
            type:'text',
            name:"numbtinglingArmHandLeftImprovedLittle"
          },
          numbtinglingArmHandLeftImprovedMedium:{
            type:'text',
            name:"numbtinglingArmHandLeftImprovedMedium"
          },
          numbtinglingArmHandLeftImprovedLot:{
            type:'text',
            name:"numbtinglingArmHandLeftImprovedLot"
          },
          numbtinglingArmHandLeftNotImproving:{
            type:'text',
            name:"numbtinglingArmHandLeftNotImproving"
          },
          numbtinglingArmHandLeftGettingWorse:{
            type:'text',
            name:"numbtinglingArmHandLeftGettingWorse"
          },

          numbtinglingArmHandRightNever:{
            type:'text',
            name:"numbtinglingArmHandRightNever"
          },
          numbtinglingArmHandRightHealed:{
            type:'text',
            name:"numbtinglingArmHandRightHealed"
          },
          numbtinglingArmHandRightStillHave:{
            type:'text',
            name:"numbtinglingArmHandRightStillHave"
          },
          numbtinglingArmHandRightImprovedLittle:{
            type:'text',
            name:"numbtinglingArmHandRightImprovedLittle"
          },
          numbtinglingArmHandRightImprovedMedium:{
            type:'text',
            name:"numbtinglingArmHandRightImprovedMedium"
          },
          numbtinglingArmHandRightImprovedLot:{
            type:'text',
            name:"numbtinglingArmHandRightImprovedLot"
          },
          numbtinglingArmHandRightNotImproving:{
            type:'text',
            name:"numbtinglingArmHandRightNotImproving"
          },
          numbtinglingArmHandRightGettingWorse:{
            type:'text',
            name:"numbtinglingArmHandRightGettingWorse"
          },

          numbtinglingLegFootLeftNever:{
            type:'text',
            name:"numbtinglingLegFootLeftNever"
          },
          numbtinglingLegFootLeftHealed:{
            type:'text',
            name:"numbtinglingLegFootLeftHealed"
          },
          numbtinglingLegFootLeftStillHave:{
            type:'text',
            name:"numbtinglingLegFootLeftStillHave"
          },
          numbtinglingLegFootLeftImprovedLittle:{
            type:'text',
            name:"numbtinglingLegFootLeftImprovedLittle"
          },
          numbtinglingLegFootLeftImprovedMedium:{
            type:'text',
            name:"numbtinglingLegFootLeftImprovedMedium"
          },
          numbtinglingLegFootLeftImprovedLot:{
            type:'text',
            name:"numbtinglingLegFootLeftImprovedLot"
          },
          numbtinglingLegFootLeftNotImproving:{
            type:'text',
            name:"numbtinglingLegFootLeftNotImproving"
          },
          numbtinglingLegFootLeftGettingWorse:{
            type:'text',
            name:"numbtinglingLegFootLeftGettingWorse"
          },

          numbtinglingLegFootRightNever:{
            type:'text',
            name:"numbtinglingLegFootRightNever"
          },
          numbtinglingLegFootRightHealed:{
            type:'text',
            name:"numbtinglingLegFootRightHealed"
          },
          numbtinglingLegFootRightStillHave:{
            type:'text',
            name:"numbtinglingLegFootRightStillHave"
          },
          numbtinglingLegFootRightImprovedLittle:{
            type:'text',
            name:"numbtinglingLegFootRightImprovedLittle"
          },
          numbtinglingLegFootRightImprovedMedium:{
            type:'text',
            name:"numbtinglingLegFootRightImprovedMedium"
          },
          numbtinglingLegFootRightImprovedLot:{
            type:'text',
            name:"numbtinglingLegFootRightImprovedLot"
          },
          numbtinglingLegFootRightNotImproving:{
            type:'text',
            name:"numbtinglingLegFootRightNotImproving"
          },
          numbtinglingLegFootRightGettingWorse:{
            type:'text',
            name:"numbtinglingLegFootRightGettingWorse"
          },

          weakclumsyArmHandLeftNever:{
            type:'text',
            name:"weakclumsyArmHandLeftNever"
          },
          weakclumsyArmHandLeftHealed:{
            type:'text',
            name:"weakclumsyArmHandLeftHealed"
          },
          weakclumsyArmHandLeftStillHave:{
            type:'text',
            name:"weakclumsyArmHandLeftStillHave"
          },
          weakclumsyArmHandLeftImprovedLittle:{
            type:'text',
            name:"weakclumsyArmHandLeftImprovedLittle"
          },
          weakclumsyArmHandLeftImprovedMedium:{
            type:'text',
            name:"weakclumsyArmHandLeftImprovedMedium"
          },
          weakclumsyArmHandLeftImprovedLot:{
            type:'text',
            name:"weakclumsyArmHandLeftImprovedLot"
          },
          weakclumsyArmHandLeftNotImproving:{
            type:'text',
            name:"weakclumsyArmHandLeftNotImproving"
          },
          weakclumsyArmHandLeftGettingWorse:{
            type:'text',
            name:"weakclumsyArmHandLeftGettingWorse"
          },

          weakclumsyArmHandRightNever:{
            type:'text',
            name:"weakclumsyArmHandRightNever"
          },
          weakclumsyArmHandRightHealed:{
            type:'text',
            name:"weakclumsyArmHandRightHealed"
          },
          weakclumsyArmHandRightStillHave:{
            type:'text',
            name:"weakclumsyArmHandRightStillHave"
          },
          weakclumsyArmHandRightImprovedLittle:{
            type:'text',
            name:"weakclumsyArmHandRightImprovedLittle"
          },
          weakclumsyArmHandRightImprovedMedium:{
            type:'text',
            name:"weakclumsyArmHandRightImprovedMedium"
          },
          weakclumsyArmHandRightImprovedLot:{
            type:'text',
            name:"weakclumsyArmHandRightImprovedLot"
          },
          weakclumsyArmHandRightNotImproving:{
            type:'text',
            name:"weakclumsyArmHandRightNotImproving"
          },
          weakclumsyArmHandRightGettingWorse:{
            type:'text',
            name:"weakclumsyArmHandRightGettingWorse"
          },

          weakclumsyLegFootLeftNever:{
            type:'text',
            name:"weakclumsyLegFootLeftNever"
          },
          weakclumsyLegFootLeftHealed:{
            type:'text',
            name:"weakclumsyLegFootLeftHealed"
          },
          weakclumsyLegFootLeftStillHave:{
            type:'text',
            name:"weakclumsyLegFootLeftStillHave"
          },
          weakclumsyLegFootLeftImprovedLittle:{
            type:'text',
            name:"weakclumsyLegFootLeftImprovedLittle"
          },
          weakclumsyLegFootLeftImprovedMedium:{
            type:'text',
            name:"weakclumsyLegFootLeftImprovedMedium"
          },
          weakclumsyLegFootLeftImprovedLot:{
            type:'text',
            name:"weakclumsyLegFootLeftImprovedLot"
          },
          weakclumsyLegFootLeftNotImproving:{
            type:'text',
            name:"weakclumsyLegFootLeftNotImproving"
          },
          weakclumsyLegFootLeftGettingWorse:{
            type:'text',
            name:"weakclumsyLegFootLeftGettingWorse"
          },

          weakclumsyLegFootRightNever:{
            type:'text',
            name:"weakclumsyLegFootRightNever"
          },
          weakclumsyLegFootRightHealed:{
            type:'text',
            name:"weakclumsyLegFootRightHealed"
          },
          weakclumsyLegFootRightStillHave:{
            type:'text',
            name:"weakclumsyLegFootRightStillHave"
          },
          weakclumsyLegFootRightImprovedLittle:{
            type:'text',
            name:"weakclumsyLegFootRightImprovedLittle"
          },
          weakclumsyLegFootRightImprovedMedium:{
            type:'text',
            name:"weakclumsyLegFootRightImprovedMedium"
          },
          weakclumsyLegFootRightImprovedLot:{
            type:'text',
            name:"weakclumsyLegFootRightImprovedLot"
          },
          weakclumsyLegFootRightNotImproving:{
            type:'text',
            name:"weakclumsyLegFootRightNotImproving"
          },
          weakclumsyLegFootRightGettingWorse:{
            type:'text',
            name:"weakclumsyLegFootRightGettingWorse"
          },

          
          stiffnessInJointsNever:{
            type:'text',
            name:"stiffnessInJointsNever"
          },
          stiffnessInJointsHealed:{
            type:'text',
            name:"stiffnessInJointsHealed"
          },
          stiffnessInJointsStillHave:{
            type:'text',
            name:"stiffnessInJointsStillHave"
          },
          stiffnessInJointsImprovedLittle:{
            type:'text',
            name:"stiffnessInJointsImprovedLittle"
          },
          stiffnessInJointsImprovedMedium:{
            type:'text',
            name:"stiffnessInJointsImprovedMedium"
          },
          stiffnessInJointsImprovedLot:{
            type:'text',
            name:"stiffnessInJointsImprovedLot"
          },
          stiffnessInJointsNotImproving:{
            type:'text',
            name:"stiffnessInJointsNotImproving"
          },
          stiffnessInJointsGettingWorse:{
            type:'text',
            name:"stiffnessInJointsGettingWorse"
          },

          
          headachesNever:{
            type:'text',
            name:"headachesNever"
          },
          headachesHealed:{
            type:'text',
            name:"headachesHealed"
          },
          headachesStillHave:{
            type:'text',
            name:"headachesStillHave"
          },
          headachesImprovedLittle:{
            type:'text',
            name:"headachesImprovedLittle"
          },
          headachesImprovedMedium:{
            type:'text',
            name:"headachesImprovedMedium"
          },
          headachesImprovedLot:{
            type:'text',
            name:"headachesImprovedLot"
          },
          headachesNotImproving:{
            type:'text',
            name:"headachesNotImproving"
          },
          headachesGettingWorse:{
            type:'text',
            name:"headachesGettingWorse"
          },

          
          SoreorSpasmInMusclesNever:{
            type:'text',
            name:"SoreorSpasmInMusclesNever"
          },
          SoreorSpasmInMusclesHealed:{
            type:'text',
            name:"SoreorSpasmInMusclesHealed"
          },
          SoreorSpasmInMusclesStillHave:{
            type:'text',
            name:"SoreorSpasmInMusclesStillHave"
          },
          SoreorSpasmInMusclesImprovedLittle:{
            type:'text',
            name:"SoreorSpasmInMusclesImprovedLittle"
          },
          SoreorSpasmInMusclesImprovedMedium:{
            type:'text',
            name:"SoreorSpasmInMusclesImprovedMedium"
          },
          SoreorSpasmInMusclesImprovedLot:{
            type:'text',
            name:"SoreorSpasmInMusclesImprovedLot"
          },
          SoreorSpasmInMusclesNotImproving:{
            type:'text',
            name:"SoreorSpasmInMusclesNotImproving"
          },
          SoreorSpasmInMusclesGettingWorse:{
            type:'text',
            name:"SoreorSpasmInMusclesGettingWorse"
          },

          
          lightheadedNever:{
            type:'text',
            name:"lightheadedNever"
          },
          lightheadedHealed:{
            type:'text',
            name:"lightheadedHealed"
          },
          lightheadedStillHave:{
            type:'text',
            name:"lightheadedStillHave"
          },
          lightheadedImprovedLittle:{
            type:'text',
            name:"lightheadedImprovedLittle"
          },
          lightheadedImprovedMedium:{
            type:'text',
            name:"lightheadedImprovedMedium"
          },
          lightheadedImprovedLot:{
            type:'text',
            name:"lightheadedImprovedLot"
          },
          lightheadedNotImproving:{
            type:'text',
            name:"lightheadedNotImproving"
          },
          lightheadedGettingWorse:{
            type:'text',
            name:"lightheadedGettingWorse"
          },

          
          visionChangesNever:{
            type:'text',
            name:"visionChangesNever"
          },
          visionChangesHealed:{
            type:'text',
            name:"visionChangesHealed"
          },
          visionChangesStillHave:{
            type:'text',
            name:"visionChangesStillHave"
          },
          visionChangesImprovedLittle:{
            type:'text',
            name:"visionChangesImprovedLittle"
          },
          visionChangesImprovedMedium:{
            type:'text',
            name:"visionChangesImprovedMedium"
          },
          visionChangesImprovedLot:{
            type:'text',
            name:"visionChangesImprovedLot"
          },
          visionChangesNotImproving:{
            type:'text',
            name:"visionChangesNotImproving"
          },
          visionChangesGettingWorse:{
            type:'text',
            name:"visionChangesGettingWorse"
          },

          
          sleepChangesNever:{
            type:'text',
            name:"sleepChangesNever"
          },
          sleepChangesHealed:{
            type:'text',
            name:"sleepChangesHealed"
          },
          sleepChangesStillHave:{
            type:'text',
            name:"sleepChangesStillHave"
          },
          sleepChangesImprovedLittle:{
            type:'text',
            name:"sleepChangesImprovedLittle"
          },
          sleepChangesImprovedMedium:{
            type:'text',
            name:"sleepChangesImprovedMedium"
          },
          sleepChangesImprovedLot:{
            type:'text',
            name:"sleepChangesImprovedLot"
          },
          sleepChangesNotImproving:{
            type:'text',
            name:"sleepChangesNotImproving"
          },
          sleepChangesGettingWorse:{
            type:'text',
            name:"sleepChangesGettingWorse"
          },

          
          radiatingPainNever:{
            type:'text',
            name:"radiatingPainNever"
          },
          radiatingPainHealed:{
            type:'text',
            name:"radiatingPainHealed"
          },
          radiatingPainStillHave:{
            type:'text',
            name:"radiatingPainStillHave"
          },
          radiatingPainImprovedLittle:{
            type:'text',
            name:"radiatingPainImprovedLittle"
          },
          radiatingPainImprovedMedium:{
            type:'text',
            name:"radiatingPainImprovedMedium"
          },
          radiatingPainImprovedLot:{
            type:'text',
            name:"radiatingPainImprovedLot"
          },
          radiatingPainNotImproving:{
            type:'text',
            name:"radiatingPainNotImproving"
          },
          radiatingPainGettingWorse:{
            type:'text',
            name:"radiatingPainGettingWorse"
          },

          
          anxietyNever:{
            type:'text',
            name:"anxietyNever"
          },
          anxietyHealed:{
            type:'text',
            name:"anxietyHealed"
          },
          anxietyStillHave:{
            type:'text',
            name:"anxietyStillHave"
          },
          anxietyImprovedLittle:{
            type:'text',
            name:"anxietyImprovedLittle"
          },
          anxietyImprovedMedium:{
            type:'text',
            name:"anxietyImprovedMedium"
          },
          anxietyImprovedLot:{
            type:'text',
            name:"anxietyImprovedLot"
          },
          anxietyNotImproving:{
            type:'text',
            name:"anxietyNotImproving"
          },
          anxietyGettingWorse:{
            type:'text',
            name:"anxietyGettingWorse"
          },

          
          lackOfEnthusiasmNever:{
            type:'text',
            name:"lackOfEnthusiasmNever"
          },
          lackOfEnthusiasmHealed:{
            type:'text',
            name:"lackOfEnthusiasmHealed"
          },
          lackOfEnthusiasmStillHave:{
            type:'text',
            name:"lackOfEnthusiasmStillHave"
          },
          lackOfEnthusiasmImprovedLittle:{
            type:'text',
            name:"lackOfEnthusiasmImprovedLittle"
          },
          lackOfEnthusiasmImprovedMedium:{
            type:'text',
            name:"lackOfEnthusiasmImprovedMedium"
          },
          lackOfEnthusiasmImprovedLot:{
            type:'text',
            name:"lackOfEnthusiasmImprovedLot"
          },
          lackOfEnthusiasmNotImproving:{
            type:'text',
            name:"lackOfEnthusiasmNotImproving"
          },
          lackOfEnthusiasmGettingWorse:{
            type:'text',
            name:"lackOfEnthusiasmGettingWorse"
          },

          medicationsNever:{
            type:'text',
            name:"medicationsNever"
          },

          PatientSignature:{
            type:'text',
            name:"PatientSignature"
          },
          DrSignature:{
            type:'text',
            name:"DrSignature"
          },

        
        }
    }
    
    export default form;