import moment from "moment";
import checkout from "./form";

const {
  formField: {
    clunkSoundwithNeckNever,
    clunkSoundwithNeckHealed,
    clunkSoundwithNeckStillHave,
    clunkSoundwithNeckImprovedLittle,
    clunkSoundwithNeckImprovedMedium,
    clunkSoundwithNeckImprovedLot,
    clunkSoundwithNeckNotImproving,
    clunkSoundwithNeckGettingWorse,

    neckPainNever,
    neckPainHealed,
    neckPainStillHave,
    neckPainImprovedLittle,
    neckPainImprovedMedium,
    neckPainImprovedLot,
    neckPainNotImproving,
    neckPainGettingWorse,

    upperBackPainNever,
    upperBackPainHealed,
    upperBackPainStillHave,
    upperBackPainImprovedLittle,
    upperBackPainImprovedMedium,
    upperBackPainImprovedLot,
    upperBackPainNotImproving,
    upperBackPainGettingWorse,

    lowBackPainNever,
    lowBackPainHealed,
    lowBackPainStillHave,
    lowBackPainImprovedLittle,
    lowBackPainImprovedMedium,
    lowBackPainImprovedLot,
    lowBackPainNotImproving,
    lowBackPainGettingWorse,

    shoulderPainLeftNever,
    shoulderPainLeftHealed,
    shoulderPainLeftStillHave,
    shoulderPainLeftImprovedLittle,
    shoulderPainLeftImprovedMedium,
    shoulderPainLeftImprovedLot,
    shoulderPainLeftNotImproving,
    shoulderPainLeftGettingWorse,

    shoulderPainRightNever,
    shoulderPainRightHealed,
    shoulderPainRightStillHave,
    shoulderPainRightImprovedLittle,
    shoulderPainRightImprovedMedium,
    shoulderPainRightImprovedLot,
    shoulderPainRightNotImproving,
    shoulderPainRightGettingWorse,

    elbowPainLeftNever,
    elbowPainLeftHealed,
    elbowPainLeftStillHave,
    elbowPainLeftImprovedLittle,
    elbowPainLeftImprovedMedium,
    elbowPainLeftImprovedLot,
    elbowPainLeftNotImproving,
    elbowPainLeftGettingWorse,

    elbowPainRightNever,
    elbowPainRightHealed,
    elbowPainRightStillHave,
    elbowPainRightImprovedLittle,
    elbowPainRightImprovedMedium,
    elbowPainRightImprovedLot,
    elbowPainRightNotImproving,
    elbowPainRightGettingWorse,

    wristPainLeftNever,
    wristPainLeftHealed,
    wristPainLeftStillHave,
    wristPainLeftImprovedLittle,
    wristPainLeftImprovedMedium,
    wristPainLeftImprovedLot,
    wristPainLeftNotImproving,
    wristPainLeftGettingWorse,

    wristPainRightNever,
    wristPainRightHealed,
    wristPainRightStillHave,
    wristPainRightImprovedLittle,
    wristPainRightImprovedMedium,
    wristPainRightImprovedLot,
    wristPainRightNotImproving,
    wristPainRightGettingWorse,

    handfingerPainLeftNever,
    handfingerPainLeftHealed,
    handfingerPainLeftStillHave,
    handfingerPainLeftImprovedLittle,
    handfingerPainLeftImprovedMedium,
    handfingerPainLeftImprovedLot,
    handfingerPainLeftNotImproving,
    handfingerPainLeftGettingWorse,

    handfingerPainRightNever,
    handfingerPainRightHealed,
    handfingerPainRightStillHave,
    handfingerPainRightImprovedLittle,
    handfingerPainRightImprovedMedium,
    handfingerPainRightImprovedLot,
    handfingerPainRightNotImproving,
    handfingerPainRightGettingWorse,

    hipPainLeftNever,
    hipPainLeftHealed,
    hipPainLeftStillHave,
    hipPainLeftImprovedLittle,
    hipPainLeftImprovedMedium,
    hipPainLeftImprovedLot,
    hipPainLeftNotImproving,
    hipPainLeftGettingWorse,

    hipPainRightNever,
    hipPainRightHealed,
    hipPainRightStillHave,
    hipPainRightImprovedLittle,
    hipPainRightImprovedMedium,
    hipPainRightImprovedLot,
    hipPainRightNotImproving,
    hipPainRightGettingWorse,

    kneePainLeftNever,
    kneePainLeftHealed,
    kneePainLeftStillHave,
    kneePainLeftImprovedLittle,
    kneePainLeftImprovedMedium,
    kneePainLeftImprovedLot,
    kneePainLeftNotImproving,
    kneePainLeftGettingWorse,

    kneePainRightNever,
    kneePainRightHealed,
    kneePainRightStillHave,
    kneePainRightImprovedLittle,
    kneePainRightImprovedMedium,
    kneePainRightImprovedLot,
    kneePainRightNotImproving,
    kneePainRightGettingWorse,

    ankleFootpainLeftNever,
    ankleFootpainLeftHealed,
    ankleFootpainLeftStillHave,
    ankleFootpainLeftImprovedLittle,
    ankleFootpainLeftImprovedMedium,
    ankleFootpainLeftImprovedLot,
    ankleFootpainLeftNotImproving,
    ankleFootpainLeftGettingWorse,

    ankleFootpainRightNever,
    ankleFootpainRightHealed,
    ankleFootpainRightStillHave,
    ankleFootpainRightImprovedLittle,
    ankleFootpainRightImprovedMedium,
    ankleFootpainRightImprovedLot,
    ankleFootpainRightNotImproving,
    ankleFootpainRightGettingWorse,

    jawChewingPainLeftNever,
    jawChewingPainLeftHealed,
    jawChewingPainLeftStillHave,
    jawChewingPainLeftImprovedLittle,
    jawChewingPainLeftImprovedMedium,
    jawChewingPainLeftImprovedLot,
    jawChewingPainLeftNotImproving,
    jawChewingPainLeftGettingWorse,

    jawChewingPainRightNever,
    jawChewingPainRightHealed,
    jawChewingPainRightStillHave,
    jawChewingPainRightImprovedLittle,
    jawChewingPainRightImprovedMedium,
    jawChewingPainRightImprovedLot,
    jawChewingPainRightNotImproving,
    jawChewingPainRightGettingWorse,

    facePainNever,
    facePainHealed,
    facePainStillHave,
    facePainImprovedLittle,
    facePainImprovedMedium,
    facePainImprovedLot,
    facePainNotImproving,
    facePainGettingWorse,

    chestribsPainNever,
    chestribsPainHealed,
    chestribsPainStillHave,
    chestribsPainImprovedLittle,
    chestribsPainImprovedMedium,
    chestribsPainImprovedLot,
    chestribsPainNotImproving,
    chestribsPainGettingWorse,

    stomachPainNever,
    stomachPainHealed,
    stomachPainStillHave,
    stomachPainImprovedLittle,
    stomachPainImprovedMedium,
    stomachPainImprovedLot,
    stomachPainNotImproving,
    stomachPainGettingWorse,

    BrnisesonNever,
    BrnisesonHealed,
    BrnisesonStillHave,
    BrnisesonImprovedLittle,
    BrnisesonImprovedMedium,
    BrnisesonImprovedLot,
    BrnisesonNotImproving,
    BrnisesonGettingWorse,

    cutsscrapesOnNever,
    cutsscrapesOnHealed,
    cutsscrapesOnStillHave,
    cutsscrapesOnImprovedLittle,
    cutsscrapesOnImprovedMedium,
    cutsscrapesOnImprovedLot,
    cutsscrapesOnNotImproving,
    cutsscrapesOnGettingWorse,

    scarsOnNever,
    scarsOnHealed,
    scarsOnStillHave,
    scarsOnImprovedLittle,
    scarsOnImprovedMedium,
    scarsOnImprovedLot,
    scarsOnNotImproving,
    scarsOnGettingWorse,

    numbtinglingArmHandLeftNever,
    numbtinglingArmHandLeftHealed,
    numbtinglingArmHandLeftStillHave,
    numbtinglingArmHandLeftImprovedLittle,
    numbtinglingArmHandLeftImprovedMedium,
    numbtinglingArmHandLeftImprovedLot,
    numbtinglingArmHandLeftNotImproving,
    numbtinglingArmHandLeftGettingWorse,

    numbtinglingArmHandRightNever,
    numbtinglingArmHandRightHealed,
    numbtinglingArmHandRightStillHave,
    numbtinglingArmHandRightImprovedLittle,
    numbtinglingArmHandRightImprovedMedium,
    numbtinglingArmHandRightImprovedLot,
    numbtinglingArmHandRightNotImproving,
    numbtinglingArmHandRightGettingWorse,

    numbtinglingLegFootLeftNever,
    numbtinglingLegFootLeftHealed,
    numbtinglingLegFootLeftStillHave,
    numbtinglingLegFootLeftImprovedLittle,
    numbtinglingLegFootLeftImprovedMedium,
    numbtinglingLegFootLeftImprovedLot,
    numbtinglingLegFootLeftNotImproving,
    numbtinglingLegFootLeftGettingWorse,

    numbtinglingLegFootRightNever,
    numbtinglingLegFootRightHealed,
    numbtinglingLegFootRightStillHave,
    numbtinglingLegFootRightImprovedLittle,
    numbtinglingLegFootRightImprovedMedium,
    numbtinglingLegFootRightImprovedLot,
    numbtinglingLegFootRightNotImproving,
    numbtinglingLegFootRightGettingWorse,

    weakclumsyArmHandLeftNever,
    weakclumsyArmHandLeftHealed,
    weakclumsyArmHandLeftStillHave,
    weakclumsyArmHandLeftImprovedLittle,
    weakclumsyArmHandLeftImprovedMedium,
    weakclumsyArmHandLeftImprovedLot,
    weakclumsyArmHandLeftNotImproving,
    weakclumsyArmHandLeftGettingWorse,

    weakclumsyArmHandRightNever,
    weakclumsyArmHandRightHealed,
    weakclumsyArmHandRightStillHave,
    weakclumsyArmHandRightImprovedLittle,
    weakclumsyArmHandRightImprovedMedium,
    weakclumsyArmHandRightImprovedLot,
    weakclumsyArmHandRightNotImproving,
    weakclumsyArmHandRightGettingWorse,

    weakclumsyLegFootLeftNever,
    weakclumsyLegFootLeftHealed,
    weakclumsyLegFootLeftStillHave,
    weakclumsyLegFootLeftImprovedLittle,
    weakclumsyLegFootLeftImprovedMedium,
    weakclumsyLegFootLeftImprovedLot,
    weakclumsyLegFootLeftNotImproving,
    weakclumsyLegFootLeftGettingWorse,

    weakclumsyLegFootRightNever,
    weakclumsyLegFootRightHealed,
    weakclumsyLegFootRightStillHave,
    weakclumsyLegFootRightImprovedLittle,
    weakclumsyLegFootRightImprovedMedium,
    weakclumsyLegFootRightImprovedLot,
    weakclumsyLegFootRightNotImproving,
    weakclumsyLegFootRightGettingWorse,

    stiffnessInJointsNever,
    stiffnessInJointsHealed,
    stiffnessInJointsStillHave,
    stiffnessInJointsImprovedLittle,
    stiffnessInJointsImprovedMedium,
    stiffnessInJointsImprovedLot,
    stiffnessInJointsNotImproving,
    stiffnessInJointsGettingWorse,

    headachesNever,
    headachesHealed,
    headachesStillHave,
    headachesImprovedLittle,
    headachesImprovedMedium,
    headachesImprovedLot,
    headachesNotImproving,
    headachesGettingWorse,

    SoreorSpasmInMusclesNever,
    SoreorSpasmInMusclesHealed,
    SoreorSpasmInMusclesStillHave,
    SoreorSpasmInMusclesImprovedLittle,
    SoreorSpasmInMusclesImprovedMedium,
    SoreorSpasmInMusclesImprovedLot,
    SoreorSpasmInMusclesNotImproving,
    SoreorSpasmInMusclesGettingWorse,

    lightheadedNever,
    lightheadedHealed,
    lightheadedStillHave,
    lightheadedImprovedLittle,
    lightheadedImprovedMedium,
    lightheadedImprovedLot,
    lightheadedNotImproving,
    lightheadedGettingWorse,

    visionChangesNever,
    visionChangesHealed,
    visionChangesStillHave,
    visionChangesImprovedLittle,
    visionChangesImprovedMedium,
    visionChangesImprovedLot,
    visionChangesNotImproving,
    visionChangesGettingWorse,

    sleepChangesNever,
    sleepChangesHealed,
    sleepChangesStillHave,
    sleepChangesImprovedLittle,
    sleepChangesImprovedMedium,
    sleepChangesImprovedLot,
    sleepChangesNotImproving,
    sleepChangesGettingWorse,

    radiatingPainNever,
    radiatingPainHealed,
    radiatingPainStillHave,
    radiatingPainImprovedLittle,
    radiatingPainImprovedMedium,
    radiatingPainImprovedLot,
    radiatingPainNotImproving,
    radiatingPainGettingWorse,

    anxietyNever,
    anxietyHealed,
    anxietyStillHave,
    anxietyImprovedLittle,
    anxietyImprovedMedium,
    anxietyImprovedLot,
    anxietyNotImproving,
    anxietyGettingWorse,

    lackOfEnthusiasmNever,
    lackOfEnthusiasmHealed,
    lackOfEnthusiasmStillHave,
    lackOfEnthusiasmImprovedLittle,
    lackOfEnthusiasmImprovedMedium,
    lackOfEnthusiasmImprovedLot,
    lackOfEnthusiasmNotImproving,
    lackOfEnthusiasmGettingWorse,

    medicationsNever,
    PatientSignature,
    DrSignature,
    // medicationsImprovedLittle, medicationsImprovedMedium,medicationsImprovedLot,
    // medicationsNotImproving,medicationsGettingWorse,
  },
} = checkout;

const initialValues = {
  form7: [
    {
      patient6: "",
      date6: "",
      dateofInjury6: "",
      formCreatedDate: moment().format("DD-MM-YYYY"),
      [clunkSoundwithNeckNever.name]: "",
      [clunkSoundwithNeckHealed.name]: "",
      [clunkSoundwithNeckStillHave.name]: "",
      [clunkSoundwithNeckImprovedLittle.name]: "",
      [clunkSoundwithNeckImprovedMedium.name]: "",
      [clunkSoundwithNeckImprovedLot.name]: "",
      [clunkSoundwithNeckNotImproving.name]: "",
      [clunkSoundwithNeckGettingWorse.name]: "",

      [neckPainNever.name]: "",
      [neckPainHealed.name]: "",
      [neckPainStillHave.name]: "",
      [neckPainImprovedLittle.name]: "",
      [neckPainImprovedMedium.name]: "",
      [neckPainImprovedLot.name]: "",
      [neckPainNotImproving.name]: "",
      [neckPainGettingWorse.name]: "",

      [upperBackPainNever.name]: "",
      [upperBackPainHealed.name]: "",
      [upperBackPainStillHave.name]: "",
      [upperBackPainImprovedLittle.name]: "",
      [upperBackPainImprovedMedium.name]: "",
      [upperBackPainImprovedLot.name]: "",
      [upperBackPainNotImproving.name]: "",
      [upperBackPainGettingWorse.name]: "",

      [lowBackPainNever.name]: "",
      [lowBackPainHealed.name]: "",
      [lowBackPainStillHave.name]: "",
      [lowBackPainImprovedLittle.name]: "",
      [lowBackPainImprovedMedium.name]: "",
      [lowBackPainImprovedLot.name]: "",
      [lowBackPainNotImproving.name]: "",
      [lowBackPainGettingWorse.name]: "",

      [shoulderPainLeftNever.name]: "",
      [shoulderPainLeftHealed.name]: "",
      [shoulderPainLeftStillHave.name]: "",
      [shoulderPainLeftImprovedLittle.name]: "",
      [shoulderPainLeftImprovedMedium.name]: "",
      [shoulderPainLeftImprovedLot.name]: "",
      [shoulderPainLeftNotImproving.name]: "",
      [shoulderPainLeftGettingWorse.name]: "",

      [shoulderPainRightNever.name]: "",
      [shoulderPainRightHealed.name]: "",
      [shoulderPainRightStillHave.name]: "",
      [shoulderPainRightImprovedLittle.name]: "",
      [shoulderPainRightImprovedMedium.name]: "",
      [shoulderPainRightImprovedLot.name]: "",
      [shoulderPainRightNotImproving.name]: "",
      [shoulderPainRightGettingWorse.name]: "",

      // kk

      [elbowPainLeftNever.name]: "",
      [elbowPainLeftHealed.name]: "",
      [elbowPainLeftStillHave.name]: "",
      [elbowPainLeftImprovedLittle.name]: "",
      [elbowPainLeftImprovedMedium.name]: "",
      [elbowPainLeftImprovedLot.name]: "",
      [elbowPainLeftNotImproving.name]: "",
      [elbowPainLeftGettingWorse.name]: "",

      [elbowPainRightNever.name]: "",
      [elbowPainRightHealed.name]: "",
      [elbowPainRightStillHave.name]: "",
      [elbowPainRightImprovedLittle.name]: "",
      [elbowPainRightImprovedMedium.name]: "",
      [elbowPainRightImprovedLot.name]: "",
      [elbowPainRightNotImproving.name]: "",
      [elbowPainRightGettingWorse.name]: "",

      [wristPainLeftNever.name]: "",
      [wristPainLeftHealed.name]: "",
      [wristPainLeftStillHave.name]: "",
      [wristPainLeftImprovedLittle.name]: "",
      [wristPainLeftImprovedMedium.name]: "",
      [wristPainLeftImprovedLot.name]: "",
      [wristPainLeftNotImproving.name]: "",
      [wristPainLeftGettingWorse.name]: "",

      [wristPainRightNever.name]: "",
      [wristPainRightHealed.name]: "",
      [wristPainRightStillHave.name]: "",
      [wristPainRightImprovedLittle.name]: "",
      [wristPainRightImprovedMedium.name]: "",
      [wristPainRightImprovedLot.name]: "",
      [wristPainRightNotImproving.name]: "",
      [wristPainRightGettingWorse.name]: "",

      [handfingerPainLeftNever.name]: "",
      [handfingerPainLeftHealed.name]: "",
      [handfingerPainLeftStillHave.name]: "",
      [handfingerPainLeftImprovedLittle.name]: "",
      [handfingerPainLeftImprovedMedium.name]: "",
      [handfingerPainLeftImprovedLot.name]: "",
      [handfingerPainLeftNotImproving.name]: "",
      [handfingerPainLeftGettingWorse.name]: "",

      [handfingerPainRightNever.name]: "",
      [handfingerPainRightHealed.name]: "",
      [handfingerPainRightStillHave.name]: "",
      [handfingerPainRightImprovedLittle.name]: "",
      [handfingerPainRightImprovedMedium.name]: "",
      [handfingerPainRightImprovedLot.name]: "",
      [handfingerPainRightNotImproving.name]: "",
      [handfingerPainRightGettingWorse.name]: "",

      [hipPainLeftNever.name]: "",
      [hipPainLeftHealed.name]: "",
      [hipPainLeftStillHave.name]: "",
      [hipPainLeftImprovedLittle.name]: "",
      [hipPainLeftImprovedMedium.name]: "",
      [hipPainLeftImprovedLot.name]: "",
      [hipPainLeftNotImproving.name]: "",
      [hipPainLeftGettingWorse.name]: "",

      [hipPainRightNever.name]: "",
      [hipPainRightHealed.name]: "",
      [hipPainRightStillHave.name]: "",
      [hipPainRightImprovedLittle.name]: "",
      [hipPainRightImprovedMedium.name]: "",
      [hipPainRightImprovedLot.name]: "",
      [hipPainRightNotImproving.name]: "",
      [hipPainRightGettingWorse.name]: "",

      [kneePainLeftNever.name]: "",
      [kneePainLeftHealed.name]: "",
      [kneePainLeftStillHave.name]: "",
      [kneePainLeftImprovedLittle.name]: "",
      [kneePainLeftImprovedMedium.name]: "",
      [kneePainLeftImprovedLot.name]: "",
      [kneePainLeftNotImproving.name]: "",
      [kneePainLeftGettingWorse.name]: "",

      [kneePainRightNever.name]: "",
      [kneePainRightHealed.name]: "",
      [kneePainRightStillHave.name]: "",
      [kneePainRightImprovedLittle.name]: "",
      [kneePainRightImprovedMedium.name]: "",
      [kneePainRightImprovedLot.name]: "",
      [kneePainRightNotImproving.name]: "",
      [kneePainRightGettingWorse.name]: "",

      [ankleFootpainLeftNever.name]: "",
      [ankleFootpainLeftHealed.name]: "",
      [ankleFootpainLeftStillHave.name]: "",
      [ankleFootpainLeftImprovedLittle.name]: "",
      [ankleFootpainLeftImprovedMedium.name]: "",
      [ankleFootpainLeftImprovedLot.name]: "",
      [ankleFootpainLeftNotImproving.name]: "",
      [ankleFootpainLeftGettingWorse.name]: "",

      [ankleFootpainRightNever.name]: "",
      [ankleFootpainRightHealed.name]: "",
      [ankleFootpainRightStillHave.name]: "",
      [ankleFootpainRightImprovedLittle.name]: "",
      [ankleFootpainRightImprovedMedium.name]: "",
      [ankleFootpainRightImprovedLot.name]: "",
      [ankleFootpainRightNotImproving.name]: "",
      [ankleFootpainRightGettingWorse.name]: "",

      [jawChewingPainLeftNever.name]: "",
      [jawChewingPainLeftHealed.name]: "",
      [jawChewingPainLeftStillHave.name]: "",
      [jawChewingPainLeftImprovedLittle.name]: "",
      [jawChewingPainLeftImprovedMedium.name]: "",
      [jawChewingPainLeftImprovedLot.name]: "",
      [jawChewingPainLeftNotImproving.name]: "",
      [jawChewingPainLeftGettingWorse.name]: "",

      [jawChewingPainRightNever.name]: "",
      [jawChewingPainRightHealed.name]: "",
      [jawChewingPainRightStillHave.name]: "",
      [jawChewingPainRightImprovedLittle.name]: "",
      [jawChewingPainRightImprovedMedium.name]: "",
      [jawChewingPainRightImprovedLot.name]: "",
      [jawChewingPainRightNotImproving.name]: "",
      [jawChewingPainRightGettingWorse.name]: "",

      [facePainNever.name]: "",
      [facePainHealed.name]: "",
      [facePainStillHave.name]: "",
      [facePainImprovedLittle.name]: "",
      [facePainImprovedMedium.name]: "",
      [facePainImprovedLot.name]: "",
      [facePainNotImproving.name]: "",
      [facePainGettingWorse.name]: "",

      [chestribsPainNever.name]: "",
      [chestribsPainHealed.name]: "",
      [chestribsPainStillHave.name]: "",
      [chestribsPainImprovedLittle.name]: "",
      [chestribsPainImprovedMedium.name]: "",
      [chestribsPainImprovedLot.name]: "",
      [chestribsPainNotImproving.name]: "",
      [chestribsPainGettingWorse.name]: "",

      [stomachPainNever.name]: "",
      [stomachPainHealed.name]: "",
      [stomachPainStillHave.name]: "",
      [stomachPainImprovedLittle.name]: "",
      [stomachPainImprovedMedium.name]: "",
      [stomachPainImprovedLot.name]: "",
      [stomachPainNotImproving.name]: "",
      [stomachPainGettingWorse.name]: "",

      [BrnisesonNever.name]: "",
      [BrnisesonHealed.name]: "",
      [BrnisesonStillHave.name]: "",
      [BrnisesonImprovedLittle.name]: "",
      [BrnisesonImprovedMedium.name]: "",
      [BrnisesonImprovedLot.name]: "",
      [BrnisesonNotImproving.name]: "",
      [BrnisesonGettingWorse.name]: "",

      [cutsscrapesOnNever.name]: "",
      [cutsscrapesOnHealed.name]: "",
      [cutsscrapesOnStillHave.name]: "",
      [cutsscrapesOnImprovedLittle.name]: "",
      [cutsscrapesOnImprovedMedium.name]: "",
      [cutsscrapesOnImprovedLot.name]: "",
      [cutsscrapesOnNotImproving.name]: "",
      [cutsscrapesOnGettingWorse.name]: "",

      [scarsOnNever.name]: "",
      [scarsOnHealed.name]: "",
      [scarsOnStillHave.name]: "",
      [scarsOnImprovedLittle.name]: "",
      [scarsOnImprovedMedium.name]: "",
      [scarsOnImprovedLot.name]: "",
      [scarsOnNotImproving.name]: "",
      [scarsOnGettingWorse.name]: "",

      [numbtinglingArmHandLeftNever.name]: "",
      [numbtinglingArmHandLeftHealed.name]: "",
      [numbtinglingArmHandLeftStillHave.name]: "",
      [numbtinglingArmHandLeftImprovedLittle.name]: "",
      [numbtinglingArmHandLeftImprovedMedium.name]: "",
      [numbtinglingArmHandLeftImprovedLot.name]: "",
      [numbtinglingArmHandLeftNotImproving.name]: "",
      [numbtinglingArmHandLeftGettingWorse.name]: "",

      [numbtinglingArmHandRightNever.name]: "",
      [numbtinglingArmHandRightHealed.name]: "",
      [numbtinglingArmHandRightStillHave.name]: "",
      [numbtinglingArmHandRightImprovedLittle.name]: "",
      [numbtinglingArmHandRightImprovedMedium.name]: "",
      [numbtinglingArmHandRightImprovedLot.name]: "",
      [numbtinglingArmHandRightNotImproving.name]: "",
      [numbtinglingArmHandRightGettingWorse.name]: "",

      [numbtinglingLegFootLeftNever.name]: "",
      [numbtinglingLegFootLeftHealed.name]: "",
      [numbtinglingLegFootLeftStillHave.name]: "",
      [numbtinglingLegFootLeftImprovedLittle.name]: "",
      [numbtinglingLegFootLeftImprovedMedium.name]: "",
      [numbtinglingLegFootLeftImprovedLot.name]: "",
      [numbtinglingLegFootLeftNotImproving.name]: "",
      [numbtinglingLegFootLeftGettingWorse.name]: "",

      [numbtinglingLegFootRightNever.name]: "",
      [numbtinglingLegFootRightHealed.name]: "",
      [numbtinglingLegFootRightStillHave.name]: "",
      [numbtinglingLegFootRightImprovedLittle.name]: "",
      [numbtinglingLegFootRightImprovedMedium.name]: "",
      [numbtinglingLegFootRightImprovedLot.name]: "",
      [numbtinglingLegFootRightNotImproving.name]: "",
      [numbtinglingLegFootRightGettingWorse.name]: "",

      [weakclumsyArmHandLeftNever.name]: "",
      [weakclumsyArmHandLeftHealed.name]: "",
      [weakclumsyArmHandLeftStillHave.name]: "",
      [weakclumsyArmHandLeftImprovedLittle.name]: "",
      [weakclumsyArmHandLeftImprovedMedium.name]: "",
      [weakclumsyArmHandLeftImprovedLot.name]: "",
      [weakclumsyArmHandLeftNotImproving.name]: "",
      [weakclumsyArmHandLeftGettingWorse.name]: "",

      [weakclumsyArmHandRightNever.name]: "",
      [weakclumsyArmHandRightHealed.name]: "",
      [weakclumsyArmHandRightStillHave.name]: "",
      [weakclumsyArmHandRightImprovedLittle.name]: "",
      [weakclumsyArmHandRightImprovedMedium.name]: "",
      [weakclumsyArmHandRightImprovedLot.name]: "",
      [weakclumsyArmHandRightNotImproving.name]: "",
      [weakclumsyArmHandRightGettingWorse.name]: "",

      [weakclumsyLegFootLeftNever.name]: "",
      [weakclumsyLegFootLeftHealed.name]: "",
      [weakclumsyLegFootLeftStillHave.name]: "",
      [weakclumsyLegFootLeftImprovedLittle.name]: "",
      [weakclumsyLegFootLeftImprovedMedium.name]: "",
      [weakclumsyLegFootLeftImprovedLot.name]: "",
      [weakclumsyLegFootLeftNotImproving.name]: "",
      [weakclumsyLegFootLeftGettingWorse.name]: "",

      [weakclumsyLegFootRightNever.name]: "",
      [weakclumsyLegFootRightHealed.name]: "",
      [weakclumsyLegFootRightStillHave.name]: "",
      [weakclumsyLegFootRightImprovedLittle.name]: "",
      [weakclumsyLegFootRightImprovedMedium.name]: "",
      [weakclumsyLegFootRightImprovedLot.name]: "",
      [weakclumsyLegFootRightNotImproving.name]: "",
      [weakclumsyLegFootRightGettingWorse.name]: "",

      [stiffnessInJointsNever.name]: "",
      [stiffnessInJointsHealed.name]: "",
      [stiffnessInJointsStillHave.name]: "",
      [stiffnessInJointsImprovedLittle.name]: "",
      [stiffnessInJointsImprovedMedium.name]: "",
      [stiffnessInJointsImprovedLot.name]: "",
      [stiffnessInJointsNotImproving.name]: "",
      [stiffnessInJointsGettingWorse.name]: "",

      [headachesNever.name]: "",
      [headachesHealed.name]: "",
      [headachesStillHave.name]: "",
      [headachesImprovedLittle.name]: "",
      [headachesImprovedMedium.name]: "",
      [headachesImprovedLot.name]: "",
      [headachesNotImproving.name]: "",
      [headachesGettingWorse.name]: "",

      [SoreorSpasmInMusclesNever.name]: "",
      [SoreorSpasmInMusclesHealed.name]: "",
      [SoreorSpasmInMusclesStillHave.name]: "",
      [SoreorSpasmInMusclesImprovedLittle.name]: "",
      [SoreorSpasmInMusclesImprovedMedium.name]: "",
      [SoreorSpasmInMusclesImprovedLot.name]: "",
      [SoreorSpasmInMusclesNotImproving.name]: "",
      [SoreorSpasmInMusclesGettingWorse.name]: "",

      [lightheadedNever.name]: "",
      [lightheadedHealed.name]: "",
      [lightheadedStillHave.name]: "",
      [lightheadedImprovedLittle.name]: "",
      [lightheadedImprovedMedium.name]: "",
      [lightheadedImprovedLot.name]: "",
      [lightheadedNotImproving.name]: "",
      [lightheadedGettingWorse.name]: "",

      [visionChangesNever.name]: "",
      [visionChangesHealed.name]: "",
      [visionChangesStillHave.name]: "",
      [visionChangesImprovedLittle.name]: "",
      [visionChangesImprovedMedium.name]: "",
      [visionChangesImprovedLot.name]: "",
      [visionChangesNotImproving.name]: "",
      [visionChangesGettingWorse.name]: "",

      [sleepChangesNever.name]: "",
      [sleepChangesHealed.name]: "",
      [sleepChangesStillHave.name]: "",
      [sleepChangesImprovedLittle.name]: "",
      [sleepChangesImprovedMedium.name]: "",
      [sleepChangesImprovedLot.name]: "",
      [sleepChangesNotImproving.name]: "",
      [sleepChangesGettingWorse.name]: "",

      [radiatingPainNever.name]: "",
      [radiatingPainHealed.name]: "",
      [radiatingPainStillHave.name]: "",
      [radiatingPainImprovedLittle.name]: "",
      [radiatingPainImprovedMedium.name]: "",
      [radiatingPainImprovedLot.name]: "",
      [radiatingPainNotImproving.name]: "",
      [radiatingPainGettingWorse.name]: "",

      [anxietyNever.name]: "",
      [anxietyHealed.name]: "",
      [anxietyStillHave.name]: "",
      [anxietyImprovedLittle.name]: "",
      [anxietyImprovedMedium.name]: "",
      [anxietyImprovedLot.name]: "",
      [anxietyNotImproving.name]: "",
      [anxietyGettingWorse.name]: "",

      [lackOfEnthusiasmNever.name]: "",
      [lackOfEnthusiasmHealed.name]: "",
      [lackOfEnthusiasmStillHave.name]: "",
      [lackOfEnthusiasmImprovedLittle.name]: "",
      [lackOfEnthusiasmImprovedMedium.name]: "",
      [lackOfEnthusiasmImprovedLot.name]: "",
      [lackOfEnthusiasmNotImproving.name]: "",
      [lackOfEnthusiasmGettingWorse.name]: "",

      [medicationsNever.name]: "",
      [PatientSignature.name]: "",
      [DrSignature.name]: "",
      // [medicationsImprovedLittle.name] : "",
      // [medicationsImprovedMedium.name] : "",
      // [medicationsImprovedLot.name] : "",
      // [medicationsNotImproving.name] : "",
      // [medicationsGettingWorse.name] : "",

      symptomsupdate: [
        {
          name: "Clunk sound with neck movements",
        },
        {
          name: "Neck pain",
        },
        {
          name: "Upper back pain",
        },
        {
          name: "Low back pain",
        },
        {
          name: "Shoulder pain (left)",
        },
        {
          name: "Shoulder pain (right)",
        },
        {
          name: "Elbow pain (left)",
        },
        {
          name: "Elbow pain (right)",
        },
        {
          name: "Wrist pain (left)",
        },
        {
          name: "Wrist pain (right)",
        },
        {
          name: "Hand/finger pain (left)",
        },
        {
          name: "Hip _pain (left)",
        },
        {
          name: "Hip _pain (right)",
        },
        {
          name: "Knee pain (left)",
        },
        {
          name: "Knee pain (right)",
        },
        {
          name: "Ankle/foot pain (left)",
        },
        {
          name: "Ankle/foot pain (right)",
        },
        {
          name: "Jaw/chewing pain (left)",
        },
        {
          name: "Jaw/chewing pain (right)",
        },
        {
          name: "Face pain",
        },
        {
          name: "Chest/ribs pain",
        },
        {
          name: "Stomach pain",
        },
        {
          name: "Brnises on",
        },
        {
          name: "Cuts/scrapes on",
        },
        {
          name: "Scars on",
        },
        {
          name: "Numb/tingling arm/hand (left)",
        },
        {
          name: "numb/tingling arm/hand (right)",
        },
        {
          name: "Numb/tingling leg/foot (left)",
        },
        {
          name: "Numb/tingling leg/foot (right)",
        },
        {
          name: "Weak/clumsy arm/hand left)",
        },
        {
          name: "Weak/clumsy arm/hand (right)",
        },
        {
          name: "Weak/clumsy leg/foot (left)",
        },
        {
          name: "Weak/clumsy leg/foot (right)",
        },
        {
          name: "Stiffness in joints",
        },
        {
          name: "Headaches",
        },
        {
          name: "Sore or spasm in muscles",
        },
        {
          name: "Dizzy/lightheaded/woozy",
        },
        {
          name: "Vision changes",
        },
        {
          name: "Sleep changes",
        },
        {
          name: "Radiating pain",
        },
        {
          name: "Anxiety/nervousness",
        },
        {
          name: "Lack of enthusiasm for life",
        },
        {
          name: "I take these medications",
        },
      ],
    },
  ],
  name : ""
};

export default initialValues;
