const initialValues = {

    patientp4 : "",
    datep4 : "",
    dateofInjuryp4 : "",

    signatureOfDoctor: "",
    
    //cervical spine
    cervicalcheck1 : false,
    cervicalcheck2 : false,
    cervicalcheck3 : false,
    cervicalcheck4 : false,
    cervicalcheck5 : false,

    cervicalcheck6 : false,
    cervicalinput6 : "",
    cervicalcheck7 : false,
    cervicalinput7 : "",

    cervicalcheck8 : false,
    cervicalcheck9 : false,
    cervicalcheck10 : false,
    cervicalcheck11 : false,
    cervicalinput11 : "",
    cervicalcheck12 : false,
    cervicalinput12 : "",
    cervicalcheck13 : false,
    cervicalinput13 : "",
    cervicalcheck14 : false,
    cervicalcheck15 : false,
    cervicalcheck16 : false,
    cervicalcheck17 : false,
    cervicalcheck18 : false,
    cervicalcheck19 : false,
    cervicalcheck20 : false,
    cervicalcheck21 : false,
    cervicalcheck22 : false,
    cervicalcheck23 : false,
    cervicalcheck24 : false,

    //upper extrimity
    upextrimitycheck1 : false,
    upextrimitycheck2 : false,
    upextrimitycheck3 : false,
    upextrimitycheck4 : false,
    upextrimitycheck5 : false,
    upextrimitycheck6 : false,
    upextrimityinput6 : "",
    upextrimitycheck7 : false,
    upextrimityinput7 : "",
    upextrimitycheck8 : false,
    upextrimitycheck9 : false,
    upextrimitycheck10 : false,
    upextrimitycheck11 : false,
    upextrimityinput11 : "",
    upextrimitycheck12 : false,
    upextrimityinput12 : "",
    upextrimitycheck13 : false,
    upextrimitycheck14 : false,
    upextrimitycheck15 : false,
    upextrimitycheck16 : false,
    upextrimitycheck17 : false,
    upextrimitycheck18 : false,
    upextrimitycheck19 : false,
    upextrimitycheck20 : false,
    upextrimitycheck21 : false,
    upextrimitycheck22 : false,
    upextrimitycheck23 : false,
    upextrimitycheck24 : false,

    //lower extrimity
    lowxtrimitycheck1 : false,
    lowxtrimitycheck2 : false,
    lowxtrimitycheck3 : false,
    lowxtrimitycheck4 : false,
    lowxtrimitycheck5 : false,
    lowxtrimitycheck6 : false,
    lowxtrimityinput6 : "",
    lowxtrimitycheck7 : false,
    lowxtrimityinput7 : "",
    lowxtrimitycheck8 : false,
    lowxtrimitycheck9 : false,
    lowxtrimitycheck10 : false,
    lowxtrimitycheck11 : false,
    lowxtrimityinput11 : "",
    lowxtrimitycheck12 : false,
    lowxtrimityinput12 : "",
    lowxtrimitycheck13 : false,
    lowxtrimitycheck14 : false,
    lowxtrimitycheck15 : false,
    lowxtrimitycheck16 : false,
    lowxtrimitycheck17 : false,
    lowxtrimitycheck18 : false,
    lowxtrimitycheck19 : false,
    lowxtrimitycheck20 : false,
    lowxtrimitycheck21 : false,
    lowxtrimitycheck22 : false,
    lowxtrimitycheck23 : false,
    lowxtrimitycheck24 : false,


    //pelvis
     //lower extrimity
     pelvischeck1 : false,
     pelvischeck2 : false,
     pelvischeck3 : false,
     pelvischeck4 : false,
     pelvischeck5 : false,
     pelvischeck6 : false,
     pelvisinput6 : "",
     pelvischeck7 : false,
     pelvisinput7 : "",
     pelvischeck8 : false,
     pelvischeck9 : false,
     pelvischeck10 : false,
     pelvischeck11 : false,
     pelvisinput11 : "",
     pelvischeck12 : false,
     pelvisinput12 : "",
     pelvischeck13 : false,
     pelvischeck14 : false,
     pelvischeck15 : false,
     pelvischeck16 : false,
     pelvischeck17 : false,
     pelvischeck18 : false,
     pelvischeck19 : false,
     pelvischeck20 : false,
     pelvischeck21 : false,
     pelvischeck22 : false,
     pelvischeck23 : false,
     pelvischeck24 : false,

    //backInjury
    braincheck1 : false,
    braincheck2 : false,
    braincheck3 : false,
    braincheck4 : false,
    braininput4 : "",
    braincheck5 : false,
    braincheck6 : false,
    braincheck7 : false,
    braincheck8 : false,
    braincheck9 : false,
    braincheck10 : false,
    braincheck11 : false,
    braincheck12 : false,
    braincheck13 : false,
    braincheck14 : false,
    braininput14 : "",

    //thorasicSpine
    thorasiccheck1 : false,
    thorasiccheck2 : false,
    thorasiccheck3 : false,
    thorasiccheck4 : false,
    thorasiccheck5 : false,
    thorasiccheck6 : false,
    thorasicinput6 : "",
    thorasiccheck7 : false,
    thorasicinput7 : "",
    thorasiccheck8 : false,
    thorasiccheck9 : false,
    thorasiccheck10 : false,
    thorasiccheck11 : false,
    thorasicinput11 : "",
    thorasiccheck12 : false,
    thorasicinput12 : "",
    thorasiccheck13 : false,
    thorasicinput13 : "",
    thorasiccheck14 : false,
    thorasiccheck15 : false,
    thorasiccheck16 : false,
    thorasiccheck17 : false,
    thorasiccheck18 : false,
    thorasiccheck19 : false,
    thorasiccheck20 : false,
    thorasiccheck21 : false,
    thorasiccheck22 : false,
    thorasiccheck23 : false,
    thorasiccheck24 : false,


    //LumberSpine
    lumbercheck1 : false,
    lumbercheck2 : false,
    lumbercheck3 : false,
    lumbercheck4 : false,
    lumbercheck5 : false,
    lumbercheck6 : false,
    lumberinput6 : "",
    lumbercheck7 : false,
    lumberinput7 : "",
    lumbercheck8 : false,
    lumbercheck9 : false,
    lumbercheck10 : false,
    lumbercheck11 : false,
    lumberinput11 : "",
    lumbercheck12 : false,
    lumberinput12 : "",
    lumbercheck13 : false,
    lumberinput13 : "",
    lumbercheck14 : false,
    lumbercheck15 : false,
    lumbercheck16 : false,
    lumbercheck17 : false,
    lumbercheck18 : false,
    lumbercheck19 : false,
    lumbercheck20 : false,
    lumbercheck21 : false,
    lumbercheck22 : false,
    lumbercheck23 : false,
    lumbercheck24 : false,

    //depression
    depresscheck1 : false,
    depresscheck2 : false,
    depresscheck3 : false,
    depresscheck4 : false,
    depresscheck5 : false,
    depresscheck6 : false,
    depresscheck7 : false,
    depresscheck8 : false,

    //TJM
    tjmcheck1 : false,
    tjmcheck2 : false,
    tjmcheck3 : false,
    tjmcheck4 : false,
    tjmcheck5 : false,
    tjmcheck6 : false,
    tjmcheck7 : false,
    tjmcheck8 : false,

    //misc
    miscinputpre1 : "",
    miscinputpost1 : "",
    miscinputpre2 : "",
    miscinputpost2 : "",
    misccheck1 : false,
    misccheck2 : false,
    misccheck3 : false,
    misccheck4 : false,
    misccheck5 : false,
    misccheck6 : false,
    misccheck7 : false,
    miscinput7 : "",
    misccheck8 : false,
  
}